### ISSUE TITLE
Sidebar missing

### ISSUE THREAD

**Issue by torstenkoepke** [chrisgrieser/shimmering-focus#1]
Great work - but how do I get to the sidebar on the left - I would like to use the "Customizable sidebar"-plugin also.

**Comment by chrisgrieser** [comment]
Thanks! In case you want to use the sidebars, you can just install the theme and delete the part in the CSS that removes the sidebar.

Just search for `.workspace-ribbon` to find the following code block, delete it, and save the CSS file. This is super simple and can be done with any text editor.

```css
.workspace-ribbon {
	display: none;
}
```

**Comment by torstenkoepke** [comment]
Thanks Chris - I was searching for sidebar in the css :-) Bloody beginner with css

**Comment by chrisgrieser** [comment]
you are welcome!

Yeah, I also only learned CSS by tinkering around with Obsidian CSS snippets. It's actually fun!

**Comment by chrisgrieser** [comment]
With [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4), I added support for the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/). Using that plugin, re-enabling the ribbon is now simply a mouse click.

This also allows you to install updates of _Shimmering Focus_ without having to re-delete those three lines of code every time 🙂
