### ISSUE TITLE
[Bug]:  Cannot Drag The Obsidian Application To Reposition With This Theme

### ISSUE THREAD

**Issue by niisakov** [chrisgrieser/shimmering-focus#103]
### Bug Description

When I select this theme, I cannot reposition Obsidian on the desktop any longer.  I can expand it vertically and horizontally, but I cannot reposition at all.

### To Reproduce

Select as the theme for Obsidian.

### Obsidian Version

0.13.23

### Installer Version

0.12.15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Not a bug, dragging the window requires the titlebar, which is hidden by default in this theme. 

Use the Style settings plugin to re-enable the title bar and you can drag the Obsidian window.
