### ISSUE TITLE
Feature Request: Change Highlighting color of "[[]]", especially in dark mode

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#104]
### Feature Requested

I love this theme, but embedding stuff can be difficult as the background color in dark mode almost perfectly mask visible embed-brackets.

In image 1, my cursor was in-between both closing brackets. 

Now, playing with the style settings can help... _marginally_.

Default dark mode style settings.

As "best" as I could get it with respect to this very specific problem.

However, the light difference necessary to make the brackets stand out make this hardly a dark mode anymore. It's grey, but it's no longer really _dark_.

(YMMV, on my 32" monitor that's a significant light difference because of the perceived cumulative increase of brightness associated with a large number of pixels increasing brightness). In the end, it's too bright for me if I need/want to work on a dark theme - which is the greater portion of my day.

I am not even sure if Obsidian/the theme would allow for it. I don't know if either are fundamentally capable of supporting such. 

Thank you.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/80548781/151679173-7aab449a-a883-4df0-a775-1db99ca12734.png)
 only highlighting brackets actually makes them properly visible
![image](https://user-images.githubusercontent.com/80548781/151679176-0fd99366-9dd2-4f93-8f9b-976320d2c7a5.png)

---

![image](https://user-images.githubusercontent.com/80548781/151679398-97ef96d8-2dc9-4928-ab13-37a7478f105e.png)

Direct color comparison:
![image](https://user-images.githubusercontent.com/80548781/151679685-fa712039-dc20-41c9-90a4-dadf3bbd5739.png)

---

Relevant Custom Colors-settings:
![image](https://user-images.githubusercontent.com/80548781/151679832-850190b1-b354-4868-8728-4858d1a44138.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
could you tell me the three values of the the dark mode custom colors you have set in the style settings, so I can take a look?

**Comment by Gewerd-Strauss** [comment]
Hello,

Brightness dark mode: 7
Hue: 220
Saturation: 6

These seem to be the default. I had to set up a fresh instance of obsidian on a new laptop because my old one died. While I simply copied my vault (and thus should have all plugins and my settings cloned over), I cannot deny that currently the issue doesn't seem as extremely bad anymore. It's still much more unpleasant than I would like it to be, but the brackets are no longer basically invisible. I am not exactly sure why this is the case. 
I could not yet check if this is an issue related to settings (and thus display-agnostic), or if it will be worse or better on my main display. Setup of this laptop has only been finished yesterday, and I have not had the chance to dock this laptop again. If, unlikely as it is, my main display gives a grave difference, I will update this thread.



![grafik](https://user-images.githubusercontent.com/80548781/161448700-67195f0e-af29-489d-be71-310306e6e63c.png)


---

P.S.: Sorry for the late reply, I have been rather busy the last few weeks.

**Comment by chrisgrieser** [comment]
got it, issue should be fixed in the latest update.

(It's quite tricky to keep things readable while at the same time offering tons of color customization.)

---

Also a heads up since I notice you are changing accent colors via a snippet: In preparation of a bigger color update, a lot of color variables in Shimmering Focus have been renamed, so your snippet won't work anymore after the update. Simply change use these variables to change accent colors again:

```css
	--primary-accent-1: hsl(250 50% 49%);
	--primary-accent-2: hsl(250 75% 64%);
	--primary-accent-3: hsl(250 90% 76%);
	--primary-accent-4: hsl(250 90% 83%);
```

**Comment by Gewerd-Strauss** [comment]
Hmm. I have a few snippets, but neither of them are active. 
However, I am using advanced appearance. And while a lot of that can be tracked over to style settings, I have not finished all the settings I need (not to mention the amount of trial and error I will need to get this right :P)

I realised this whole issue is wasting your time, because I forgot the plethora of stuff interacting on my end that you cannot know about. For that, I am sorry.

I can try and migrate an as-good-as-possible-approximation via style settings, but given that I need to do that in an extreme step by step process, it will take a while. I am currently relatively busy with university live, and although that doesn't excuse opening a BS ticket here I will try and get this migrated and inform you once I am done.

There are two issues that make this painful as fuck:

1. style settings has no search bar, and there are _a lot_ of settings to search through
2. as far as I could find, the theme's settings on style settings doesn't allow for differentiated editing of base color and accent color. Or maybe I am just utterly blind, but I couldn't find it. (aka, this is what I set up in advanced appearance:
![grafik](https://user-images.githubusercontent.com/80548781/161529413-7e2fc7b2-508e-41fb-8cf2-ed564c772303.png)
, while I could not find a "base color"-equivalent on the Style settings for shimmering focus)

I will do a bit more digging, and see how close to the initial screenshot I can get.

**Comment by chrisgrieser** [comment]
no worries! the bracket readability has been improved in the latest update.

Also, I am working on a bigger update that offers options to customize all accent colors. Will just take a bit, but then you will be able to customize everything :)

---

> style settings has no search bar, and there are a lot of settings to search through

![image](https://user-images.githubusercontent.com/73286100/161532686-a14c1fa3-1850-401b-806e-9c514b586e75.png)

https://obsidian.md/plugins?id=settings-search

also: https://github.com/mgmeyers/obsidian-style-settings/issues/51
