### ISSUE TITLE
Feature Request: Make the Unresolved Links brighter in the LP

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#105]
### Feature Requested

I want to make a request to make the unresolved links brighter in the Live Preview so that they can be seen more easily. Thanks. 

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/88898230/151900236-f3799ff0-7973-427a-aeba-af2e26e78307.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
oh that one is actually a bug, they are supposed to be better visible. I just use Live Preview so rarely, that I didn't notice :P

fixed.

**Comment by Liong1976** [comment]
Thanks a lot, Chris!
