### ISSUE TITLE
[Bug]: Pseudo-Admonition cuts off first letter in Preview mode

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#106]
### Bug Description

As mentioned in https://github.com/chrisgrieser/shimmering-focus/issues/87, the first letter gets partially cut off in Preview mode.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/152551946-f1255936-580e-4fa3-b050-2c9a5b547439.png)

### To Reproduce

1. Use Pseudo-Admonition ">>>"
2. write something
3. go to preview mode
4. see letter is cut off

### Obsidian Version

0.13.23

### Installer Version

0.12.15

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
I assume you already checked that it's not a css snippet interfering? 

Cause I tried it with different settings (zoom, font sizes, etc.) and it always looks right on my end. Could you keep an eye on it under what conditions that bug occurs? 🤔

**Comment by ReaderGuy42** [comment]
Yes, I just tried it in an empty vault (no plugins, no snippets) and it still happens. I'll try and see if I can narrow it down, but it seems to always be like this.
