### ISSUE TITLE
FR: Style Settings to change Accent Colors

### ISSUE THREAD

**Issue by xidsyed** [chrisgrieser/shimmering-focus#107]
### Bug Description

There isnt an option for it either

### Obsidian Version

0.13.23

### Installer Version

0.12.10

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
this isn't a bug, changing accent colors is simply not implemented yet in the theme :P

**Comment by xidsyed** [comment]
I guess. the reason I called it a bug was that i was using the minimal theme, and it had the option to change the link color, so i set it to purple, and as far as i remember California Coast had a Blue Link Accent color... But it has remained pruple... any idea how i can fix it?
