### ISSUE TITLE
Feature Request: Ability to change size of modals

### ISSUE THREAD

**Issue by spiritualgeek** [chrisgrieser/shimmering-focus#108]
### Feature Requested

Could you please consider the exposure of modal sizing through the Style Settings plug? Currently, the settings modal is huge on my 4K monitor and I can't easily see what I'm changing a setting for. Would be nice to have others, but it's not critical. Being able to change the font would be the cherry on top 

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
ah good idea, haven't thought of that one. luckily easy and quick to implement, so I just pushed an update that includes a style setting to change modal sizes.

> Being able to change the font would be the cherry on top

the cherry is already there, it's the menu font in the "Typography" section of the Style Settings :)

**Comment by spiritualgeek** [comment]
So awesome. Thank you so much! 

PS: I think styles setting has an issue with certain values on their sliders, but at least I got to set it to something more reasonable. Would be great to have this for the height as well.
