### ISSUE TITLE
[Bug]: Headings have visible outline and different color to background

### ISSUE THREAD

**Issue by AlexRimor** [chrisgrieser/shimmering-focus#111]
### Bug Description

With the latest update headings now have a different color to the background and a visible outline. See attached screenshot.

I have this theme in two vaults. The issue appears immediately after updating to the latest version of the theme.

### Relevant Screenshot

![Obsidian_CjGoK3DIRU](https://user-images.githubusercontent.com/81555748/152709310-30325687-63c1-43b9-b90f-c3b2fe9a3f67.png)

### To Reproduce

Update to the latest version of the theme as at 7th Feb 2022.

### Obsidian Version

0.13.23

### Installer Version

0.12.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by AlexRimor** [comment]
For me, reverting to a previous version of this theme resolves the issue for now.

**Comment by kngautham** [comment]
Install Style Settings and you have the option to turn on/off. The option is Remove Heading Background and its under typography.

**Comment by chrisgrieser** [comment]
It's a feature, not a bug 😉 

As kngautham said, there is a style setting option to turn it off.

**Comment by AlexRimor** [comment]
Ah ok thanks. I guess its a new feature?
Thanks @kngautham for telling me how to change it back to the way I like. And thank you @chrisgrieser for an amazing theme.
