### ISSUE TITLE
Feature Request: Unresolved Links as visible as Resolved Links in LP (Editor mode)

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#113]
### Feature Requested

I want to make a request to make unresolved links as visible as resolved links in LP (editor mode). Thanks

### Relevant Screenshot

Here is in the editor mode
![image](https://user-images.githubusercontent.com/88898230/152860405-0fbb97ac-6b65-4a3b-90c7-a019ceabc6a1.png)

Here is in the reading mode
![image](https://user-images.githubusercontent.com/88898230/152860491-12a4a658-f0c3-45fc-9d61-ad30617635c4.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
that's actually a bug :D
Nevertheless, fixed

**Comment by Liong1976** [comment]
Thanks!
