### ISSUE TITLE
[Bug]: Underline of a internal link is outside of header background in live preview

### ISSUE THREAD

**Issue by Achen19** [chrisgrieser/shimmering-focus#118]
### Bug Description

Underline of a internal link is outside of header background in live preview; looks fine in read mode. I have tried this with all heading sizes as well, issue persists

normal text in same header looks fine

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/41016414/154784198-84b4b6de-d296-496c-b928-a74666a630ba.png)

![image](https://user-images.githubusercontent.com/41016414/154784281-c7a2db82-7aaa-4a86-905d-86e04beff4dc.png)

### To Reproduce

be in liver preview mode
create header 
add a linked note to header

### Obsidian Version

0.13.23

### Installer Version

0.12.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn if off again.)

**Comment by chrisgrieser** [comment]
should be fixed in the latest update
