### ISSUE TITLE
Broken selection highlighting in preview

### ISSUE THREAD

**Issue by NomarCub** [chrisgrieser/shimmering-focus#12]
Preview selection highlighting uses black instead of the color set in the theme.

![image](https://user-images.githubusercontent.com/5298006/132949902-a2f76837-d0aa-43d5-b26f-b6edd106c981.png)

I have a local fix, that works with Obsidian's way of defining its `--text-selection` variable in its app.css (dark and light, respectively):

```css
--selection-color: rgba(60, 36, 59, 0.99);
--selection-color: rgba(232, 221, 255, 0.99);
```

**Comment by chrisgrieser** [comment]
That's weird. I am pretty much using the [same method](https://github.com/chrisgrieser/shimmering-focus/blob/bc5af6189bdd3bd94aaf7d4810d18b13233e069c/obsidian.css#L220) of [changing selection color](https://github.com/chrisgrieser/shimmering-focus/blob/bc5af6189bdd3bd94aaf7d4810d18b13233e069c/obsidian.css#L1461) already.

And for me, selections in preview mode look as they should:
<img width=40% alt="Screenshot 2021-09-11 15 54 49" src="https://user-images.githubusercontent.com/73286100/132950399-5cf27c70-7cee-40cf-b0d4-3638fd9a5bbe.png">

Did you do anything else to get that wrong coloring? Or do you maybe use a CSS snippet, that is interfering?

**Comment by NomarCub** [comment]
I specifically said the problem is in preview, as you can see on the screenshot. Your reply is in edit mode.

Their method is only slightly different - using rgba() and 0.99, - but it works for some reason.
The screenshot if of the Obsidian Help vault with only your theme added. No interference as far as I can tell.

**Comment by chrisgrieser** [comment]
oh sorry, I attached the wrong screenshot. Nevertheless, it also looks fine in preview mode to me?
<img width="1111" alt="Screenshot 2021-09-11 16 10 03" src="https://user-images.githubusercontent.com/73286100/132950719-83505742-f878-4b8c-816d-d1b5fd9a7b86.png">

**Comment by chrisgrieser** [comment]
I assume adding that 1% transparency shouldn't do any visual difference, so I assume it ensures proper overlaying of colors under certain conditions that appear to exist not on my device but on your device. As the [Wikipedia article on RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) implies, adding even 1% of transparency could have some functional purpose when overlaying colors.

> Alpha indicates how opaque each pixel is and allows an image to be combined over others using alpha compositing, with transparent areas and anti-aliasing of the edges of opaque regions.

Nayway, as adding such minor transparency does not make any visual difference but seems to fix things at least for some people, I have simply [added that in the latest version](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.6.1).
