### ISSUE TITLE
[Bug]: Banner plugin 

### ISSUE THREAD

**Issue by EhuddR** [chrisgrieser/shimmering-focus#120]
### Feature Requested

Hi, I would like to know if you could fix the way the banner plugin behaves inside the shimmering theme. The problem is that the images appear centered, I guess the theme uses by default the default cssclass for images of the theme and therefore does not use the plugin settings.  

### Right now it looks like this
![Screenshot_20220222_143726](https://user-images.githubusercontent.com/78237982/155206080-1eda25d8-1014-4858-a22f-6eb98c2664a9.png)

### It should look like this (Minimal Theme) 

![Screenshot_20220222_144302](https://user-images.githubusercontent.com/78237982/155206910-2d357278-a6d0-4484-8c46-2e7f557aac95.png)

### Relevance

- [x] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
fixed in latest release

**Comment by imeed166** [comment]
There is a gap at the top of the banner, is this intentional ?

https://user-images.githubusercontent.com/38974541/166684982-3957ad07-500a-4135-9d16-d425c8ebf91a.mov

**Comment by chrisgrieser** [comment]
Probably not, that space is actually the hot zone that actives the hidden header bar. The css for the hidden header bar is kinda tricky, I don't know whether it is possible to have a hidden header bar and the banners plugin active at the same time.

**Comment by imeed166** [comment]
The gap persists even if the header bar is visible.

**Comment by imeed166** [comment]
Alright.
