### ISSUE TITLE
[Bug]: wrong mono font for LaTeX commands

### ISSUE THREAD

**Issue by thudjx** [chrisgrieser/shimmering-focus#121]
### Bug Description

I have used the commanded style-setting plugin to change the Mono font into "DejaVu Sans Mono", so that the math codes in `$...$` and `$$...$$` are shown in that font. The problem is the LaTeX like commands such as `\int` are shown in italic text font(in my case is Stix2)

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/32637321/155250219-f427d95a-d448-4821-91de-fb2f0e7fd78e.png)

### To Reproduce

1. input $a^\dagger$
2. `\dagger` is shown in the italic text font, while `a` is shown in the correct mono font as expected

### Obsidian Version

0.13.23

### Installer Version

0.12.5

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [ ] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [ ] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Do you have "DejaVu Sans Mono" installed on your system?

Also, could you share the code for the latex code from above, so I can test it?

**Comment by chrisgrieser** [comment]
nevermind, I figured it out, fixed in latest update
