### ISSUE TITLE
[Bug]: Links in headings are lower

### ISSUE THREAD

**Issue by lyonsquark** [chrisgrieser/shimmering-focus#122]
### Bug Description

Links in headings have a lower baseline (links in body text are fine) in live-preview.  This seemed to happen after an update to the theme, but I'm not sure which update actually did it. 

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/97726/155397009-fb53e026-84f1-4a79-a12e-0ee039533873.png)

### To Reproduce

Make a heading with ## (any level will do it) and make a link with [[ ... ]] 

### Obsidian Version

0.13.26

### Installer Version

0.13.24

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
fixed with the latest update
