### ISSUE TITLE
Contribution: Analog to the colored bold font style, this colors italic text

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#123]
### Type of Contribution

Color Scheme(s)

### Description

I really like the added visibility that your theme gives bold text, and I changed the color, to make it pop even more (I just saw that this might actually not be part of the theme anymore, I think, but I still use it :) )
And now I added a snippet that adds color to italicized text:

```
:root
{
    --italic-in-lightmode: #0BAD00;
    --italic-in-darkmode: #0DD000;


}


.theme-light .cm-em,
.theme-light .markdown-preview-view em {
	color: var(--italic-in-lightmode);
}

.vertical-tab-nav-item:last-child {
	color: var(--italic-in-lightmode);
}

.theme-dark .cm-em,
.theme-dark .markdown-preview-view em {
	color: var(--italic-in-darkmode);
}

.vertical-tab-nav-item:last-child {
	color: var(--italic-in-darkmode);
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/71895400/155549399-5c17e9ba-639f-4ca9-9c4a-ced6f631ae9c.png)

![image](https://user-images.githubusercontent.com/71895400/155549460-898ba9c3-9398-4a16-ab30-0034a4ba5f21.png)

**Comment by chrisgrieser** [comment]
something very similar will be part of the bigger color style upgrade I am planing. 🙂 

What's the reason for `.vertical-tab-nav-item:last-child` ❓

**Comment by ReaderGuy42** [comment]
I don't know. A) this is over a month ago, and b) I (still) don't know anything about coding, so this is just copied/borrowed from somewhere and pretty much just brute-forced, trial and error, till some combination of lines worked what I was trying to do haha
so, I'm not sure, sorry!

**Comment by chrisgrieser** [comment]
haha, no worries! gonna add a bunch more color options to the theme once I have more time.

**Comment by ReaderGuy42** [comment]
Awesome, I look forward to that, thanks!!
