### ISSUE TITLE
[Bug]: Bullet Point in LP is small

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#124]
### Bug Description

I don't know if this is a bug or intentional. The bullet points in LP are smaller than in the reading mode. I am using the Outliner plugin.

### Relevant Screenshot

Here is the screenshot of LP

![image](https://user-images.githubusercontent.com/88898230/155822981-dd4b6bed-aa45-4633-a316-b463e2abd401.png)

Here is the screenshot of the reading mode

![image](https://user-images.githubusercontent.com/88898230/155823011-208c3f66-bbc6-402e-b69a-2ca07713643a.png)

### To Reproduce

1. Make bullet points

### Obsidian Version

0.13.24

### Installer Version

0.13.23

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
is actually also an issue with the default theme. However, it's also easily fixed. Done in latest release.

**Comment by Liong1976** [comment]
Ok, thanks, Chris!
