### ISSUE TITLE
Feature Request: When the Longform is left-aligned, the Footnotes in Reading view also left-aligned

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#126]
### Feature Requested

It would be great if when the Longform is left-aligned, the footnotes in the Reading view are also left-aligned instead of justified so that the footnotes are not stretched out and more aesthetically better.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/88898230/158798857-cf76729f-f307-4efc-a4f3-faadad1d9ec8.png)

![image](https://user-images.githubusercontent.com/88898230/158799920-81f6911d-2ad0-40ea-b7db-232588dd6ad3.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
done :)

**Comment by Liong1976** [comment]
Thanks a lot, Chris! I do appreciate it
