### ISSUE TITLE
[Bug]: In the Longform Plugin, in the numbered listing of scenes in a Draft folder, scenes including the word "Appendix" become un-numbered

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#127]
### Bug Description

I initially asked this over at the Longform repo (https://github.com/kevboh/longform/issues/56) thinking it's the plugin, because I didn't know your theme adds those numbers in the scene list. 

It turns out that scene titles including the word "Appendix" don't get a number, I assume (?) this has to do with stuff similar to the Index file?

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/159231395-313b5831-4cb1-4b22-ba99-85f85b01d3b0.png)

### To Reproduce

1. Using Shimmering Focus as theme, go to Longform plugin sidebar, scene list
2. have a scene include the term "Appendix" or change a title to include that word (it changes it "live"/in real-time)
3. scene is/becomes unnumbered

### Obsidian Version

0.13.33

### Installer Version

0.13.30

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
that's actually done on purpose, for scenes title "appendix" or "metadata", since I do not think that they should be numbered :P

You can use this css snippet to number all scenes:

```css
#scene-list .scene-container::BEFORE {
	content: counter(sidebar) ".";
	padding-right: 5px;
	counter-increment: sidebar;
}
```
