### ISSUE TITLE
Feature Request: Support Hover Editor Snap to Side

### ISSUE THREAD

**Issue by rushikb** [chrisgrieser/shimmering-focus#128]
### Feature Requested

Hover editor update 5.0 now allows users to snap popovers to the left/right/top edges— I was unable to use this for shimmering Focus even after enabling Title bar, ribbons and header bar. 
Example of feature for SF vs Sanctum,
 

### Relevant Screenshot

![CleanShot 2022-03-21 at 22 39 02](https://user-images.githubusercontent.com/6484525/159285054-8b10c204-1117-48f5-9204-c80f02bcf8a1.gif)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
how exactly does this snap feature work? I can't find it in the plugin readme, and also it does not work for me in the Default theme?

**Comment by chrisgrieser** [comment]
nevermind, figured it out, should work with the latest release. 🙂
