### ISSUE TITLE
Feature Request: Image enhancement (zoom) option

### ISSUE THREAD

**Issue by tom-00** [chrisgrieser/shimmering-focus#13]
It would be really nice if I am to able to see any image in the preview mode (bigger) with the zooming option.  While hovering the mouse icon over an image gives us the option to zoom that image, whether clicking or automatically.

**Comment by chrisgrieser** [comment]
implemented in [release 1.23](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.23), update via Github oder the Community Theme browser :)
