### ISSUE TITLE
[Bug]: Preferences menu misaligned

### ISSUE THREAD

**Issue by osted** [chrisgrieser/shimmering-focus#130]
### Bug Description

In preferences window top half of the vertical menu is aligned to the right and the bottom half is left aligned (as it should be).

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/45074458/160473832-5b1adcb0-6a1e-4f93-8d28-76f794b10c4a.png)

### To Reproduce

1. Chose Shimmering Focus theme
2. Open preferences window

### Obsidian Version

0.14.2

### Installer Version

0.11.5

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
that one actually is a feature not a bug 😅 

The different alignments were done to differentiate Obsidian settings from plugin settings. But I can see that it comes of as wrong for some people. I have therefore changed it so all items are left-aligned. 👍
