### ISSUE TITLE
[Bug]: Can't change the hover window size.

### ISSUE THREAD

**Issue by YIRU69** [chrisgrieser/shimmering-focus#131]
### Bug Description

Hi, I have a problem when I use shimmering-focus.
When I use the hover editor, open a hover window, I want to resize the window but it don't work. WHY?HELP

### Relevant Screenshot

![1](https://user-images.githubusercontent.com/48148292/161381868-a334c7d9-0a8b-497b-abc3-cdea2218fa06.gif)

### To Reproduce

When I use the hover editor, open a hover window, I want to resize the window but it don't work. WHY?HELP

### Obsidian Version

0.14.2

### Installer Version

..

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
There is a theme setting to change popover sizes, which probably overrides the hover editor resizing. Will look into how to fix that, but until then, you can change the size of popovers with the respective style setting

![image](https://user-images.githubusercontent.com/73286100/161386843-4a3490c0-6aac-453b-9d2b-79bc691d2ca1.png)

**Comment by chrisgrieser** [comment]
ok, nevermind the first post, it's fixed with the latest update
