### ISSUE TITLE
[Bug]: Slow when scrolling in settings

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#132]
### Bug Description

Compared to default theme or other themes, scrolling in settings is a little slow. I tried using a clean vault with only shimmering focus and the problem still occurs.

### Relevant Screenshot

https://user-images.githubusercontent.com/38974541/161565142-039d068c-7424-42b0-bb45-3fdd9bcf01d9.mp4

### To Reproduce

1. Open settings
2. Scroll through long list (community plugins, hotkeys...)

### Obsidian Version

0.14.2

### Installer Version

0.14.2

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
That's weird. Does it affect all settings tabs or only surviving ones?

**Comment by imeed166** [comment]
Ah yeah, only settings that a have a long lists like community plugin and hotkeys.
Check just now, and I was low on battery when this happened, so the scrolling is not slow anymore when plugged in. Guess this was a problem on my end.

**Comment by imeed166** [comment]
Okay, will do.

**Comment by imeed166** [comment]
It reappeared, even though I'm plugged in. I don't know what's causing this.

https://user-images.githubusercontent.com/38974541/161615946-91abb4e2-47dd-41ec-9ae4-0cce634d2684.mov

**Comment by imeed166** [comment]
I have the same problem with sanctum, but there is non problem with ITS, minimal, default, primary, blue topaz..

**Comment by imeed166** [comment]
And it affect all sectings tabs.

**Comment by chrisgrieser** [comment]
huh that's weird. When did it start to appear? Cause I haven't really touched the settings' css in the last couple of updates. 😕

**Comment by imeed166** [comment]
It was always there when I used the theme. But at first I thought it was because of me, it was until I was trying other themes, that I noticed the difference.

**Comment by chrisgrieser** [comment]
Ok, in the latest update I added toggles to turn of animations & shadows (under Misc). Can you try those and see whether it improves things?
![Screenshot 2022-04-05 22 08 18](https://user-images.githubusercontent.com/73286100/161840709-43e642c9-9290-481d-9a3f-5f2d43b0face.png)

[Also, according to mgmeyers](https://discord.com/channels/686053708261228577/840286264964022302/960973322668109844), it looks like you have window translucency on, can you try turning that off?

**Comment by imeed166** [comment]
I had window translucency off, animations were turned off too. I turned off shadows and 3D-effets from the new updates, but scrolling is still slow.

**Comment by chrisgrieser** [comment]
Hmmm, I don't really know what could cause this. It's also hard for me to debug, since I cannot reproduce it really.

You could try out and see whether you can find some sort of condition which causes the slow down, which might give a clue. Otherwise, it might be that you will have to [take a performance snapshot](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+debug+why+Obsidian+is+running+slowly#Taking+a+performance+snapshot) to figure out what causes the slowdown. 😕

**Comment by chrisgrieser** [comment]
okay, I had an idea. Could you try updating to the latest version and have a look?

**Comment by imeed166** [comment]
It's a bit better, but still slow

**Comment by chrisgrieser** [comment]
hmm, could you try setting the shapes to "angular"? I actually read that many rounded corners can have performance impact as well 😵‍💫

**Comment by chrisgrieser** [comment]
also, is it just settings tabs, or are other things like longer notes also affected? if so, could you try to look for some pattern, like notes with which type of content are affected and which aren't?

**Comment by imeed166** [comment]
> hmm, could you try setting the shapes to "angular"? I actually read that many rounded corners can have performance impact as well 😵‍💫

same problem



> also, is it just settings tabs, or are other things like longer notes also affected? if so, could you try to look for some pattern, like notes with which type of content are affected and which aren't?

That's the thing, scrolling is smooth in all notes. It happens only in settings tabs. 
Here's an example: when using style settings in obsidian settings it's slow, but when I use with the command `show style setting view` to open in a new pane, it's smooth.

**Comment by chrisgrieser** [comment]
> That's the thing, scrolling is smooth in all notes. It happens only in settings tabs.
Here's an example: when using style settings in obsidian settings it's slow, but when I use it with the command show style setting view to open in a new pane, it's smooth.

Ok, that is actually some valuable information, because this means that it's an issue related to something that only occurs in the settings menu. 🤔 
no need for a recording, I get it. Could you make see which settings tabs are performing so slowly and which perform better? That could help narrow down the issue

**Comment by imeed166** [comment]
Nothing specific, all settings perform the same, it's just that when I start scrolling fast in a tab that contains a lot (community plugins, hotkey, style settings unfolded, global hotkey plugin settings...), it becomes slow at rendering the content

**Comment by chrisgrieser** [comment]
Hmm. Could you try changing the size of menues/modals (under misc)? Like die reducing the size of the menu help with performance?

**Comment by imeed166** [comment]
No, it doesn't help.

**Comment by chrisgrieser** [comment]
Do you have this setting enabled/disabled? Could you try toggling it, restart Obsidian, and look whether it affects the issue?
<img width="1081" alt="Screenshot 2022-04-08 10 09 25" src="https://user-images.githubusercontent.com/73286100/162393593-d0fce9c8-c2f2-4554-851a-06651c636324.png">

**Comment by imeed166** [comment]
I have it enabled. When I disable it, it's slower than before.

**Comment by chrisgrieser** [comment]
hah, I think I found it. Using the slowest of all settings pages (the theme browser), I could actually reproduce the issue. It's actually one simple line of completely unrelated code 🙈 

Could you update to the latest theme version and look how the performance is now?

---

reference for myself: it's `backdrop-filter: blur(3px)` that for whatever reason slowed everything down.

**Comment by imeed166** [comment]
Ah, FINALLY. Thank you. It's smooth now.
You should tell the author of sanctum theme to update their theme as well.

**Comment by chrisgrieser** [comment]
great 🥳 

Thanks for the patience! Figuring this one out has been a harder one.
