### ISSUE TITLE
[Bug]: all text is black in dark mode

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#133]
### Bug Description

All text is black in dark mode in the latest release.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/38974541/162480875-28f27cd9-e0d9-40e4-86cd-7f5aaa1279bc.png)

### To Reproduce

1. update to latest version
2. turn on dark mode

### Obsidian Version

0.14.2

### Installer Version

0.14.2

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
oops. Thanks, is fixed.
