### ISSUE TITLE
Feature Request: Show Vault Name im File Browser

### ISSUE THREAD

**Issue by MSzturc** [chrisgrieser/shimmering-focus#134]
### Feature Requested

Currently it's not possible to reenable to show the vault name as root node in file browser. I use it to move notes from inbox to my root folder. 

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
good point, haven't thought of that. Added style setting to show the vault in the file explorer again. 🙂
