### ISSUE TITLE
[Bug]: Rendering issues

### ISSUE THREAD

**Issue by MSzturc** [chrisgrieser/shimmering-focus#135]
### Bug Description

With the current version of shimmering focus i have rendering issues on my mac ( see image )

I've used a clean vault without plugins & with standard settings.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/4275753/162536681-368ee639-2d18-49d9-b102-563bd35c273c.png)

(spacing top left to small)

### To Reproduce

I've used a clean vault without plugins & with standard settings.

### Obsidian Version

0.14.2

### Installer Version

0.14.2

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
I am also using a Mac and have no issues there. I assume it has to do with screen resolution maybe?

Could you tell me your screen resolution? And also your font size setting (Settings ➞ Appearance ➞ Font Size)?

**Comment by MSzturc** [comment]
I have a m1 macbook air with standard display settings ( 2560-by-1600 ). My font size is standard too ( 16 )

**Comment by chrisgrieser** [comment]
weird. I have the same resolution and font size and it looks correct here 💀 
Any unusual font you are using? lots of zoom-in or zoom-out? 🤔 

---

Also, could you use the following css snippet and adjust the value until it looks fine on your end? Probably easier than me blindly tweaking the value without knowing how it looks on your end.

```css
body {
	--mac-traffic-light-padding: 1rem; // add/substract values in ~0.05 steps
}
```

**Comment by MSzturc** [comment]
With 1.25rem it looks right

![image](https://user-images.githubusercontent.com/4275753/162542286-d426aaf8-5906-4119-a0f1-3e93d093bb7e.png)

1.5rem has the same height as the title bar of the note

**Comment by chrisgrieser** [comment]
nah, wasting a few pixels on my display, but fine, is fixed 😝
