### ISSUE TITLE
Feature Request: Hide File View Button Bar

### ISSUE THREAD

**Issue by MSzturc** [chrisgrieser/shimmering-focus#136]
### Feature Requested

Is it possible to add an option to hide file viewer bar? For me it is more logical to have them in the ribbon bar. Therefore i've added the new note & new folder button to ribbon to have only one button bar. 

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/4275753/162542756-fc6625aa-eb73-4044-817b-196a60fa350a.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
implemented in latest release 👍
