### ISSUE TITLE
[Bug]: Newest changes break stuff

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#138]
### Bug Description

With the newest changes from today the Style Settings and generally the theme break. See screenshot

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/162733344-3bfc6d39-4ecd-4fd7-acfd-464e863324f2.png)

### To Reproduce

1. Update Theme
2. everything changes because Style Settings no longer works with the theme

### Obsidian Version

0.14.2

### Installer Version

0.13.30

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by ReaderGuy42** [comment]
Deleting the apostrophe the error message in the screen shot mentions solves the problem :)

**Comment by chrisgrieser** [comment]
I was already pushing the update as you reported this. You are just too quickly updating with updating the theme 😆

**Comment by ReaderGuy42** [comment]
Haha sorry! I have a "Visual Ping" set to tell me if you add something to the changelog, and those come every 12 hours, and sometimes it just times it right after you push new stuff.

**Comment by chrisgrieser** [comment]
haha lol 😆 

what app do you use do that?
