### ISSUE TITLE
Index pages missing

### ISSUE THREAD

**Issue by sascha-andres** [chrisgrieser/shimmering-focus#14]
When I use this theme (great work btw) all my index pages are missing. This is very unfortunate and has me forced to use another theme.

Is there a way to unhide Index pages?

Best regards
Sascha

**Comment by chrisgrieser** [comment]
Thanks!

And my bad about the hidden Index files. I wanted to implement that as I setting, but accidentally hidden them by default. 😣

[Fixed it just now](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.7.1). Download from Github or update via the Community browser and your Index files will re-appear. :)
