### ISSUE TITLE
[Discussion]: Which Default Settings make sense?

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/shimmering-focus#141]
The theme has been adding quite a bit of style settings, and for many of them, I am not sure which should be the default setting. So I am inviting you to make suggestions what opt-in settings should be the default.

(Only thing not up for debate are the toggles in `Show/Hide UI elements` – this theme's main selling point is a minimalistic user interface, after all. 😉 )

**Comment by ReaderGuy42** [comment]
I actually think the default settings are pretty good. I prefer the round  shapes over the square-ish ones but that's not really vital. Thanks for putting so much work into this theme!

**Comment by pryley** [comment]
Hiding the shadows makes the theme feel more minimal.

**Comment by chrisgrieser** [comment]
> Hiding the shadows makes the theme feel more minimal.

That's actually somewhat of a misunderstanding a lot of people have: Shimmering Focus isn't about a minimal aesthetic, but about a minimalist user interface. 

See here for summer elaboration on that: https://chrisgrieser.github.io/shimmering-focus/design-philosophy/

**Comment by chrisgrieser** [comment]
closing this, since I think it makes more sense to use discussions for this. [Continued here](https://github.com/chrisgrieser/shimmering-focus/discussions/148).
