### ISSUE TITLE
Feature Request [No rush!]: Snippets for coloring italics and bold (differently) no longer work

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#142]
### Feature Requested

As mentioned previously, I have snippets for coloring, e.g. one for italic and one for bold. Here's the one for italics:
```
/* light mode */

.theme-light .cm-em,
.theme-light .markdown-preview-view em {
	color: var(--italic-in-lightmode);
}

.theme-light .cm-quote.cm-em,
.theme-light .cm-quote.cm-quote-1.cm-em,
.theme-light .markdown-preview-view em {
	color: var(--italic-in-lightmode);
}

.vertical-tab-nav-item:last-child {
	color: var(--italic-in-lightmode);
}

/* dark mode */

.theme-dark .cm-em,
.theme-dark .markdown-preview-view em {
	color: var(--italic-in-darkmode);
}

.theme-dark .cm-quote.cm-em,
.theme-dark .cm-quote.cm-quote-1.cm-em,
.theme-dark .markdown-preview-view em {
	color: var(--italic-in-darkmode);
}

.vertical-tab-nav-item:last-child {
	color: var(--italic-in-darkmode);
}
```
However, this no longer seems to work. I assume your new Style Settings defining colors for just those things are superseding them. Would it be possible to either have a toggle that turns this setting off so I can use my snippet again, or make it possible to give italics and bold different colors (that's the main point), so it's easier to quickly tell the difference just by color?

Since the default for the Style Settings is to have Bold & Italic as "uncolored" I assume that this also supersedes the snippet and "uncolors" these instead of using the snippet.

Thanks!!

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Already working on it as part of the big color overhaul. You should try the theme beta (unlockable under Misc), then select "custom colors", then you can customize the bold + italics color (right now there aren't many options yet though)

**Comment by ReaderGuy42** [comment]
Great, thanks, I'll have a look :)

**Comment by chrisgrieser** [comment]
totally forgot: by now, you can change the colors for bold/italic simply by using this this snippet:
```css
.theme-light {
	--bold-text-color: red;
	--italic-text-color: blue;
}
.theme-dark {
	--bold-text-color: red;
	--italic-text-color: blue;
}
```

**Comment by ReaderGuy42** [comment]
Awesome, thanks! The bold works perfectly, but the italics does not. It needs the S in there, i.e. "--italics-text-color"

**Comment by chrisgrieser** [comment]
ah thx, typo on my end. edited it above, in case anyone else finds this issue 🙂
