### ISSUE TITLE
[Bug]: Cursor option doesn't work

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#143]
### Bug Description

Whatever I choose for the cursor option (in the Style Settings), the Obsidian shows Dark Eclipse

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/88898230/163996747-0e0c8aee-c565-4d0f-9ed8-f22f53e25c62.png)

![image](https://user-images.githubusercontent.com/88898230/163998928-5c350e4a-c99e-47d2-be0a-b204fdd58576.png)
The Dark Eclipse cursor is in the second line, second word, "qui"

### To Reproduce

1. Open "Style Settings"
2. Choose "Cursor" > "Shimmering Beam"

### Obsidian Version

0.14.6

### Installer Version

0.14.6

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
ah thanks, fixed with latest update.

**Comment by Liong1976** [comment]
Thanks, Chris!
