### ISSUE TITLE
[Bug]: Selecting the Beta Color Scheme "Custom Colors" makes everything go see-through (kind of)

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#144]
### Bug Description

Not sure if you'd like feedback on this, but when you choose "Custom Colors" from the Beta Color Schemes, everything goes see-through making it quite hard to navigate (not impossible though).
See the screenshot for what I mean. I should add that I wasn't, at that time, using dark mode, so that's another issue, I guess.

Thanks :)

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/164257396-320cdc27-d183-432c-ad8f-5757fe2dfe55.png)

### To Reproduce

1. Style Settings
2. Color & Aesthetics
3. Beta Color Schemes
4. Custom Colors
5. See-through

### Obsidian Version

0.14.6

### Installer Version

0.14.6

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
of course' I'd like feedback on this! Especially when I am still developing things (the beta features); feedback is most useful.

yeah, that's a bug from all the major color variable restructuring I've been doing. Fixed with latest release

**Comment by ReaderGuy42** [comment]
Great, thanks!!
