### ISSUE TITLE
[Bug]: Custom Colors cause more fun glitches :) (and internal links are sometimes really pale)

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#145]
### Bug Description

When I have Custom Colors active under Color Schemes and try switching to Dark mode (or the other way, I assume) I get some funky glitches :)

I found this because I was trying to figure out why sometimes, not always, internal links are so pale they're barely legible. (This also applies when I have the default color scheme active)

See screengrab and screenshot for more.

### Relevant Screenshot

https://user-images.githubusercontent.com/71895400/164440681-43d69d50-41d0-4206-839e-4cad604677e9.mp4

![image](https://user-images.githubusercontent.com/71895400/164440975-ddac0465-93df-4a33-91db-4714e1d7e490.png)

### To Reproduce

1. color schemes default or custom
2. change between dark and light mode
3. screen goes disco
4. (and links are pale)

### Obsidian Version

0.14.6

### Installer Version

0.14.6

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by ReaderGuy42** [comment]
I just figured out that the pale links are for notes that have NOT been created yet. Is this intentional then?

**Comment by chrisgrieser** [comment]
ummm, I can't figure out what's causing that glitching, it doesn't occur on my end. How exactly are you switching between dark and light mode?

**Comment by chrisgrieser** [comment]
also, it seems there are some more issues that do not occur on my end, like the style settings on your end looks kinda of. For me, it looks like this:

Could you check whether via safe mode and disabling css snippets, if you have something interfering there?

<img width="1013" alt="Pasted image  2022-04-21 13 32 26" src="https://user-images.githubusercontent.com/73286100/164449644-1f53262d-2851-4367-a917-0ca91398282b.png">

**Comment by chrisgrieser** [comment]
but regarding the unresolved links: yeah, they are indeed supposed to look like this and have a different color tone from normal links. 

But on your display it seems, they are indeed a bit harder to read, so I cranked up the contrast for them in the latest update. 👍

**Comment by ReaderGuy42** [comment]
> ummm, I can't figure out what's causing that glitching, it doesn't occur on my end. How exactly are you switching between dark and light mode?

I have hotkeys set up, "Ctrl+ArrowDown" for dark  mode, ArrowUp for light mode, this lets me switch back and forth quickly.



> also, it seems there are some more issues that do not occur on my end, like the style settings on your end looks kinda of. For me, it looks like this:
> 
> Could you check whether via safe mode and disabling css snippets, if you have something interfering there?
> 


I have a thing in my colors snippet that changes the signature (❖ or whatever that symbol is) to a Greek word that I think is cool, that's all that is.

I just opened the Sandbox vault (I guess they got rid of/renamed the Help vault) and installed the theme and Style Settings, nothing else. I then switched to Custom Colors and the ghosting (if that's what that is called, the glitches) start before I even close the menu:

https://user-images.githubusercontent.com/71895400/164457095-06f84497-2e4a-43dd-b8ad-3214dbffd7cf.mp4

**Comment by chrisgrieser** [comment]
> I have a thing in my colors snippet that changes the signature (❖ or whatever that symbol is) to a Greek word that I think is cool, that's all that is.

ah I see, good. I think that it was some kind of bug, but if it's intentional, then it's fine

**Comment by ReaderGuy42** [comment]
OK, no worries, since it's easy to avoid it's not a big deal, thanks!

**Comment by chrisgrieser** [comment]
Could you try deleting the theme and the style setting plugin and then reinstalling both of them? 

A sunrise curried style settings configuration might be a potential cause if the glitches 🤔

**Comment by ReaderGuy42** [comment]
> sunrise curried style settings configuration
I'm not sure what this means?
I reinstalled both, but when I switch to Custom Colors the same thing happens again. But also since it happens in the Sandbox vault, I don't think it has to do with my settings, as I don't have any snippets or other plugins there.

**Comment by chrisgrieser** [comment]
> sunrise curried style settings configuration

oh sorry, that's autocorrect for you.

Yeah, then I am quite unsure what causes it, sorry :(

**Comment by ReaderGuy42** [comment]
No worries :)

**Comment by ReaderGuy42** [comment]
Stupid question, but are you on 0.14.6? with the new installer? Because I only noticed this once I'd downloaded and installed the newest installer/version. If that's not it, maybe it's a Linux thing, or a me thing, as in something that's interacting with something else on my PC.

**Comment by ReaderGuy42** [comment]
FYI under Typography, under Fonts you have a Typo:
![image](https://user-images.githubusercontent.com/71895400/164718853-07f9b3fe-9051-4705-95af-e3712467d780.png)

**Comment by chrisgrieser** [comment]
thx, typo is fixed.

**Comment by ReaderGuy42** [comment]
Cool :)

**Comment by ReaderGuy42** [comment]
Another quick question (sorry): Which setting governs this text bit:
![question](https://user-images.githubusercontent.com/71895400/164720445-f7f23fb2-3bf7-4b30-bd45-095a706febe6.png)

This is when you open two square brackets "[[" to choose a note to link with. This specific font appears when I have your theme active, but is like that regardless of whether Style Settings is enabled or not.

**Comment by chrisgrieser** [comment]
oh yeah, you are right, that font doesn't look too good there. I changed it to the interface font.

If you want to customize it with a snippet, you can use this: 

```css
body .suggestion-container .suggestion-note {
	font-family: "Arial";
}
```

---

also, to keep things tidy, I activated the discussion tab, where things like questions can be asked. This keeps the issue section limited to issues in the more narrow sense (which helps me keep an overview of things 🙂 )
![image](https://user-images.githubusercontent.com/73286100/164724472-f0a874eb-f4a6-4c2b-8178-cef3a3c99344.png)

**Comment by ReaderGuy42** [comment]
Perfect!

**Comment by chrisgrieser** [comment]
btw, I fixed a bug which might have caused the glitches 🙂

**Comment by ReaderGuy42** [comment]
Yes, I think it's gone now! Thanks :)
