### ISSUE TITLE
[Bug]: misaligned checkbox in callout

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#150]
### Bug Description

The checkboxes are misaligned if created in a callout, and it's the same for dataview task list.

### Relevant Screenshot

https://user-images.githubusercontent.com/38974541/165051038-7c50d82f-ddc4-4b49-b1b3-a322d6c50402.mov

### To Reproduce

1. create callout
2. add checkboxes or dataview task view
3. switch to reading view

### Obsidian Version

0.14.6

### Installer Version

0.14.5

### Font Size

14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
thanks, fixed
