### ISSUE TITLE
[Bug]: The colour of selected, highlighted text is unreadable in dark mode

### ISSUE THREAD

**Issue by SkepticMystic** [chrisgrieser/shimmering-focus#151]
### Bug Description

If you highlight some `==text==`, then select it in the editor, the background colour has bad contrast and makes the text unreadable.
The same is **not** true in light mode, where the colouring is just fine.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/70717676/165708096-b8c88b21-29f1-4258-b7ee-ec2f0a66147e.png)

### To Reproduce

1. Type out some text
2. Highlight it with `==`
3. Select a range of that highlighted text

### Obsidian Version

0.14.7

### Installer Version

0.12.5

### Font Size

19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
since when are you a SF user? 👀 👀 👀

**Comment by SkepticMystic** [comment]
I like to switch it up sometimes 😋 
Thanks for resolving this so quickly!

**Comment by chrisgrieser** [comment]
no big deal, the fix was only changing one line and deleting another one :P
