### ISSUE TITLE
[Bug]: Tags rendered twice in dataview tasks list

### ISSUE THREAD

**Issue by lguenth** [chrisgrieser/shimmering-focus#153]
### Bug Description

Hello hello, I've come across a visual bug. :eyes: 

When appending tags to task items and then querying them with dataview, the tags somehow appear twice and overlap with other text (see below). I've confirmed that it doesn't happen in the default theme or any of the other themes I sometimes use.

At first I thought it only happens inside callouts, but as you can see, it also happens inside normal dataview query blocks.

Task format:
`- [ ] Open Atlas lokal einrichten? #projekt/inova`

Query:
`TASK WHERE !completed`

~~Related: I wanted to update the theme before reporting... but it seems your last update broke the theme completely: #154~~ Resolved.

### Relevant Screenshot

![grafik](https://user-images.githubusercontent.com/69049131/166144253-46347c07-96a5-44a8-ad14-5a8cadc74c18.png)

### To Reproduce

1. Enable Shimmering Focus
2. Create a todo (i.e. bullet with checkbox) item which includes a tag
3. Query for tasks with dataview
4. Tada, a bug 🐞

### Obsidian Version

0.14.7

### Installer Version

0.14.2

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
it's an issue caused by the "tags-in-gutter" option paired with a gutter that is too narrow. You need a wider window, or zoom out, or turn off tags-in-gutter. 

On the css side, there is unfortunately little I can do, I think :(

https://user-images.githubusercontent.com/73286100/166146105-6d6b25fe-0c79-47c1-ad20-17dcfbba8a77.mov

**Comment by lguenth** [comment]
Ohhh, I see. Thanks for the quick reply, I didn't remember that feature. I just have to tweak my setup some more. :)
