### ISSUE TITLE
[Bug]: Updating to latest version breaks theme, reverts to Default?

### ISSUE THREAD

**Issue by lguenth** [chrisgrieser/shimmering-focus#154]
### Bug Description

Hey, I was just about to open issue for something minor (#153) but then I ran into something more pressing. :grimacing: 

When I tried to update the theme to confirm the bug is still there, suddenly the complete theme broke and everything reverted back to the look of the default theme.

I disabled all snippets and plugins, tried to reinstall the theme, I even tried it on my Android devices... No change. Help?

### Relevant Screenshot

![grafik](https://user-images.githubusercontent.com/69049131/166145281-59fb94b7-bd9c-4641-9d6a-5664f0b744b3.png)

### To Reproduce

1. Enable Shimmering Focus
2. Update to latest version through the theme "store"

### Obsidian Version

0.14.7

### Installer Version

0.14.2

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [X] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by lguenth** [comment]
I'm so sorry, suddenly it works again, I just hit Update for the fifth time and it worked. Gaaah. :upside_down_face:

**Comment by chrisgrieser** [comment]
yeah, I just fixed it since `@atlas` [already gave me a heads up on Discord](https://discord.com/channels/686053708261228577/702656734631821413/970295865849815151) 🙈 

Thanks though!

**Comment by lguenth** [comment]
Okay, cool, so I didn't imagine it or break it myself. Good to know. :sweat_smile:
