### ISSUE TITLE
[Bug]: command palette  display overlapped

### ISSUE THREAD

**Issue by HideOnLie** [chrisgrieser/shimmering-focus#155]
### Bug Description

As shown below.
I'm not sure what caused it. 

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/51672711/166153351-3430adf8-6785-423c-8b99-3667d4f279cc.png)

### To Reproduce

1. set long command to hotkeys
2. <ctrl + P> , show the command palette 

### Obsidian Version

0.14.6

### Installer Version

0.12.19

### Font Size

14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
fixed with latest release!
