### ISSUE TITLE
[Bug]: checkbox not appearing right

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#159]
### Bug Description

The checkboxes look flat

### Relevant Screenshot

https://user-images.githubusercontent.com/38974541/166475253-2ed22830-aa32-4331-810f-14c944950df4.mov

### To Reproduce

1. create checkbox

### Obsidian Version

0.14.6

### Installer Version

0.14.5

### Font Size

14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
the issue does not occur for me, even when I install the theme in the help vault.

Could you check whether maybe another snippet/plugin is interferring here?

**Comment by imeed166** [comment]
You're right, it was the [database](https://github.com/tomaszkiewicz/obsidian-database-plugin) plugin, (sorry).

**Comment by chrisgrieser** [comment]
no problem! might wanna open a bug report at that plugin then, a plugin's css shouldn't affect things that have nothing to do with the plugin
