### ISSUE TITLE
Feature Request: Fold indicator options

### ISSUE THREAD

**Issue by b1uegh0st** [chrisgrieser/shimmering-focus#160]
### Feature Requested

Thanks for the continuous work on this great theme.

I dug around in the style settings options and search but cannot find a way to turn off the (end of line) fold indicator. 

It is rather distracting to me (used to be a "...", also I personally don't need it to be click-able. So please add an option to turn it off (or turn it back to "...")

A side request (on this topic) would be that the Collapse Arrow can have an option to only show when hover or in active line, even when folded. This is less important as I already have that in CSS.

Both of these request, I guess, are in the spirit of making the look very minimal while writing.

Thank you.

### Relevant Screenshot

I want to turn this off.
![Uploading image.png…]()

Cannot find it 
![Uploading image.png…]()

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
ah, how could I miss those 🤣 

Hidden by default and setting to re-enable in latest release
