### ISSUE TITLE
[Bug]: The cursor changed into thin after Obsidian updated into 0.14.9

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#161]
### Bug Description

The cursor changed into thin after I had updated into Obsidian 0.14.9

### Relevant Screenshot

Not available

### To Reproduce

1. Update into Obsidian 0.14.9
2. Cursor changed into the default one (a very thin one) regardless what I chose in the Style Settings

### Obsidian Version

0.14.9

### Installer Version

0.14.6

### Font Size

15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Unfortunately, this is due to a change with the new Obsidian version. From Obsidian 0.14.8 on, it seems the only thing a theme can change is the color of the cursor. There is unfortunately nothing I can do about it.

[See explanation from the Obsidian devs here at Discord.](https://discord.com/channels/686053708261228577/931552763467411487/971091252013588550)

**Comment by Liong1976** [comment]
No worries, Chris. Thanks for the explanation!
