### ISSUE TITLE
[Bug]: Cannot open a new pane

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#162]
### Bug Description

A new pane is hidden

### Relevant Screenshot

This is in default theme:
![image](https://user-images.githubusercontent.com/88898230/166686441-c518cbaa-8bb3-448b-afbf-db029fd6f4f5.png)

This is in Shimmering Focus:
![image](https://user-images.githubusercontent.com/88898230/166686478-d54b5fcf-730c-4829-bb14-674f3147ac1e.png)

### To Reproduce

1. Open a new pane 
2. Only one pane shows

### Obsidian Version

0.14.9

### Installer Version

0.14.6

### Font Size

15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by ReaderGuy42** [comment]
I came here to mention something similar. I thought it was that the theme's most current update was interacting with the Sliding Panes (Andy's Mode) plugin because suddenly the panes take up my entire monitor, instead of just half.

But I think the issue is rather that with the update the pane can't be split anymore.

@Liong1976 in the meantime you could use the Sliding Panes plugin. You still can't see 2 panes at the same time, but maybe it's easier to swap back and forth :)
Thanks!

**Comment by Liong1976** [comment]
Thanks, @ReaderGuy42 for the advice

**Comment by chrisgrieser** [comment]
thanks, issue is fixed

**Comment by Liong1976** [comment]
Thanks, Chris!

**Comment by ReaderGuy42** [comment]
Thanks :)
