### ISSUE TITLE
[Bug]: Text cut off with Chinese in Settings UI

### ISSUE THREAD

**Issue by oldwinter** [chrisgrieser/shimmering-focus#166]
### Bug Description

hi ，my awesome author，I love your shimmering theme and shimmering alfred plugin so so so much.
there is some small format err both in mac and mobile with Chinese language. see as follows.
I'd appreciate it if you could fix it in your busy schedule.

### Relevant Screenshot

<img width="275" alt="image" src="https://user-images.githubusercontent.com/8112159/167906503-950f9f2b-94ea-41d7-a712-4df158b7dfb3.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/8112159/167906609-c6c98ec5-58ad-4a74-b265-c5cccccde022.png">

### To Reproduce

esay to see in screenshot

### Obsidian Version

0.14.6

### Installer Version

0.14.6

### Font Size

14

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [X] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
ah thanks, hiding the "version" in front of the version number indeed only works properly when Obsidian is used in English. Have reverted that, so now it should display properly.
