### ISSUE TITLE
Plugin Support: Notion-Like Tables

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#169]
### Issues with the plugin

the buttons are too big

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/38974541/169043357-5720d213-0314-4a01-bd79-2fb33b919c42.png)

### Link to the Plugin

https://obsidian.md/plugins?id=notion-like-tables

**Comment by imeed166** [comment]
closing this, as this is much better than it was before 

![image](https://user-images.githubusercontent.com/38974541/171605998-f30ea0ff-9829-47fc-9715-3a9b0765c063.png)

**Comment by chrisgrieser** [comment]
has this been solved on the plugin's end or what happened?

**Comment by imeed166** [comment]
I don't know, I thought it was you. In any case, it appears like that in the latest release.
