### ISSUE TITLE
[Bug]: *==Italic-highlight==* gets paler in Preview/PDF and turns the color e.g. red to brownish

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#173]
### Bug Description

In one of the newer updates, the theme now turns `*==italic-highlighted==*` words slightly paler in Preview mode and in PDFs which makes the red (that was once default and is now my default) sort of brownish.

This doesn't happen when I switch to the default theme, but the paling does also occur when I turn off that snippet.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/172836163-3572ab65-63b5-4b7f-baeb-5fd232b0cc3a.png)
Live Preview mode

![image](https://user-images.githubusercontent.com/71895400/172836223-5bd4ca07-ba73-450e-894f-e5143ec306dd.png)

Preview mode

### To Reproduce

1. word highlighting
2. switch to preview mode
3. word that is highlighted and italic gets paler

### Obsidian Version

0.14.15

### Installer Version

0.14.6

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
oh sorry, I didn't forgot to consider italics that are used for multi-color highlights. Is fixed.

**Comment by ReaderGuy42** [comment]
Awesome, thanks!
