### ISSUE TITLE
[Bug]: Longform / writing css class serif font not working

### ISSUE THREAD

**Issue by change-of-basis** [chrisgrieser/shimmering-focus#175]
### Bug Description

The SF theme is supposed to provide a serif font and independent styling designed for writing manuscripts, for Longform notes (i.e., “scenes”) as well as notes with the “writing” css class in the YAML. However, the serif font does not appear for my Longform notes. 

Also, I tried adding the “writing” css class to the YAML of a note, and that also had no effect.

### Things I have tried

I tried both of these (Longform note and regular note with writing css class) in a fresh vault (Obsidian help vault) with SF and Longform as the only installed theme/plugin (and no additional CSS snippets).

I also tried uninstalling the SF theme, quitting obsidian, deleting the style settings data file, and then restarting obsidian and installing SF again.

I have noticed that, in the SF Style Settings specifically for Longform/writing, changing the font size does affect the font size for Longform notes, but changing the font itself does nothing.

### Relevant Screenshot

https://user-images.githubusercontent.com/107888006/174674768-8a23a225-4cf1-4253-bce3-7fd3263d9331.mov

### To Reproduce

1. Create a Longform scene with SF enabled
2. Write the scene

### Obsidian Version

0.14.15

### Installer Version

0.11.3

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Your installer version seems quite outdated. Could you try updating the installer and have a look again?

(You can update the installer by downloading the `.dmg` from the Obsidian website again and installing it over your current Obsidian version. The most up to date installer version is 0.14.6 I think)

**Comment by change-of-basis** [comment]
Oh wow--this not only solved this issue, but every other issue I has as well. The whole app just looks better! Thanks so much, I had no idea that app installers need to be updated in addition to just updating the app. Sorry to bother you with this! I will go update my topic on the forum now.
