### ISSUE TITLE
[Bug]: Plugin Names outside Modal in Command Palette

### ISSUE THREAD

**Issue by lguenth** [chrisgrieser/shimmering-focus#178]
### Bug Description

Hello hello,
I seem to have found a bug in your styling for the core command palette that I can reproduce in the sandbox vault (but not with the default or any other theme). 

In the latest insider build (v0.15.3), the plugin names aren't clipped off at the borders of the modal but instead appear outside of it. This becomes even more apparent when community plugins are installed but it also happens with the built-in ones.
They don't scroll but seem to have the proper hover effects. :see_no_evil: (see video below)

I think this is caused by your workaround to have the plugin names appear after the command.

### Relevant Screenshot

From my vault:
https://user-images.githubusercontent.com/69049131/176415909-39253812-fced-44d6-ad51-70f301e5b84a.mp4

Reproduced in sandbox:
![220629_122658_screenshot](https://user-images.githubusercontent.com/69049131/176415996-eaf7f2dc-4198-443a-a151-a975341cc6c1.png)

### To Reproduce

Steps to reproduce:
1. Open Sandbox
2. Install Shimmering Focus theme
3. Enable any plugins
4. Open command palette and search something
5. Bonus: Try to scroll when plugin names are visible

### Obsidian Version

0.15.3

### Installer Version

0.14.15

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi, issue is known, but I cannot fix it without ruining how it looks for ppl on the public release (which is the majority). 

Will therefore be fixed upon the next public release. Until then, you can simply move the plugin name to the left again via style setting. 🙏

**Comment by lguenth** [comment]
Awesome, thank you! :heart: I just wasn't sure if you were aware of it. :) I guess I can close the issue and hope someone else who wants to report does a quick search first...

**Comment by chrisgrieser** [comment]
nah leave it open until the issue is actually fixed 🙂

**Comment by chrisgrieser** [comment]
now that new release is public, has been fixed.
