### ISSUE TITLE
#### is bigger than ###

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#18]
![image](https://user-images.githubusercontent.com/59067099/134892252-28f1b070-729e-49c1-b8a8-9c46c795d8ab.png)

**Comment by chrisgrieser** [comment]
I just tested it and in my installation, the h4 is smaller as h3. Do you maybe use some other plugins or CSS snippets that change the heading sizes?

<img width="418" alt="Screenshot 2021-09-27 14 05 13" src="https://user-images.githubusercontent.com/73286100/134911665-8fe8e2b9-8ab1-45a4-b8ad-e5896c555345.png"><img width="412" alt="Screenshot 2021-09-27 14 05 22" src="https://user-images.githubusercontent.com/73286100/134911659-b8bc504e-f55f-4e94-9390-d9a54d3e567b.png">

**Comment by DeutscheGabanna** [comment]
Hi, this is what i use - no other CSS
![image](https://user-images.githubusercontent.com/59067099/134923461-876d2391-d45b-487b-b1a9-fef0ddf28110.png)

**Comment by chrisgrieser** [comment]
well, I'd test disabling the plugins one by one, whichever causes the issue. if that does not help, try restarting Obsidian. Unfortunately I cannot help you beyond that, since I am also not a developer.

Nevertheless, as far as I can tell, this issue is not cause by theme, so I am closing this.
