### ISSUE TITLE
Feature Request: Allow finer control of line length in reading view regardless of max-view

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#180]
### Feature Requested

Currently, the line length in reading view available via style settings is capped at 1300 (cf Image1, 1440p monitor), with 700 (cf Image2) being the default. 
Then there is the max-view, which stretches text out across the entire width of the respective pane, but it is only active if the left sidebar is hidden. 
Now, for my personal workflow I cannot hide the left sidebar. It contains my dayplanner, my backlinks- and header-panes, all of which I constantly require when working. Moving them over to the right side is not really an option either for similar reasons - it's already filled with basically perma-required fields. 

Hence, I'd like to propose either:
- allow a margin-per-pane type of input, where you scale line-length not in an absolute manner, but instead give the left and right margins to the respective pane's edges in "% of total current pane-width". Meaning an input of `10-05` would result in 10% of the pane's width be used as left margin, 5% as right margin, at the remaining 85% are used as line length to expand text across.
- or, if solution A would not be sensible, change the field into an open edit field so users can input any integer they want, allowing for linelengths above 1300 (what is the unit here?) | this is probably simpler, but might result in more weird edge-cases if one removes any and all validations. 

Obviously option 1 would allow for a more specific granular control compared to option 2, although I'd assume implementation would be more complicated.

Sincerely,
~Gw

### Relevant Screenshot

Image 1: ![grafik](https://user-images.githubusercontent.com/80548781/177116673-7153e47a-8e0e-495a-9116-f01c6d910675.png)

Image 2: 
![grafik](https://user-images.githubusercontent.com/80548781/177117004-27451915-047e-4496-b5ec-746c2460e0ef.png)

### Relevance

- [x] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Actually, I think Option 1 has more potentially problematic edge cases (e.g. plugins affecting the gutter), so I simply implemented Option 2. You can now set a line length of up to 2500 px. 🙂

**Comment by Gewerd-Strauss** [comment]
Thank you :)
