### ISSUE TITLE
Arrows for showing all children of a tag is partially hidden behind scrollbar

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#19]
![image](https://user-images.githubusercontent.com/59067099/134892310-10f6d782-6a8e-49f5-b224-d564decad977.png)

**Comment by chrisgrieser** [comment]
good catch, i haven't noticed as I don't use nested tags that often. Fixed in [release 1.21](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.21).
