### ISSUE TITLE
Feature Request: Hide Status Bar item "Sidebar Focus en/disabled"

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#191]
### Feature Requested

With the new version going public (0.15.6) a new item in the status bar appeared, called "Sidebar Focus enabled" or "disabled".

Would it be possible to include this in the list of things that are hidable?

Thanks :)

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/179193402-8745ab2b-297d-4806-bd12-cb35e6e2f05a.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
It's actually not an Obsidian feature, but being added by the pane relief plugin. 

Anyway, added the option in the latest update. :)

**Comment by ReaderGuy42** [comment]
Thanks!
