### ISSUE TITLE
[Bug]: yaml colors issue introduced by recent change...

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#194]
### Bug Description

A recent update touched the yaml color rendering code. It seems to have introduced a new issue, as pictured below.

### Relevant Screenshot

<img width="526" alt="image" src="https://user-images.githubusercontent.com/42705243/180667272-0e765dca-8124-467c-b4ad-b956bb2e08bb.png">

### To Reproduce

Create yaml code as pictured.

### Obsidian Version

0.15.8

### Installer Version

0.15.8

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
ah, since I don't use `[]` in my yaml frontmatter, I didn't notice this issue. Thanks, fixed in the latest update.
