### ISSUE TITLE
Feature Request:  Clean-Embeds: Hide embedded chapter's name 

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#195]
### Feature Requested

Hello, 

I use the `clean-embeds`-css _quite_ a lot. Basically everywhere. 
It is amazing, and something I am baffled hasn't made it into base obsidian yet.
However, it has its flaws. 

I often have rather large documents when it comes to more complex topics, or when I track my own thoughts on a subject over the course of several months. In my workflow that results in a lot of specific chapters; and sometimes I want to embed some specific chapters elsewhere instead of copy-pasting it again. After all, that's the point of embeds.

My issue is that embedded chapters don't get shown in the outline of a note - which I often require.
The only solution I have found is to replicate the chapter name immediately before the embed. That however, results in the rather annoying visual seen in image 1. 

Currently, I don't really have a workaround to hotfix this issue.

If possible, I would suggest either of the following two solutions, although there might be better ones:
1. set up an additional css-class which will trim the first header encountered in an embed. This would make `cssclass: clean-embeds` work as it does currently, and the additional class could be leveraged if you wanted to show the chapter's title within the outline.
2. set up a globally active style setting manipulating the behaviour of `cssclass; clean-embeds` to do the same. While probably easier you would be restricted to either one of both options - and while I personally wouldn't mind I would assume there are users who would prefer the current behaviour over what I am requesting. After all, each method has its advantages and disadvantages.

---

The (at face value) best solution would be if obsidian would natively insert the chapter you embed (and its subchapters) into the note outline automatically, but even just thinking about it for a few seconds makes it complicated. Would header levels be adjusted to be children of the current level, or would they disrupt the chapters's flow and remain static?

As I believe it is unlikely to be implemented at all, or soon, I am instead turning here to see if a workaround via a css-class is possible. 
I also don't believe css-snippets to be the solution if you want granularity. To my knowledge, css-snippets are active globally, which means you'd have to manually de-/activate the snippet every time you want a  specific behaviour; which is rather cumbersome compared to f.e. simply changing the name of an embedded cssclass.

---

Thank you.

Sincerely,  
~Gw

### Relevant Screenshot

![grafik](https://user-images.githubusercontent.com/80548781/180840561-b6276c7a-e2c4-4ad1-a19a-a9f407a8d72e.png)
Image 1

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂

**Comment by chrisgrieser** [comment]
> set up a globally active style setting manipulating the behaviour of cssclass; clean-embeds to do the same. 

Has been added to the rewritten Shimmering Focus, and therefore will be available when the rewrite is done
