### ISSUE TITLE
[Bug]: The Theme is not Working

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#198]
### Bug Description

The theme is not working after the last update. It shows the Obsidian theme.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/88898230/185514366-10e723b7-e493-4b0c-b788-c49e44512d85.png)

![image](https://user-images.githubusercontent.com/88898230/185514373-ff54a308-f719-450f-ac43-2448c05c2b2f.png)

### To Reproduce

1. Update the theme

### Obsidian Version

0.15.9

### Installer Version

0.15.9

### Font Size

17

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
ah thanks, I had a bug in the build script which went unnoticed.

**Comment by Liong1976** [comment]
Thanks, Chris!
