### ISSUE TITLE
Bolding effect on links unnecessarily moves the text around on hover - consider deleting it

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#20]
Sometimes it flickers rapidly, if you move cursor just close enough to the link, or just annoys me if it moves whole parts of a document around. It doesn't offer anything for me and is just a nuisance.

**Comment by chrisgrieser** [comment]
This has been fixed a while ago already, I assume you are using an outdated version of the theme. Please update the theme either by re-selecting it in the Community Theme Browser or by downloading the latest release.
