### ISSUE TITLE
[Bug]: Character Decenders Cut Off in Hybrid Tab Header

### ISSUE THREAD

**Issue by pmbauer** [chrisgrieser/shimmering-focus#206]
### Bug Description

# Description
Character decenders are cut off in the hybrid tab header.

I have this css in a snippet that fixes it

```css
body:not(.no-tabbar-header-hybrid, .safari-tab-bar) .mod-root .workspace-tab-header-container:not(:hover) .workspace-tab-header:only-child .workspace-tab-header-inner-title {
	margin-top: -3px;
}
```

I'm using the default UI font, etc.

### Relevant spot in source.css

https://github.com/chrisgrieser/shimmering-focus/blob/95eabe33057de511e369b2339c0b57761330041a/source.css#L2482-L2483

### Relevant Screenshot

# With current version of Shimmering Focus
![CleanShot 2022-09-15 at 12 37 19@2x](https://user-images.githubusercontent.com/453580/190462903-0aa49f97-7029-498f-b563-4eb7883ee2e0.png)

# With `margin-top: -3`
![CleanShot 2022-09-15 at 12 37 08@2x](https://user-images.githubusercontent.com/453580/190462998-18fcc1f3-b92b-464a-a7c3-174b4852d3a8.png)

### To Reproduce

Create a note with a title containing character decenders, like g: `golang`

### Obsidian Version

0.16.3 (alpha)

### Installer Version

0.15.8

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
Thanks! added (with tiny adjustments) and released.
