### ISSUE TITLE
[Bug]: Hello! Found a bug, using dracula theme in light theme mode, some code colors are not rendered correctly, please look for the problem carefully and fix it in time, thank you very much for contributing a really great theme! 

### ISSUE THREAD

**Issue by zhouxinghong** [chrisgrieser/shimmering-focus#208]
### Bug Description

Hello! Found a bug, using dracula theme in light theme mode, some code colors are not rendered correctly, please look for the problem carefully and fix it in time, thank you very much for contributing a really great theme!
Also the brackets and punctuation characters in the code are not rendered.
OS: Windows 10 19044
Obsidian: 0.15.9

![2022-09-21_1](https://user-images.githubusercontent.com/54253524/191491216-e310ac5b-6699-450b-9512-40c777b5031e.png)
![2022-09-21_2](https://user-images.githubusercontent.com/54253524/191491234-911fff5e-4ab4-4c41-84e6-61db8b48081d.png)
![2022-09-21_3](https://user-images.githubusercontent.com/54253524/191491304-f96b51c5-6e40-43c5-9da0-afd0c6bb1f34.png)
![2022-09-21_5](https://user-images.githubusercontent.com/54253524/191492738-72383e2c-1a79-4ceb-96e2-102075844022.png)

### Relevant Screenshot

![2022-09-21_1](https://user-images.githubusercontent.com/54253524/191491216-e310ac5b-6699-450b-9512-40c777b5031e.png)
![2022-09-21_2](https://user-images.githubusercontent.com/54253524/191491234-911fff5e-4ab4-4c41-84e6-61db8b48081d.png)
![2022-09-21_3](https://user-images.githubusercontent.com/54253524/191491304-f96b51c5-6e40-43c5-9da0-afd0c6bb1f34.png)
![2022-09-21_5](https://user-images.githubusercontent.com/54253524/191492738-72383e2c-1a79-4ceb-96e2-102075844022.png)

### To Reproduce

settings...

### Obsidian Version

0.15.9

### Installer Version

0.15.9

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
Hi!

Obsidian 0.16 has a completely new theme, which required a full rewrite of Shimmering Focus. Since 0.16 is basically a fully rewritten theme, and since 0.15 will soon be outdated, I am unfortunately not fixing non-critical issues for the 0.15 Shimmering Focus anymore; sorry!

See also this checkbox (which you checked 😉 )
![Pasted image 2022-09-21 13 44 03](https://user-images.githubusercontent.com/73286100/191496047-077ba8fe-d83b-4189-94e5-4612fbacd7f3.png)

**Comment by zhouxinghong** [comment]
> (with 0.16, the issue will be gone anyway)

Hello! Do you have the offline installer for version 0.16? I would like to test it to see.

**Comment by chrisgrieser** [comment]
afaik, there is no offline installer; you need a [Catalyst License](https://help.obsidian.md/Advanced+topics/Insider+builds) to install it, or simply wait a bit until it's released publicly

**Comment by zhouxinghong** [comment]
> there is a theme version for 0.16. this one I continue to develop.
> there is another version of the theme for 0.15. For this one, I do not do any updates anymore, since it will soon be obsolete anyway.
Hello! How can I show the link by default and not hide it please? Where can I set it up?
![2022-09-22_171434](https://user-images.githubusercontent.com/54253524/191708173-08c38d9b-3630-4790-849d-8e81ea9b530a.png)

**Comment by chrisgrieser** [comment]
oh thanks for pointing this out, I simply forgot to add the option to it when re-writing the theme for 0.16.

Added the option in the latest release
<img width="969" alt="Pasted image 2022-09-22 11 47 56" src="https://user-images.githubusercontent.com/73286100/191715820-54fadb6b-a7ec-429a-8275-b65f0f377b33.png">

**Comment by zhouxinghong** [comment]
> oh thanks for pointing this out, I simply forgot to add the option to it when re-writing the theme for 0.16.
> 
> Added the option in the latest release

Hello! I'm looking forward to learning about the features of 0.16.x. Can you share a copy of your installed 0.16.x program file, compressed into a .zip file, with me via Google Cloud Drive? I can also continue to test your latest rewrite of the theme.

**Comment by chrisgrieser** [comment]
> afaik, there is no offline installer; you need a [Catalyst License](https://help.obsidian.md/Advanced+topics/Insider+builds) to install it, or simply wait a bit until it's released publicly

as I said, you need a catalyst license or simply wait to install 0.16

**Comment by zhouxinghong** [comment]
> > afaik, there is no offline installer; you need a [Catalyst License](https://help.obsidian.md/Advanced+topics/Insider+builds) to install it, or simply wait a bit until it's released publicly
> 
> as I said, you need a catalyst license or simply wait to install 0.16

Instead of installing the program offline, you can take your locally installed program, as follows.
![2022-09-22_233828](https://user-images.githubusercontent.com/54253524/191791799-8f94f567-3178-4c2c-9c4f-fe64ca53dd3d.png)

Compress it as a .zip and upload it to Google Cloud Drive, and it will be ready to share with me.

**Comment by chrisgrieser** [comment]
1) I am pretty sure that sharing the installer with you, without you having a catalyst license, would violate the user agreement of Obsidian. I am not interested in breaking the rules, sorry.
2) Also, I am on Mac, so that would not work anyway.

**Comment by zhouxinghong** [comment]
One more thing: can you remove the mouse click to enlarge the image, just like World in peace and quiet
