### ISSUE TITLE
There is no close or minimise window option

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#21]
I like the minimalistic approach but hiding the entirety of the window control options is unnecessary. I'd like to be able to at least close obsidian without right clicking its icon in the taskbar and picking "close window".

**Comment by chrisgrieser** [comment]
As explained in the readme, this theme is mainly intended for people who use mainly keyboard shortcuts.

However, you can also [re-enable the titlebar by using the Style Settings Plugin](https://github.com/chrisgrieser/shimmering-focus/blob/main/README.md#style-settings-plugin), as also explained in the readme.
