### ISSUE TITLE
Feature Re-Creation: Close (X) to click to close setting

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#213]
### Feature to be re-created

I would like to have the **Close** (X) at the Setting for it is handy to close the Setting

### Checklist

- [X] I updated to the latest version of the theme and checked that the feature has not been re-created yet.

**Comment by chrisgrieser** [comment]
There already is a setting for it you must have missed 🙂 
<img width="974" alt="Pasted image 2022-09-30 16 53 13" src="https://user-images.githubusercontent.com/73286100/193297433-606a0965-3694-48db-8779-f72327e76d60.png">

**Comment by Liong1976** [comment]
Oh, I thought it was only for the close buttons for tabs, not for the Setting, which I don't like.

Thanks, Chris, for showing it.
