### ISSUE TITLE
[Bug]: Misaligned icons in file explorer

### ISSUE THREAD

**Issue by Pasharet** [chrisgrieser/shimmering-focus#214]
### Bug Description

SHIMMERING FOCUS (**Version 2.331**)
Pixel 4a (5G), Android 11, 1080x2340

### Relevant Screenshot

![Screenshot_20220929-103745_Obsidian](https://user-images.githubusercontent.com/69254044/192975093-7403d432-443f-4a01-8dcc-74e86224578a.png)

### To Reproduce

...

### Obsidian Version

0.15.9

### Installer Version

0.15.9

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [X] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [ ] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [ ] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
Hi, the Obsidian core mobile theme is gonna get a complete overhaul, similar to the desktop theme in 0.16. The bug will not exist there anymore.
