### ISSUE TITLE
Feature Re-Creation:  how to get  buttons Toggle sidebar back?

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-focus#215]
### Feature to be re-created

How to get the "toggle right sidebar" and "toggle left sidebar" buttons?
I am on Obsidian 0.16.x, I checked the style settings but didn't find the option to enable it (as in vanilla Obsidian).

If this feature is not implemented yet, I am voting for it :)

### Checklist

- [X] I updated to the latest version of the theme and checked that the feature has not been re-created yet.

**Comment by danieltomasz** [comment]
Closing as I set up keyboard shortcut (ctr + l, ctrl + ;) for toggling sidebar :)

**Comment by bunnyhero** [comment]
i actually would like this feature too.
