### ISSUE TITLE
Feature Request: Better handling the scrollbar (more space)

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-focus#216]
### Feature Requested

If the page has scrollbar and the new placing of the filepath is enabled there is not enough space for the text to "breath", 

<img width="63" alt="image" src="https://user-images.githubusercontent.com/7980381/193562648-5425f59e-0b69-45b4-b1e4-7697ecd88dad.png">

Not a bug, but it  might be useful to add more space between scrollbar and text 

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by danieltomasz** [comment]
I dont know if this was explicitly adressed , but I see a bit more space between the text and scrollbar, and for me it is a bit nicer effect :)

**Comment by chrisgrieser** [comment]
> Not a bug, but it might be useful to add more space between scrollbar and text

well, for themes such spacing issues indeed count as a bug in my view, so no worries!

---

however, if you are using macOS (judging by the look of the scrollbar), then it is not a an issue of the theme, but rather a core Obsidian bug. On mac, the scrollbar is supposed to hide after a while, leaving enough space. But apparently, the scrollbar sometimes does not hide, an Obsidian restart usually fixed it for me.

You could report the issue in the Obsidian forum or in `#insider-desktop`

**Comment by danieltomasz** [comment]
I think it might be solved now in the obsidian  0.16.5 release :) There is more space between scrolbar and text and the scrollbar faster hide I think :) 

I forgot to report OS, it is MacOS indeed, it is a part of a bug  template but not the feature asking one!
Thanks for your work and the constant updates :)
