### ISSUE TITLE
[Bug]: Obsidian 0.16.4 Editing admonition/quotes bug

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-focus#219]
### Bug Description

When editing  admonition in the live view there is "a bump" on the left side, I didn't noticed this bump in 0.16.3

It might be related to this point in the 0.16.4 release notes
>Fixed styling of nested block quotes in live preview.

### Relevant Screenshot

<img width="592" alt="image" src="https://user-images.githubusercontent.com/7980381/193905771-df7fe0a5-d3fe-438b-9bca-d4a93c719edd.png">

### To Reproduce

Insert admonition or two lines quote and start editing in the live view
```
> [!TODO] Most important thing for today
> 
```

### Obsidian Version

0.16.4

### Installer Version

0.15.9

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by danieltomasz** [comment]
issue still persists ;(

**Comment by chrisgrieser** [comment]
fixed
