### ISSUE TITLE
No enter before asset embed gives wider padding than enter - a bit illogical

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#22]
code without enter:
![image](https://user-images.githubusercontent.com/59067099/134939788-09e9304e-ffdb-4626-8cf2-43a17c3c34cb.png)

preview without enter:
![image](https://user-images.githubusercontent.com/59067099/134939740-9e4580c8-add5-4565-9d16-ef377b2dbd80.png)

code with enter:
![image](https://user-images.githubusercontent.com/59067099/134939864-950c8c4a-6210-4e4d-ba13-b0819323a3b3.png)

preview with enter:
![image](https://user-images.githubusercontent.com/59067099/134939927-582cd743-3a30-484c-9228-45269eacc16b.png)

**Comment by chrisgrieser** [comment]
I am sorry, but I honestly cannot tell what the issue is based on those blurry images. 

Could you provide better screenshots, potentially with some lines indicating the issue? You can use Loren Ipsum dummy text so there is no need to blurry.

**Comment by DeutscheGabanna** [comment]
i'm sorry for that. i'll try to provide better screenshots

**Comment by DeutscheGabanna** [comment]
![image](https://user-images.githubusercontent.com/59067099/135268640-97bca7f0-311b-4489-806e-eb9222cc371b.png)
![image](https://user-images.githubusercontent.com/59067099/135268657-39191785-a4ca-4019-a217-94afdc0ee035.png)

**Comment by chrisgrieser** [comment]
Good catch, I didn't notice. Fixed it with yet another release (1.25).
