### ISSUE TITLE
[Bug]: kanban plugin overlays with show focus mode button

### ISSUE THREAD

**Issue by KraXen72** [chrisgrieser/shimmering-focus#223]
### Bug Description

kanban plugin overlays with show focus mode button

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/21956756/195790604-f6c52056-cff7-47df-bfc3-5d1fc0a2a964.png)
expected behaviour (willemstad):
![image](https://user-images.githubusercontent.com/21956756/195790640-55ec9978-fff0-4909-87eb-64d93ee3c5b7.png)

### To Reproduce

- have focus mode plugin
- have kanban plugin
- enable focus mode
- visit a kanban view

### Obsidian Version

1.0.0

### Installer Version

0.14.6

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by KraXen72** [comment]
also, checkbock ticks don't align properly: 
![image](https://user-images.githubusercontent.com/21956756/195995909-3ad1d7a7-27b5-4337-b04c-a46a36cfcee1.png)

**Comment by chrisgrieser** [comment]
Please open a separate bug report for independent issues
