### ISSUE TITLE
[Bug]: Floating TOC 2.2.2 style settings support conflicts with SF's

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#224]
### Bug Description

The new version of the floating TOC plugin adds support for style settings.
When SF is the active theme, FTOC's settings panel is not visible.
When using the default theme, it is.
This may or may not be expected behavior.

### Relevant Screenshot

n/a

### To Reproduce

Install FTOC 2.2.2.
While SF is active, look for the FTOC section in SS - it is not there!
Switch to the default theme. Look for the FTOC section in SS - it is there!

### Obsidian Version

1.0.0

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
That's actually intentional - since SF overrides the floating ToC styling, the style settings for ftoc would not work anyway. Have I removed them to reduce confusion 🙈
