### ISSUE TITLE
[Bug]: Backlink and URL share the same style

### ISSUE THREAD

**Issue by suliveevil** [chrisgrieser/shimmering-focus#225]
### Bug Description

Backlink and URL share the same style: See Line 12 and 13.

version: 3.175

### Relevant Screenshot

<img width="1440" alt="截屏2022-10-15 11 13 44" src="https://user-images.githubusercontent.com/35763237/195966541-7ed05960-afe3-4aac-aab1-267d80a0a95a.png">

### To Reproduce

1. Open Safe Mode
2. Put this text into a file:

```text
[[URL Scheme]]：[TextMate URL Scheme](https://macromates.com/textmate/manual/opening-files#url-scheme)
```

### Obsidian Version

1.0.0

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
Don't they also look the same with most themes, including the default theme?

So if you want them to look different, that would be a feature request, not a big report. Or am I misunderstanding something?

**Comment by suliveevil** [comment]
> Don't they also look the same with most themes, including the default theme?

No, almost all themes will add an URL icon for URL links or use double underline for BackLinks(bi-direction): 

![icons8-链接-100](https://user-images.githubusercontent.com/35763237/195980862-58ed4957-5b86-4163-8d48-438fbe23a250.png)

![icons8-外部链接-120](https://user-images.githubusercontent.com/35763237/195980873-8a064001-00ee-4066-be2f-700ce98947b2.png)

**Comment by chrisgrieser** [comment]
ah, that's what you mean. Those are called wikilinks, not backlinks ;)

Yeah, in the theme, wikilinks get double underlines, while normal links get normal underlines. That was only working in Reading mode, but not in Live Preview. Fixed for Live Preview in the latest update.

**Comment by suliveevil** [comment]
Thank you very much 🥰
