### ISSUE TITLE
Feature Re-Creation: Hide backlinks below file

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#227]
### Feature to be re-created

I'd like to be able to hide the backlink-section below the end of the file again. Although mostly aesthethic, it is one of the more minimalistic parts of the theme so far, and especially on heavily linked-to files the list can become a bit ridiculous. At a certain threshold - at least on my system - said list will introduce lag on certain files that I must link to and open _a lot_. 

### Relevant Screenshot

![grafik](https://user-images.githubusercontent.com/80548781/196051075-53d64c15-e21d-4dd4-8d2c-bdd6651492a9.png)

### Checklist

- [x] I updated to the latest version of the theme and checked that the feature has not been re-created yet.

**Comment by chrisgrieser** [comment]
You can already hide them, there is a toggle at the plugin settings menu of the backlinks plugin

**Comment by Gewerd-Strauss** [comment]
Stupid question: was this ever covered by the theme? Cuz they appeared suddenly after the update, and I did not actively change my settings, nor did I recall the changelog stating that said setting could reset. 

This is obviously resolved now - it works perfectly, but I am _very_ confused.

**Comment by chrisgrieser** [comment]
This was never covered by the theme. No idea why the backlinks plugin setting changed in update

**Comment by Gewerd-Strauss** [comment]
Alright, then I'll escuse myself for this pointless issue.
