### ISSUE TITLE
Feature Request: To make this theme compatible with the Influx Plugin

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#228]
### Feature Requested

I hope this theme is compatible with the Influx Plugin ((https://github.com/jensmtg/influx)). 

### Relevant Screenshot

This is what shows in the Default theme:

![image](https://user-images.githubusercontent.com/88898230/196062110-27bba1f1-d23e-40c7-b2f2-20ce5a47debc.png)

This is in this theme:
![image](https://user-images.githubusercontent.com/88898230/196062137-f91fdb93-6f76-4b38-a2e4-301a5bd26e02.png)

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by vizance** [comment]
+1 for this

**Comment by visua1hue** [comment]
+1 for plugin support, any updates on the plugin support @chrisgrieser?

**Comment by chrisgrieser** [comment]
In the latest release, there is an option to use the normal display of backlinks. That setting also affects the influx plugin, and enabling it will display the regular influx plugin display you want.

![CleanShot 2023-02-05 at 18 10 40](https://user-images.githubusercontent.com/73286100/216833832-7e8446f1-6196-4c44-81e1-c710f0a36808.png)

**Comment by Liong1976** [comment]
Thanks, @chrisgrieser!
