### ISSUE TITLE
Feature Request: Render links to [[Note#Header]] as [[Header]] in Live Preview & Reading View

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#229]
### Feature Requested

When you link to a header in a specific note, said link will get rendered as seen in image1 (LP) and image2 (R) respectively.

Similar to how renamed links are rendered as their renamed instance ([[Living Place|place to crash]]  becomes [[place to crash]]), and comparable to how links (\[Google\]\(https://www.google.com)) are rendered as "[Google](https://www.google.com)", could it be possible to render links to headings as the heading alone? 
Meaning [[Living Place#Berlin]] should be rendered as "Berlin" in Live preview and reading mode, and [[Living Place#Berlin|Berlin, Alexanderplatz 420]] would render as "Berlin, Alexanderplatz 420". Essentially, Header renaming takes priority over the linked-to header, and the linked-to header takes precedence over the unwieldy shit that is "Note#Header" and "Note > Header" respectively.
I am not sure if this is doable by theme or if it requries a plugin, but I think it would be a good addition given this theme aims to minimise visual noise a lot.

Thank you,
Sincerely,
~Gw

### Relevant Screenshot

![grafik](https://user-images.githubusercontent.com/80548781/196155889-00abce27-eecd-47ec-a19a-0d5f6cb6dd4d.png)

![grafik](https://user-images.githubusercontent.com/80548781/196155800-c973ee3d-93b9-4141-bd72-c154f5a1b137.png)

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by Gewerd-Strauss** [comment]
I still think this is relevant. For Reading-Mode I found [Link Headers Directly](https://github.com/Signynt/link-headers-directly), but I think this could be implemented theme-sided.

**Comment by chrisgrieser** [comment]
This is a bit too specific to be made part of the theme, I'd recommend making a css snippet for it, sorry.

**Comment by Gewerd-Strauss** [comment]
All right, I will look into that avenue then. Thank you.
