### ISSUE TITLE
Is it possible to change the color of the "Page back/Page forward" buttons in the top left 

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#23]
These buttons show up as black on black and are barely visible. Would it be possible to give the page back, page forward arrows a different color, e.g. the same one as the Window title color? The latter shows up as white lettering for me.

Thanks :)

**Comment by chrisgrieser** [comment]
done in the latest release 👍

**Comment by ReaderGuy42** [comment]
Thanks :)
