### ISSUE TITLE
[Bug]: Single digit line numbers in code blocks

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#231]
### Bug Description

When using code blocks only a single digit is displayed. Lines 1-9 are displayed appropriately, but 10-19 all get 1, and so on...

### Relevant Screenshot

<img width="179" alt="image" src="https://user-images.githubusercontent.com/42705243/197817599-2be222ce-47cb-46d3-8d86-f075817ad3b3.png">

### To Reproduce

Create a code block with 10+ lines.
The example above uses plain text but it also occurs with python, etc.

### Obsidian Version

1.0.2

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
thx, fixed.
