### ISSUE TITLE
[Bug]: tags containing an emoji are centered.

### ISSUE THREAD

**Issue by okaydee** [chrisgrieser/shimmering-focus#233]
### Bug Description

Hi,

I have several emoji-tags, such as: #🌲, #🗄, etc. 

**The problem:** when applying the Shimmering Focus theme, in reading mode emoji-containing tags are  centered instead of retaining their proper place within the tag chain.

I attached screenshots of both editing mode and reading mode, with the emoji tag #🌲 as an example.

I am on Windows 10, and have Obsidian 1.0.3 installed.

### Relevant Screenshot

- editing mode:
![shimmering_flow_editing_mode](https://user-images.githubusercontent.com/117564877/200762769-8c634a2e-496e-41e6-bf60-1f70fe5ddaee.png)

- reading mode:
![shimmering_flow_reading_mode](https://user-images.githubusercontent.com/117564877/200762763-3151204e-72f0-46b7-b30a-58f6be6f59c9.png)

### To Reproduce

1. In Obsidian, select Shimmering Focus as your theme.
2. In your note, create a tag containing an emoji, such as #🌲
3. Apply reading mode. The emoji-containing tag will be centered.

### Obsidian Version

1.0.3

### Installer Version

1.0.3

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
Do you use any emoji-related plugins?

**Comment by okaydee** [comment]
Yes, I use Emoji Toolbar.
I think you're correct, and the problem is that Shimmering Focus and Emoji Toolbar might not compatible.

I just tried the following: 
1. I disabled Emoji Toolbar
2. I restarted Obsidian
This solved the problem, and emoji-tags are now displayed correctly in Shimmering Focus.
Can you confirm on your end that Emoji Toolbar is the reason for this issue?

**Comment by chrisgrieser** [comment]
got it, fixed the issue, Shimmering Focus should now be compatible with the emoij toolbar

**Comment by okaydee** [comment]
Thanks so much! I updated the theme, and now it looks perfect 🙂
