### ISSUE TITLE
[Bug]: Code Fence Block Indentation In Reading View

### ISSUE THREAD

**Issue by pdanford** [chrisgrieser/shimmering-focus#234]
### Bug Description

With a fenced code block with no language tag, the Reading View indents the first line, which it shouldn't.

### Relevant Screenshot

Screen shot refuses to upload, so just follow the "To Reproduce" section.

### To Reproduce

Make a multiline code block without a language tag and switch to reading mode:
\`\`\`
Line 1
Line 2
Line 3
\`\`\`

Line 1 gets improperly indented in Reading View like this:

```
 Line 1
Line 2
Line 3
```

### Obsidian Version

1.0.3

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by SnakeHit** [comment]
The same bug for me.
This bug only perform for ``` xxxx``` code block.
When I use any language text like ```c xxx``` , It perform normally

**Comment by pdanford** [comment]
This CSS snippet fixes it:
```
.markdown-preview-view pre>code {
    display: block;
}
```

**Comment by chrisgrieser** [comment]
thx, snippet is added to theme
