### ISSUE TITLE
[Bug]: Cannot move floating window on secondary monitor/screen 

### ISSUE THREAD

**Issue by captorxxv** [chrisgrieser/shimmering-focus#235]
### Bug Description

**Cannot move floating window on secondary monitor/screen **
When i open any note, or other object with option open in new windows it opens on my second screen which is perfectly fine however i cannot move it lkeft right up or down...
Ive tested different themes and it works just fine as expected 
Please fixe that, is this is my go to theme every time 

### Relevant Screenshot

Not needed 

### To Reproduce

Just open any note or even better open Canvas in new windows and try to move the window on 2nd screen 

### Obsidian Version

1.1.5  

### Installer Version

1.0.3

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
not being able to move the window also happens with the default theme for me. Probably you have the titlebar hidden (that's why you should have added a screenshot ;) ), and without a titlebar or sidebar, you cannot move windows.

You should re-enable the titlebar in the Obsidian appearance settings.
