### ISSUE TITLE
[Bug]: Wrong position of pandoc reference tooltip

### ISSUE THREAD

**Issue by agfaur** [chrisgrieser/shimmering-focus#236]
### Bug Description

Since the last pandoc reference update, my tooltip started appearing at the topright of the screen.

I narrowed down the problem to this piece of code in source: 
```
.pwc-tooltip {
	/* fix positioning being weirdly placed by the plugin when not on default
	 * theme?!?! */
	top: 5rem !important; /* stylelint-disable-line declaration-no-important */
	left: 5rem !important; /* stylelint-disable-line declaration-no-important */
	padding: var(--size-2-2) var(--size-2-3);
	border-color: var(--secondary-accent);
}
```

Particularly the top and left attributes of the .pwc-tooltip. 
I have commented them out manually in the theme.css code on my .obsidian folder and the tooltip now works fine.

I see that this was a correction done for a prior misspositioning of the tooltip.
It seems this piece is no longer needed?

### Relevant Screenshot

1. How it looks with the default theme.css code
<img width="2416" alt="Screenshot 2022-12-16 at 13 49 55" src="https://user-images.githubusercontent.com/61879939/208101810-d1d7e9f2-393e-43c3-857b-3f389289f321.png">

2. The change to the theme.css file:
<img width="402" alt="Screenshot 2022-12-16 at 13 50 30" src="https://user-images.githubusercontent.com/61879939/208101923-5926c396-1169-40c6-9738-7166af2a0518.png">

3. How it looks afterwards:
<img width="2416" alt="Screenshot 2022-12-16 at 13 50 51" src="https://user-images.githubusercontent.com/61879939/208101959-05b947c8-b75b-4863-a5ed-3423d251482f.png">

### To Reproduce

1. Insert a pandoc reference with the relevant .bib file correclty located and the pandoc reference plugin installed.
2. With the default code of shimmering focus, hover over the citekey.
3. This happens only with shimmering focus -- at least not with the Default theme or minimal.

### Obsidian Version

1.1.5

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
Yeah that is indeed correct, however, the tooltips still show up in a wrong position in reading mode. [As far as I can tell, it's a bug with the Pandoc Reference List plugin.](https://github.com/mgmeyers/obsidian-pandoc-reference-list/issues/51)

But for source mode, your fix is indeed correct though. Will be added to the next release of the theme.
