### ISSUE TITLE
[Bug]: YAML-Keys trimmed in Reading mode and yaml-tags no longer visually separated from rest of frontmatter

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#237]
### Bug Description

I just went on to update the theme once again - I don't recall which version I was on previously, maybe .080 minus, or something? idk - and suddenly the frontmatter block is rendered differently. I checked the style settings for a relevant setting, but could not find anything related.

---

Completely unrelated things, some of which are definitely not supposed to be in this issue:
1. The link to the changelog-file in the Checklist below is broken. Just fyi. 
2. Even less related, if you could tell me if your [academic knowledge management vault](https://www.youtube.com/watch?v=4zKrY9-wrjU&t=661s) mentioned in Danny's [Obsidian October Winners 2022](https://www.youtube.com/watch?v=4zKrY9-wrjU&t=661s) is publicly available/where to find it, I would be very happy. I've been unable to locate it.

### Relevant Screenshot

Input in live preview: 
![grafik](https://user-images.githubusercontent.com/80548781/208722497-db20c159-68c9-40ff-ace9-085b3a07d696.png)
Resulting Image in Reading Mode:
![grafik](https://user-images.githubusercontent.com/80548781/208722719-30c1c0b0-e2e8-47cc-8b04-47cb5200a97e.png)

Only partial snapshot of how it looked previously, unfortunately in a file without a `tag`-yaml-field:
![grafik](https://user-images.githubusercontent.com/80548781/208724886-7cf0de55-0c41-4bb0-97e4-a27cd676f9df.png)
Keys were colored as well, if I am not completely crazy. The above snapshot is from 09.09.2022.

No other theme, including the default one, exhibits this behaviour.

### To Reproduce

1. Use an unknown theme version published in the recent past (I'd assume). (I am running 3.256 right now, but I do not recall which version I ran beforehand unfortunately.) 
2. Open a note containing metadata
3. set up style settings

### Obsidian Version

1.1.8

### Installer Version

1.0.3

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](../../README.md#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](../../Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
> * The link to the changelog-file in the Checklist below is broken. Just fyi.

thanks, is fixed. 

> * Even less related, if you could tell me if your [academic knowledge management vault](https://www.youtube.com/watch?v=4zKrY9-wrjU&t=661s) mentioned in Danny's [Obsidian October Winners 2022](https://www.youtube.com/watch?v=4zKrY9-wrjU&t=661s) is publicly available/where to find it, I would be very happy. I've been unable to locate it.

well, that's cause I have never published any such vault? I think Danny mixed up something there, I never submitted a vault for Obsidian October 😅

**Comment by chrisgrieser** [comment]
I am sorry, from your report I cannot really tell what the issue is. I tested the metadata on the latest theme and Obsidian version and everything looks like it's supposed to. 

in the latest Obsidian version, one of the two frontmatter block has been in reading mode has been removed, namely the one which rendered yaml in colors. I assume that is the issue? 

If not, please attach screenshots comparing the default theme and shimmering focus so I can better tell what the issue is you have.

**Comment by Gewerd-Strauss** [comment]
> well, that's cause I have never published any such vault? I think Danny mixed up something there, I never submitted a vault for Obsidian October 😅

Oh no.... I'm sorry, this is **really** embarrassing. He seemed to refer to Chris Lovejoy (on GH, at least). I am only recently getting more active in the obsidian community, and wasn't aware that we had multiple Chris' and latched onto the first one I knew of, I'm sorry.🤦 


---

Source: 
![grafik](https://user-images.githubusercontent.com/80548781/208769491-1b5897b7-7944-49ee-b00d-387490acdfc3.png)

Reading View: 
![grafik](https://user-images.githubusercontent.com/80548781/208769160-c627de1a-388b-495f-9ab4-2464ae629481.png)


Default theme reading view:
![grafik](https://user-images.githubusercontent.com/80548781/208769671-8afff096-6a39-4317-a2bf-f82f289e756b.png)

and source

![grafik](https://user-images.githubusercontent.com/80548781/208769834-395ea668-73f8-4d17-b114-47ab8fd0a37b.png)




Just for clarification, is this the expected result in reading mode? 

Enabled "Permanently show Metadata & YAML Frontmatter (Reading mode) in my pseudo-test vault", otherwhise default settings and no relevant plugins enabled.


---

I tracked down the last confirmed version in which I do not have this change: 3.257 - the version of an offline, non-synced phone's instance of my vault that I don't keep up to date at all times. Is there a way to retrieve/provide a specific version of a theme so I can make a personal test of whether or not this is the theme's fault, or a weird plugin interaction? I keep my plugins up to date, but didn't recall updating a theme-related plugin today - and checking this will take substantially more time :/

Below is a screenshot of the theme as it is rendered on my phone, at version 3.257, with essentially the same plugins enabled as on PC - they sync to the same vault, so the only delta between the two is that my PC-vault has been updated theme- & plugin-wise today, which is not synced because I disabled plugin sync a few days ago.


![grafik](https://user-images.githubusercontent.com/80548781/208772875-f1791ac5-61a8-4e47-965c-1340706eccc8.png)

**Comment by Gewerd-Strauss** [comment]
> thanks, is fixed.

No it's not :P




![grafik](https://user-images.githubusercontent.com/80548781/208774031-a298d66d-55ff-433a-85cf-3afff97ed5bb.png)
(I am sorry for the extremely funky arrow solution, couldn't be bothered to do this properly)

I am talking about the [this link](https://github.com/chrisgrieser/Changelog.md#changelog) (raw: https://github.com/chrisgrieser/Changelog.md#changelog) in the checklist for (bug-)issues, cf above image and the respective link in this very issue.

**Comment by chrisgrieser** [comment]
> No it's not :P
yes it is :P

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/73286100/208782791-76cc519c-0993-4947-bfd2-8753ed97003b.png">

probably the link has not yet updated for you due to github's caching. Try force reloading ;)

**Comment by chrisgrieser** [comment]
> Just for clarification, is this the expected result in reading mode?

yes, it's the expected result, due to the change from Obsidian core to remove the other yaml frontmatter block. 

It only *looks* a bit plain since I also removed "tags" and "aliases". Guess it's better to add them back to prevent confusion. :P

**Comment by Gewerd-Strauss** [comment]
> probably the link has not yet updated for you due to github's caching. Try force reloading ;)

Alright, now  I am confused. Did, didn't change shit. So I went to edge (_ugh_, but it's actually surprisingly useable now), which is my backup browser and that _still_ didn't let me access the link :P Is GH caching for my machine's IP in general?  But it also doesn't seem to update on my phone, regardless of how I access it - doesn't work from GH app, nor if visiting this website in the browser, regardless of device or login-status. This is super weird. 

Huh, Idk. It won't kill me, I'll just assume it's a bug on my end as it clearly seems to work for you and keep this in mind for the time being. ¯\\\_(ツ)\_/¯

> change from Obsidian core to remove the other yaml frontmatter block.

By that, do you mean the missing yaml-keys, leaving only the values to be displayed? Is that revertible somehow/implementable? In find yaml values without any meaning as to what key they belong to borderline confusing, as in "might just as well forfeit the entire notion of displaying it at all" because frontmatter handles a great load of different shit for me. 

If you mean something else I am really confused.


> Guess it's better to add them back to prevent confusion

Yes. **Please**. Having frontmatter-aliases, and especially tags separated is a small, but very useful feature this theme provided me so far.

**Comment by chrisgrieser** [comment]
> Huh, Idk. It won't kill me, I'll just assume it's a bug on my end as it clearly seems to work for you and keep this in mind for the time being. ¯\_(ツ)_/¯

yeah no idea ¯\_(ツ)_/¯

> By that, do you mean the missing yaml-keys, leaving only the values to be displayed? Is that revertible somehow/implementable? In find yaml values without any meaning as to what key they belong to borderline confusing, as in "might just as well forfeit the entire notion of displaying it at all" because frontmatter handles a great load of different shit for me.

yes, Obsidian core now only has a metadata block which shows tags and aliases, nothing more. Knowing that metadata-improvements are up next on the roadmap, I assume that they are soon gonna add something else. But well, that is an Obsidian issue, not an theme issue.

nevertheless, tags and aliases should be easily distinguishable since one of them is colored, and the other is not?

**Comment by Gewerd-Strauss** [comment]
I mean, tags are, aliases are not, neither is anything else in that box . I'd prefer the box'd separation we had before; maybe as an optional setting? 
(Talking about this:
![grafik](https://user-images.githubusercontent.com/80548781/208827769-4df25c99-628b-4926-899c-de51dc1510ec.png))

**Comment by chrisgrieser** [comment]
The aliases can be distinguished by the arrow in front of each of them?

If you mean sth else, you will have to be more specific?

**Comment by Gewerd-Strauss** [comment]
![grafik](https://user-images.githubusercontent.com/80548781/208846281-c0544052-2a83-465a-80e2-2708b2bb6b06.png)


I am talking about the small box below the actual yaml-render that contains solely aliases and tags, without their key names "alias" & "tags", and with rendered hashtags and "link-arrows".  
To be sure, I just checked the differences between PC and synced vault state, the relevant plugins (all that deal with rendering in some sort or another) are on the same version on mobile. The only real difference is the theme version, 3.235 on mobile vault vs 3.258 on desktop.

And yes, I have absolutely no idea why this is suddenly colored, and not last time I took the screenshot. What I could confirm is that the image above is not a result of plugins, I took it in safe mode, and none of the core plugins have any reason to influence this. Thus, the theme is the only thing that can reasonably be the cause. 

The small box shown in the image also shows up for "Things", "default", "Minimal" & "Prism" (all non-legacy).

**Comment by chrisgrieser** [comment]
Yes, I know that you mean that small box. 

But what is your issue with it? What do you want changed?

**Comment by Gewerd-Strauss** [comment]
I want it there; instead of not. In the current version of the theme - with all plugins disabled - it is no longer rendered.  
I want that separate box for tags and aliases, for a better distinction of them vs normal frontmatter (as they are the only interactible and most important parts of the frontmatter to be rendered imo).

---

In a perfect world, I suppose I'd ask for a way to _only_ render those in reading view and disregard the rest of the yaml header (or even better,  have the rest be pushed to the floating button toggled by disabling `Permantently show Metadata & YAML Frontmatter (Reading Mode)` & address metadata and yaml frontmatter by separate settings ) entirely, but that's a bit more to ask for right know than I seem necessary - I can't do it myself, and it would be kind of rude to just ask you for featurs A-Z just cuz I'd want them; so I try to not be too overbearing.

---

P.S.:  
Is there a bug-tracker somewhere? I noticed that, if disabling the aforementioned setting `Permantently show Metadata & YAML Frontmatter (Reading Mode)`, only the "M" for the Metadata-block is shown. The "Y" mentioned in the setting itself is missing. But I don't know if you are aware of that already.

**Comment by chrisgrieser** [comment]
> P.S.:
Is there a bug-tracker somewhere? I noticed that, if disabling the aforementioned setting Permantently show Metadata & YAML Frontmatter (Reading Mode), only the "M" for the Metadata-block is shown. The "Y" mentioned in the setting itself is missing. But I don't know if you are aware of that already.

Yes, this github lol. Just open another bug report. Although that issue is already fixed in the latest theme version. As I said, one of the two frontmatter blocks in reading view have been removed, and that one was the one labeled with "Y" by the theme.

---

Sorry, but I still don't get what your issue is.
- "In a perfect world, I suppose I'd ask for a way to only render those in reading view and disregard the rest of the yaml header" this is already the case?
- "I want it there; instead of not. In the current version of the theme - with all plugins disabled - it is no longer rendered." have you maybe disabled the frontmatter block in the Obsidian settings? It's there for me.

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/73286100/208881538-d6655d89-22b3-48c6-bb75-908b80f073f1.png">

**Comment by Gewerd-Strauss** [comment]
Okay. I'll try and explain.

Image 1: Current View, all things updated, toggled on `Permanently show Metadata & YAML` and `Show frontmatter`
![grafik](https://user-images.githubusercontent.com/80548781/208907239-de9925af-de0d-4b5e-a402-d834bf494daf.png)

Image 2: Old rendering before whatever the heck happened (Reading view):
![grafik](https://user-images.githubusercontent.com/80548781/208909588-df890fc7-6792-4a26-b86a-5b82e91f1d18.png)


Image 3: The part of the old reading view that I would like to see permanently
![grafik](https://user-images.githubusercontent.com/80548781/208907551-0edfb037-e0ad-48dc-8d4c-3e2d2519476b.png)

Image 4: the Hover-menu for the metadata
![grafik](https://user-images.githubusercontent.com/80548781/208909043-2b5146dd-409a-4ebc-b5b8-bf875dd8969c.png)


---


> * "I want it there; instead of not. In the current version of the theme - with all plugins disabled - it is no longer rendered." have you maybe disabled the frontmatter block in the Obsidian settings? It's there for me.

Again, I am specifically refering to the contents of image 3 / the lower box image 2.

> * "In a perfect world, I suppose I'd ask for a way to only render those in reading view and disregard the rest of the yaml header" this is already the case?

I don't see that being the case.

We can show both permanently. We can move the metadata to the side. We can hide it all  together.

We cannot hide one and show the other, one of them we can't show at all.


Elaboration: 

The for-me-best-case would be

1) Allow completely hiding the general yaml header (the entire block of image 1, or upper box in image 2) permanently, independently of 2). This removes it from rendering, and does not add the on-hover letter mentioned in 3)
2) Allow completely hiding the alias&tag-subbox (image 3, lower box in image 2), independently of 1). This removes it from the rendering, and does not add the on-hover letter mentioned in 4)
3) Allow displaying the general YAML header (the entire block of image 1, or upper box in image 2) either permanently (cf. image 1), or on-hover (like image 4, but the yaml one that no longer exists)
4) Allow displaying the subbox containing alias & tags permanently, or on hover, compare step 3
5) haven them all show on hover (image 4, but also for tags&aliases)
6) have them all permanent (image 2)
7) have either one of them permanent, and the other one on-hover (<permanent yaml, hovered tags/aliases> ←→ <permanent tags/aliases, hovered yaml>)

Which essentially boils down to the crude points:

- implement the rendering of alias&tag as in image 3
- for the general yaml header, add a checkbox to decide if it is rendered at all
   - if the above option is set to "render it at all", add a checkbox to decide if it is permanently shown, or pushed to the "letter" on the side
- for the alias/tag-box, add  a checkbox to decide if it is rendered at all
   - if the above option is set to "render it at all", add a checkbox to decide if it is permanently shown, or pushed to the "letter" on the side


That would allow all of the scenarios outlined in steps 1-7 to be toggleable. 

---



I'm sorry if I apparently completely suck at getting my point across :P

**Comment by chrisgrieser** [comment]
> 1. Allow completely hiding the general yaml header 

This is what you get when the Obsidian setting "Show Frontmatter" is *disabled*?

> 2. Allow completely hiding the alias&tag-subbox (image 3, lower box in image 2), independently of 1). 

as I said before, the recent Obsidian update did get rid of one of the previously two frontmatter boxes in reading view (or rather, somewhat merged them.) So you cannot act independently on it. You should also notice that this is literally the same with every other theme, since it's an underlying Obsidian change?

> 3. Allow displaying the general YAML header (the entire block of image 1, or upper box in image 2) either permanently (cf. image 1), or on-hover (like image 4, but the yaml one that no longer exists)

This is what you get when the Obsidian setting "Show Frontmatter" is *enabled*?

> have either one of them permanent, and the other one

(Summarizing for the following points:) I may repeat myself, but as I said, there now only is *one* frontmatter box in Obsidian. you can hide it or not with the respective Obsidian setting. You *cannot* do stuff in one case and then in a different case, since I can either target the box, or not target the box via CSS. There is no more two boxes where you can do different things to. 

I don't know, maybe I am really misunderstanding something, but this issue is the *very same* with any other theme right now. I think what you are looking for is a feature request for Obsidian core? 

---

> We can show both permanently. We can move the metadata to the side. We can hide it all together.  
> We cannot hide one and show the other, one of them we can't show at all.  

this is a good example: you use "both", "one not the other" in these contexts and your post does not really make it clear what "both" or "one" or "the other" refers to. Having *four* images before, and then referring to *two* things keeps your point simply unclear.

> I'm sorry if I apparently completely suck at getting my point across :P

well, this is why students of STEM disciplines should visit classes in humanities or social sciences: not only for getting a look beyond their discipline, but simply cause in those classes, you practice making clear arguments lol. (sorry, if this sounds lecturing, I teach at university, after all 🙈)

**Comment by chrisgrieser** [comment]
btw, I pushed a new update with some changes to how metadata looks and new settings to customize that only tags or aliases are shown in reading mode. Not sure if that is what you are after, but it's the most a theme can do right now
