### ISSUE TITLE
[Bug]: The nowrap code block have a low clarity in canvas

### ISSUE THREAD

**Issue by SnakeHit** [chrisgrieser/shimmering-focus#239]
### Steps to reproduce
Add a canvas card from file which embed the code block.
**The theme which enable the code blcok nowrap** and the card display the code block will reduce the card render clarity.
<img width="945" alt="image" src="https://user-images.githubusercontent.com/45898625/208882607-8ce1fe30-87ac-4621-819d-c5d6272ab432.png">

> The right card have more clarity then the left card Obviously.

And you can drag the card to resize. 
When the code block have no "hide", It became **clear** immediate.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/45898625/208882772-913a5d5a-2193-41c7-9a3a-28b7fbaf79b7.png">
When the code block have "hide", It became **unclear** immediate.
<img width="383" alt="image" src="https://user-images.githubusercontent.com/45898625/208882834-52e8122c-9892-4b73-868b-989717dd46b6.png">

### Expected result

The card which **have nowrap code block** render normally.

### Actual result

The card which have "hide" code block have a low clarity.

### Environment

- Operating system: Apple M1

- Debug info:
```
SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 22.1.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Blue Topaz v20221221.1
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Advanced Tables v0.18.1
		2: Calendar v1.5.10
		3: Copy Block Link v1.0.4
		4: Easy Typing v5.1.1
		5: Vimrc Support v0.8.0
		6: Tasks v1.20.0
		7: Style Settings v0.4.12
		8: Reminder v1.1.15
		9: Obsidian Memos v1.9.7
		10: Image Toolkit v1.3.1
		11: Icon Folder v1.4.3
		12: Excalidraw v1.8.6
		13: Editing Toolbar v2.2.3
		14: Admonition v9.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Relevant Screenshot

.

### To Reproduce

.

### Obsidian Version

1.1.8

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
Good catch, is fixed
