### ISSUE TITLE
Dataview slight incompatibility

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#24]
![image](https://user-images.githubusercontent.com/59067099/135263864-07f4e5ef-702b-414e-9053-8585cf484221.png)

dataview snippet to run (if you have files that will be caught by the query) in order to see this in action:
```dataview
table without id row.type as Type, rows.file.link as Name
from "journal"
group by type
```

you need to specify a meta-data key called `type` and put some category names in there

**Comment by chrisgrieser** [comment]
fixed in latest release 👍

**Comment by chrisgrieser** [comment]
just so you know, with the latest update, those lines will appear again, since now the `dataview-list-in-table` cssclass has been added to remove the lines in those cases.
https://github.com/chrisgrieser/shimmering-focus#css-classes
