### ISSUE TITLE
[Bug]: When edit the code block in canvas card which use vim, the cursor disappear.

### ISSUE THREAD

**Issue by SnakeHit** [chrisgrieser/shimmering-focus#240]
### Bug Description

When edit the code block in canvas card which use vim, the cursor disappear.

### Relevant Screenshot

![iShot_2022-12-21_18 59 48](https://user-images.githubusercontent.com/45898625/208889821-1c56f1a3-cc7a-452d-985d-1bdd2406a3cd.gif)

### To Reproduce

**Enable the vim mode**
Add a file card which include the code block, Then move the cursor into the code blcok in canvas card to edit.

### Obsidian Version

1.1.8

### Installer Version

1.0.0

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
that one actually seems to be an issue with Obsidian core, not the theme: https://forum.obsidian.md/t/vim-block-cursor-not-visible-in-code-blocks-in-canvas-cards/51374

**Comment by chrisgrieser** [comment]
please report at the bug report in the forum that you also have the issue!
