### ISSUE TITLE
[Bug]: The title of templater tp.system.suggester never shows

### ISSUE THREAD

**Issue by spiritualgeek** [chrisgrieser/shimmering-focus#241]
### Bug Description

When using something like

`varXXXX = await tp.system.suggester(["Item 1", "Item 2"], ["Item 1 Content", "Item 2 Content"],"", "Select the Item")`

The `Select the Item` does not display

Works fine with the default template

Thanks

### Relevant Screenshot

N/A

### To Reproduce

As stated in the bug description. The e.g. can be copied to test

### Obsidian Version

1.1.9

### Installer Version

1.1.9

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
thx, is fixed.

**Comment by spiritualgeek** [comment]
Appreciate the speed in fixing :) Thanks!
