### ISSUE TITLE
[Bug]: Emojis gets warped in Italic in headings

### ISSUE THREAD

**Issue by N0rdskog** [chrisgrieser/shimmering-focus#244]
### Bug Description

If there's emojis in a heading, and the heading is in italic as a result of the automatic italic text of odd number headings, the emoji will be italic as well. (1st screenshot)

This is not an issue for the automatic emojis that appears due to tags (#). (2nd screenshot)

### Relevant Screenshot
1st
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/52853430/212921308-47e5adf5-e2e8-4be1-b852-bdfb7efbb58a.png">

2nd
<img width="514" alt="image" src="https://user-images.githubusercontent.com/52853430/212921889-2dda5120-ec2f-4059-90f3-6835698111aa.png">

### To Reproduce

1. Create an odd numbered heading. (#, ###, #####)
2. Add any emoji or symbol character to the text. 
3. Behold italic yellow faces and summation symbols! 

### Obsidian Version

1.1.9

### Installer Version

0.15.9

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
fixed
