### ISSUE TITLE
Feature Request/Help wanted: setting/cssclass for rendering `abstract` frontmatter-field in reading mode

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#246]
### Feature Requested

Hello,

I basically use only this theme and nothing else; and spend a good portion of my day on manuscripts - and that fraction will go on even more soon.
As the pandoc-plugin is way too limiting for me (and I need R anyways), I need to make a complicated step-wise documentbuilding of 

    obsidian syntax → standard markdown → R-markdown → convert to docx/html/...
    
Because most papers require a special formatting for the abstract, and because docx-templates require it be its own style, one cannot feed the abstract as a normal paragraph or section when executing pandoc. That means that the abstract is a single frontmatter line, which is then interpreted by pandoc and rendered in accordance to the template word file given.

Issue is, frontmatter's hidden in reading mode because having 40 lines of frontmatter is quite annoying. And on larger projects, when I have upwards of 20 keys, this gets even worse.

Thus, I would like to ask for the ability to render a frontmatter abstract field in reading mode, even if hiding all else. A potential would be to give  a userinput, maybe a simple edit-box, to feed comma-separated yaml-fields that shall not be hidden, in the same way that tags/aliases can be kept.

Considering the high customisability of this theme, its focus on minimalism and its at least partial support on academia I believe this to be a sensible addition.

Thank you.  
Sincerely,  
~Gw

---

Alternatively, I found [this post](https://forum.obsidian.md/t/reduced-frontmatter-in-reading-view/50442/2) that allows rendering selected lines of the frontmatter via

    .frontmatter-container .frontmatter-section:nth-child(4)
    

That of course works, but is cumbersome as it is key-agnostic and would have to be updated whenever the position of a key is wrong. Is there a way to detect the keyname of the n'th child and show it if it is "abstract", or within a list of strings? 

so something pseudo like

    ToShow="abstract,author,csl"
    for index, child in .frontmatter-container .frontmatter-section
       if Instr(ToShow, child)
           ;; render

(Obviously this is just pseudocode, and very simple one at that, but I think you get what I mean.)

### Relevant Screenshot

LP-mode:

![grafik](https://user-images.githubusercontent.com/80548781/215420307-ad605936-0e41-4894-b129-8c6a0ab847e9.png)

reading mode:
![grafik](https://user-images.githubusercontent.com/80548781/215420371-b1913aec-a420-4911-a128-4f650ab55eff.png)

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
> As the pandoc-plugin is way too limiting for me (and I need R anyways), I need to make a complicated step-wise documentbuilding of
> 
> ```
> obsidian syntax → standard markdown → R-markdown → convert to docx/html/...
> ```

Yeah, I also use pandoc directly. But I am pretty sure you can consolidate all that into one step by using a pandoc filter.

---

Regarding the issue, I definitely see the use case, however this goes beyond what is possible via CSS and therefore what is feasible via theme. (for the very reason you stated, in CSS we don't know the identity of frontmatter fields.) For what you want, one would require a plugin. I would check out the metadata-related plugins, maybe one of them gets you closer to what you want? Maybe via some customization of the [metatable plugin](https://github.com/arnau/obsidian-metatable)?

Also, the next item on the roadmap of the Obsidian devs is metadata improvements, so it makes little sense for plugin devs as well theme devs to create new metadata-related features, since the underlying Obsidian architecture is likely to change soon. However, this also means some of your requests are likely to be customizable via Obsidian core soon.

**Comment by Gewerd-Strauss** [comment]
> Yeah, I also use pandoc directly. But I am pretty sure you can consolidate all that into one step by using a pandoc filter.

I am not sure what you mean by that exactly, as to my knowledge obsidian's syntax cannot be used by pandoc in its normal form as it's highly customised compared to norm-abiding md.

> metadata improv

I wasn't aware that that was on track right now - I don't follow the minutae of obsidian's development - and will hold out for now if that is the case - because it makes no sense delving into this right now, as you pointed out. 

Thank you for the pointers, I'll take a closer look once I am through the upcoming exam hell week :P I can get a good amount of stuff modded myself, but yea. Modding a plugin by readings its code and inserting working, but janky solutions is not at all the same as conceptualising and writing it from the ground up.

**Comment by chrisgrieser** [comment]
> I am not sure what you mean by that exactly, as to my knowledge obsidian's syntax cannot be used by pandoc in its normal form as it's highly customised compared to norm-abiding md.

look into pandoc filters: https://pandoc.org/lua-filters.html

They allow you to make the necessary changes from Obsidian markdown to r markdown all at once. Takes a bit of learning at first, but could simplify your workflow a bit.
