### ISSUE TITLE
[Bug]: Metadata block icon and sidebar headers don't appear on Windows

### ISSUE THREAD

**Issue by joelatschool** [chrisgrieser/shimmering-focus#247]
### Bug Description

On Windows, with default settings, the metadata block icons and the sidebar headers don't appear, even on hover.

### Relevant Screenshot

<img width="960" alt="image" src="https://user-images.githubusercontent.com/94202132/215852071-7770825a-f5fe-47f4-9433-509eb0ae88c4.png">

### To Reproduce

N/A

### Obsidian Version

1.1.9

### Installer Version

0.15.9

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
Can you try updating to the newest installer version? (Manually re-download obsidian from the website)

**Comment by joelatschool** [comment]
Just did so, still having this problem. Also, I realize the screenshot doesn't show the metadata issue, so here's another
<img width="966" alt="image" src="https://user-images.githubusercontent.com/94202132/215900181-4936e133-ba6c-4493-b93d-3a9dbfdca15c.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/94202132/215900202-1866b7dd-55d4-4413-9671-85de184dfcc0.png">

**Comment by chrisgrieser** [comment]
Hmm, I cannot reproduce it in Mac, and I don't have a windows device. 

You could try whether using restricted mode fixes it, otherwise I don't really know what could cause that issue.

**Comment by joelatschool** [comment]
Unfortunately these screenshots are from the debug vault, so they are in restricted mode and with no other addons, themes, or tweaks. I might see if I can debug it myself one of these days just using the inspector -- what sort of div am I looking for?

**Comment by chrisgrieser** [comment]
well, if you want to have a look, here is the css for the hidden sidebar tab headers: https://github.com/chrisgrieser/shimmering-focus/blob/main/source.css#L3011-L3037

and here for the metadata button: https://github.com/chrisgrieser/shimmering-focus/blob/main/source.css#L2470-L2543

**Comment by joelatschool** [comment]
a few extra notes I've realized from experimenting:
- if I switch to obsidian window frame (instead of Hidden) then the hidden sidebar tab headers start working, although the metadata buttons don't.
- when "permanently show metadata block in reading mode" is enabled with style settings, the breadcrumb section ends up higher (to the point where in source or live preview mode it intersects with the three dots):
<img width="960" alt="image" src="https://user-images.githubusercontent.com/94202132/216144659-0ee39bf4-ca87-4bd1-a38b-0162cea4c9f7.png">

My guess is that it's something to do with the different ways that Windows and Mac handle the window control buttons (maximize, minimize, close) and maybe Windows users just don't realize that the metadata block should be there? Or maybe its a Windows 11-specific thing and that userbase is small enough no one's reported it yet?

**Comment by joelatschool** [comment]
I found a rule in app.css which seems not to be from Shimmering Focus that seems to be the culprit of the "M" frontmatter button not showing up:
```css
.markdown-preview-view:not(.show-frontmatter) .frontmatter-container {
  display: none;
}
```
Lines 5619-5621 of app.css. Disabling it makes the "M" button show up in reading view by default and the metadata block show up when the style setting asks it to.

Not sure why the "Y" button isn't showing up, though, or even what it's supposed to do.

**Comment by joelatschool** [comment]
After playing with it a little more I've realized that the frontmatter stuff is because I had "Editor > Display > Show Frontmatter" turned off, so this might just be intended behavior. I'd checked all my appearance settings but didn't think to check the editor section for something occurring in reading view.

The missing sidebar headers is trickier: after prodding a bit it seems like no mouse events are being registered in that corner of the screen at all. This seems to be because of an app.css rule:
```css
body:not(.is-grabbing):not(.is-fullscreen).is-hidden-frameless .mod-top .workspace-tab-header-container {
  -webkit-app-region: drag;
}
```
Electron apps don't register any mouse events in drag regions, because the OS is hijacking them so that you can drag the window: https://github.com/electron/electron/issues/1354, https://github.com/electron/electron/issues/7107

This seems to behave differently on Windows than on Mac, for whatever reason. Commenting this rule out makes the hover work, at the expensive of not allowing windows to be dragged using that corner anymore.

**Comment by joelatschool** [comment]
Sorry for the spam! After all that, here's what I have as my css snippet to fix this on my side:
```css
body.is-frameless.is-hidden-frameless .titlebar {
	height: 35px;
}
body:not(.is-grabbing):not(.is-fullscreen).is-hidden-frameless .mod-top .workspace-tab-header-container {
 -webkit-app-region: no-drag;
}
```
I won't put in a pull request for this as I'm not completely sure how the Obsidian theme packaging scheme works or whether this will work on Mac, but if you want to incorporate this then for technicalities' sake I'm releasing this snippet under a CC0 1.0 license.

**Comment by chrisgrieser** [comment]
> Not sure why the "Y" button isn't showing up, though, or even what it's supposed to do.

oh that's because that Obsidian feature has been deprecated, therefore there is no raw-yaml-frontmatter anymore, and therefore no "Y" button. Did not have the time to update the screenshot yet. (I mean, Obsidian is adding new features too quickly, so those screenshots get outdated fast 😅 )

> After playing with it a little more I've realized that the frontmatter stuff is because I had "Editor > Display > Show Frontmatter" turned off, so this might just be intended behavior. I'd checked all my appearance settings but didn't think to check the editor section for something occurring in reading view.

Ah yes, that is indeed the intended behavior. Glad this part is solved then.

> I won't put in a pull request for this as I'm not completely sure how the Obsidian theme packaging scheme works or whether this will work on Mac, but if you want to incorporate this then for technicalities' sake I'm releasing this snippet under a CC0 1.0 license.

haha, not even sure if so few lines of code even count as sufficiently high level to be licensed 😝 

No but jokes aside, thanks for putting the time in to investigate the issue, this seems indeed to be a windows-only issue. You can make a PR to the `source.css` file if you want, then I'll run the build-and-deploy workflow on my end. Or I can just take the snippet and add it to the theme, whichever you prefer. Interference with macos can be avoided by using `body:not(.mod-macos)` in the selector (only mac devices get `.mod-macos` as a class on `body`)

**Comment by chrisgrieser** [comment]
okay, I added it to the theme myself, and credited you for the snippet in the source & README. let me know in case there are still issues with it :)

**Comment by joelatschool** [comment]
Thanks! Sorry for going radio silent, school got really busy over the past week or so. Also yeah don't worry about the licensing thing, just know some people are really particular about that kind of stuff and wanted to make sure there weren't any issues.

I'm not sure what's going wrong though, because I'm still finding that this bug occurs when I turn my snippet off, even after uninstalling and reinstalling the theme. Unfortunately don't have any time to debug right now, might check later if possible.

**Comment by chrisgrieser** [comment]
weird. Your snippet is included at line 3040, if you wanna take a look later
