### ISSUE TITLE
[Feature Request] Option for emphasis on the pandoc citation without brackets 

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#25]
Hi Chris,
Thanks a lot for making this theme that works very with my academic writings.

If possible, I want to ask your favor to make an option for the emphasis on the Pandoc citation without the brackets. In the citation style that I use, putting the brackets adds parentheses on the Pandoc conversion.

For example, if I write:
See [@PARROTTPoliticalThought1980], 45. 

It will become: (See Ronald L. Parrot, _Political Thought_, 45). 

Since I don't need the parentheses, I have to write like this in Obsidian:
See @PARROTTPoliticalThought1980, 45. 

It will become: See Ronald L. Parrot, _Political Thought_, 45. 

Therefore, it would be great if your theme have an option to emphasize the Pandoc citation that doesn't include brackets.

Many thanks for considering my request.

**Comment by chrisgrieser** [comment]
I would love to have that myself, however, that is unfortunately not possible. The highlighting of Pandoc Citations is only done via a hacky wordaround that repurposes the so called bare-link-class in Obsidian. That class is defined as anything between two square brackets.

Any further / more precise highlighting must be enabled either by Obsidian or through a plugin. You can also upvote and promote [this request for a plugin that does exactly that](https://forum.obsidian.md/t/syntax-highlighting/102).

**Comment by Liong1976** [comment]
Thanks for your explanation, Chris! I totally can understand it.
