### ISSUE TITLE
Hello! Please bring back the top left and top right buttons, it's inconvenient to use without these two buttons in the theme. I hope it can be restored to allow users to freely decide whether to show or hide 

### ISSUE THREAD

**Issue by zhouxinghong** [chrisgrieser/shimmering-focus#251]
Hello! Please bring back the top left and top right buttons, it's inconvenient to use without these two buttons in the theme. I hope it can be restored to allow users to freely decide whether to show or hide 
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/c8a3a0d3-c9cc-429f-9977-6fc0ce00d78c)

Version: 3.470 
OS: Windows 10

**Comment by usernotnull** [comment]
+1, much needed. I was hoping to find it in the Style Settings.

**Comment by zhouxinghong** [comment]
+1, much needed. I was hoping to find it in the Style Settings.

**Comment by chrisgrieser** [comment]
added in latest update
