### ISSUE TITLE
[Bug]: Code-block-flair not aligned

### ISSUE THREAD

**Issue by visua1hue** [chrisgrieser/shimmering-focus#253]
### Bug Description

Code-block-flair not aligned on Windows

### Relevant Screenshot

![codeblock](https://user-images.githubusercontent.com/54352478/222406351-d822aa3c-e928-4013-bcf7-f60790c05945.png)

### To Reproduce

normal code block

### Obsidian Version

v1.1.15

### Installer Version

v1.1.15

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)

**Comment by visua1hue** [comment]
This snippet fixed it for me 💯 

```css
/* BUG Fix :: code-block-flair */
.markdown-source-view.mod-cm6 .code-block-flair {
    top: unset; 
}
```

**Comment by chrisgrieser** [comment]
thanks, fixed
