### ISSUE TITLE
Feature Request: checkbox styling based on task completion status (similar to Minimal theme)

### ISSUE THREAD

**Issue by mcndt** [chrisgrieser/shimmering-focus#254]
### Feature Requested

Minimal theme has extra checkbox states: https://minimal.guide/Block+types/Checklists

![image](https://user-images.githubusercontent.com/23149353/222955764-72c6e338-6c4d-4503-84a0-7ce92f73ebc2.png)

I would love to see something similar for this plugin, I think it fits the philosophy quite well being text-based and it is quite similar to the annotation tags already featured.

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by asphaltbuffet** [comment]
This would be phenomenal. I waffle between a few themes solely based on this feature. It would close the gap between some of my paper-based task lists and obsidian.

**Comment by asphaltbuffet** [comment]
I would only tweak the suggested format by putting a strikethrough on the text of `Done` items as well (similar to `canceled`)

**Comment by chrisgrieser** [comment]
I tend to refrain from this, since there is a plugin which already implements that allows you to create your own checkbox styling, customized to your needs and portable across various themes: https://github.com/ebullient/obsidian-snippetor

No need for every theme to re-invent the wheel ;)

**Comment by HuangZhuo** [comment]
> ### Feature Requested
> Minimal theme has extra checkbox states: https://minimal.guide/Block+types/Checklists
> 
> ![image](https://user-images.githubusercontent.com/23149353/222955764-72c6e338-6c4d-4503-84a0-7ce92f73ebc2.png)
> 
> I would love to see something similar for this plugin, I think it fits the philosophy quite well being text-based and it is quite similar to the annotation tags already featured.
> 
> ### Relevant Screenshot
> _No response_
> 
> ### Checklist
> * [x]  I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
> * [x]  The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
> * [x]  My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

[this](https://forum.obsidian.md/t/alternative-checkboxes-icon-bullets-copy-and-paste/35962/10?u=joy) may be helpful.

**Comment by HuangZhuo** [comment]
@mcndt [this](https://forum.obsidian.md/t/alternative-checkboxes-icon-bullets-copy-and-paste/35962/10?u=joy) may be helpful.
