### ISSUE TITLE
Feature Request: Aligning images

### ISSUE THREAD

**Issue by specblades** [chrisgrieser/shimmering-focus#256]
### Feature Requested

Please, add aligning images option like in Topaz Blue
 
https://forum.obsidian.md/t/theme-blue-topaz/6425/101

### Relevant Screenshot

<img width="532" alt="image" src="https://user-images.githubusercontent.com/113993746/223775846-655e7666-786a-44c9-8622-a9a7f03c612c.png">

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by xllowl** [comment]
This can be achieve by copying the part in Topaz blue css code and snippet that into the css.
