### ISSUE TITLE
[Bug]: Extra Spacing for Sidebar Buttons

### ISSUE THREAD

**Issue by emdoe** [chrisgrieser/shimmering-focus#258]
### Bug Description

Thanks for the awesome theme! I found there's a similar issue to #200, but for the sidebar button: 

<img width="172" alt="image" src="https://user-images.githubusercontent.com/2088116/228073547-31324ee0-d930-4cef-b9fd-0f1763b06172.png">

And I thought adding an extra ~10px should solve this small issue:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/2088116/228074657-50e7faf3-74c3-4fcc-9829-88b268828814.png">

I hope this information is useful. Thanks again for the great work!

### Relevant Screenshot

See the description above.

### To Reproduce

The most extreme case can be reproduced by changing the width of the window to about 700pt.

### Obsidian Version

1.1.16

### Installer Version

1.1.16

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
thanks, fixed
