### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by mscott99** [chrisgrieser/shimmering-focus#260]
### Feature Requested

To give an option to make the line numbers follow visual lines instead of logical ones.

With the vimrc plugin, I can have the j,k, keys mapped to changing visual lines instead of logical ones.

Also, it would be great to have the relative line numbers before the cursor line also.

Thanks for the awesome theme! I just discovered it.

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
Hi,

I, too, would love something like that, however, that is not possible to implement by a theme, since it goes beyond what you can do with CSS. You would require a plugin a for that.

**Comment by mscott99** [comment]
Okay, good to know thanks!
