### ISSUE TITLE
Feature Request:  Use new feature of BRAT to distribute insider theme version

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-focus#262]
### Feature Requested

Latest  OBSIDIAN-42 BRAT release has option to download and use beta theme if ` theme-beta.css` in the repo, it would be convenient that this theme would be distributed through this channel as well

https://github.com/TfTHacker/obsidian42-brat/releases/tag/0.7.0

### Checklist

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment]
currently, there is no separate insider version of this theme. But I'll keep it in my mind in case I need to create a new one. Thanks for the suggestins!
