### ISSUE TITLE
[Bug]: Exported PDFs are neither searchable nor selectable

### ISSUE THREAD

**Issue by mwidmann** [chrisgrieser/shimmering-focus#264]
### Bug Description

When I use the built in "Export to PDF" function with Shimmering Focus set as the theme, the exported PDF neither has selectable text nor searchable content. With any other theme I tried, this is not the case. Also the size of the created PDF file is 10x bigger than the one created with the default theme.

I tried analyzing the PDF with poppler's pdfinfo. This is what it returns on exactly the same exported note when the Shimmering Focus theme is enabled:

```
Creator:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.0.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
Producer:       Skia/PDF m100
CreationDate:   Tue Apr 25 16:12:20 2023 CEST
ModDate:        Tue Apr 25 16:12:20 2023 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      594.96 x 841.92 pts (A4)
Page rot:       0
File size:      367473 bytes
Optimized:      no
PDF version:    1.4
```

and this is the output with the default theme (or any other theme I tried:

```
Creator:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.0.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
Producer:       Skia/PDF m100
CreationDate:   Tue Apr 25 16:21:11 2023 CEST
ModDate:        Tue Apr 25 16:21:11 2023 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      594.96 x 841.92 pts (A4)
Page rot:       0
File size:      31190 bytes
Optimized:      no
PDF version:    1.4
```

### Relevant Screenshot

If required I can provide the PDFs.

### To Reproduce

1. Create a simple note
2. From the file menu choose "Export to PDF"
3. Open the created PDF
4. try searching in it.

### Obsidian Version

1.1.16

### Installer Version

1.0.3

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
Sorry, pdf export options are unfortunately not something that I plan to do. Reason being that I do not use PDF exports, and at the same time they are pretty time intensive to implement.

In case you find a solution, I'll gladly add it to the theme, but given all the other issues for this theme (and my other repos), PDF exports is unlikely something I have the time resources to implement on my own, sorry!

**Comment by chrisgrieser** [comment]
I actually accidentally stumbled upon the cause of this issue. should be fixed in the latest update
