### ISSUE TITLE
[Bug]: Mobile missing and misaligned icons

### ISSUE THREAD

**Issue by alphatownsman** [chrisgrieser/shimmering-focus#265]
### Bug Description

I really liked this theme but run into some show stoppers on my iPhone 12 mini

 - the close button is missed in setting view 
 - title text and top right icons in editor view are off by a few pixels

in case it matters, I disabled all community plugins so supposed not caused by other plugins.

## Missing close icon
![IMG_1051](https://user-images.githubusercontent.com/90480431/235331557-c579b1aa-9daa-462d-bf63-ef511ffca8c8.jpeg)

## Misaligned icon
![IMG_1052](https://user-images.githubusercontent.com/90480431/235331578-1d81143b-17fe-4ede-b013-a75502e5da0b.png)

### To Reproduce

on iPhone 12 mini, set the theme to this theme. 

### Obsidian Version

1.4.3(95) iOS

### Installer Version

API 1.1.16

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)

**Comment by benlind** [comment]
You can reenable the close button on mobile:

1. Install the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings)
2. In the Style Settings menu in Obisidian, expand Shimmering Focus > Show/Hide UI Elements and click the "Re-enable Close Buttons" setting
