### ISSUE TITLE
[Bug]: Remove predefined icon for #moc tags, as it overrides the icon set by the supercharged-links plugin

### ISSUE THREAD

**Issue by nilfric** [chrisgrieser/shimmering-focus#266]
### Bug Description

Remove predefined icon for #moc tags, as it overrides the icon set by the supercharged-links plugin latest (0.9.6).

```css
body:not(.no-built-in-supercharged-links) .data-link-icon[data-link-tags~="#moc"i]::before {
    content: "🗺 ";
}
```

### Relevant Screenshot

<img width="940" alt="image" src="https://user-images.githubusercontent.com/8360302/235341854-9a934265-a530-4cb1-8294-6f385cb5c40a.png">

### To Reproduce

1. Add `tags: moc` to note
2. Add `example: value` to note
3. In another note, insert a link to the first note
4. Configure supercharged links plugin to prepend a text (icon) if the note has `example: value`
Result: shimmering-focus css overrides the prepend text to instead display the map icon 🗺

### Obsidian Version

1.1.16

### Installer Version

1.1.16

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)

**Comment by chrisgrieser** [comment]
I added the missing option to disable the builtin icons for supercharged links:
![CleanShot 2023-04-30 at 10 40 16@2x](https://user-images.githubusercontent.com/73286100/235343967-c89fa32b-0f69-4cda-9903-cd6288d8a3bf.png)

**Comment by nilfric** [comment]
@chrisgrieser perfect, thank you!
