### ISSUE TITLE
[Bug]: Left margins of tabs in sidebar are cut off on Windows

### ISSUE THREAD

**Issue by flaminganimal** [chrisgrieser/shimmering-focus#267]
### Bug Description

On Windows, the left-most edge of tabs that have been moved to either of the sidebars are cut off. This includes the header fold buttons. 
When the tab is in Reading View, the left margin is removed completely, and the header fold buttons are inaccessible.

### Relevant Screenshot

Live preview:

![2023-05-04 (2)](https://user-images.githubusercontent.com/34195392/236126663-897220ed-2c8c-4e50-8f52-5b9f3d2a2743.png)

Reading view:

![2023-05-04 (3)](https://user-images.githubusercontent.com/34195392/236126682-f8c4c93d-ecdf-4f18-bf2e-49019dfe8d41.png)

### To Reproduce

1. Drag and drop a tab onto the sidebar
2. Enable reading view for the tab

### Obsidian Version

1.2.7

### Installer Version

1.1.16

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
actually not a windows issue but a general issue. fixed
