### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by maizehsu** [chrisgrieser/shimmering-focus#271]
### Bug Description

Trying to install the plugin but shows that there's no appropriate version found for Obsidian v1.3.5 macOS Ventura apple silicon.

### Relevant Screenshot

<img width="226" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/71319123/3b8403ed-34dd-4c9c-ba1d-1650e0a3d4f2">

### To Reproduce

Install the theme given versions and environ

### Obsidian Version

1.3.5

### Installer Version

1.3.5

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
oh thx for the info – fixed it.
