### ISSUE TITLE
[Bug]: No visual indication of multiple files  selected with shift or cmd in file manager

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-focus#278]
### Bug Description

on file selection is visible, but when selecting  multiple files, there is no visual indication which files are picked (wither with shift or cmd), this  is confusing

### Relevant Screenshot

No screenshot, as the selected files look the same way as unselected

### To Reproduce

TRy to select files with shift or cmd, files are selected but no visual indication which are selected

### Obsidian Version

1.4.1

### Installer Version

1.3.6

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by myserial** [comment]
@danieltomasz ,I encounter it as well , has you resolved?

**Comment by chrisgrieser** [comment]
has been fixed in the latest release

**Comment by myserial** [comment]
> has been fixed in the latest release

Thks! I've updated.
