### ISSUE TITLE
Search result highlight is yellow on green

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#28]
![image](https://user-images.githubusercontent.com/59067099/136176501-87f7f0ac-34ea-4a43-aa79-5482e7aa28f3.png)

**Comment by chrisgrieser** [comment]
could you please provide some information how you got that highlight? Like what type of search you used, how exactly I can reproduce this? I have styled most highlights already, so I assume it must be one that I have missed.
