### ISSUE TITLE
[Bug]:Hello! The header conflicts with other extensions after returning to the default style.

### ISSUE THREAD

**Issue by zhouxinghong** [chrisgrieser/shimmering-focus#280]
### Bug Description

Hello! The header conflicts with other extensions after returning to the default style.

Please see:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/1cd1c339-fd80-4ee7-ae44-88e72954483e)

The best performance should be:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/ffeef7d6-22cc-46ea-bf45-580003011cd7)

Windows 10
Extend latest version

### Relevant Screenshot

Hello! The header conflicts with other extensions after returning to the default style.

Please see:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/1cd1c339-fd80-4ee7-ae44-88e72954483e)

The best performance should be:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/ffeef7d6-22cc-46ea-bf45-580003011cd7)

Windows 10
Extend latest version

### To Reproduce

Hello! The header conflicts with other extensions after returning to the default style.

Please see:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/1cd1c339-fd80-4ee7-ae44-88e72954483e)

The best performance should be:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/ffeef7d6-22cc-46ea-bf45-580003011cd7)

Windows 10
Extend latest version

### Obsidian Version

1.37

### Installer Version

1.37

### In which mode(s) does the problem occur? (if applicable)

- [x] Source (Edit)
- [x] Reading (Preview)
- [x] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by zhouxinghong** [comment]
The problem occurs at:
source mode
reading mode
live preview mode

Windows 10
Extend latest version
Obsidian 1.37

**Comment by zhouxinghong** [comment]
The background colors of number 1 and number 2 do not match
![image](https://github.com/chrisgrieser/shimmering-focus/assets/54253524/b1df7fe7-4665-435c-90b0-795ef240879f)

**Comment by chrisgrieser** [comment]
1. please open separate bug reports for each bug
2. please state which plugin is creating the icon, since it does not appear to be a default icon. Otherwise, it is not possible to do anything about it
3. please do not fill your post with copypaste of the same content, it makes bug reports hard to read
