### ISSUE TITLE
[Bug]: The style of callout is not working properly

### ISSUE THREAD

**Issue by wanghaiqiangk** [chrisgrieser/shimmering-focus#281]
### Bug Description

All types of callout, e.g. note, caution, tip, etc, revert back to a plain style with only border colorized.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/shimmering-focus/assets/34156944/7293f438-f61d-40a5-81d4-44167389ec38)

### To Reproduce

Just regular ways to add a callout, like

> [!note]
> blabla

### Obsidian Version

v1.4.12

### Installer Version

v1.3.7

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
thx, fixed
