### ISSUE TITLE
Feature Request: Add a way to show Changelog whenever you update the theme for whatever reason!

### ISSUE THREAD

**Issue by Droyk** [chrisgrieser/shimmering-focus#282]
### Feature Requested

As of now, there's no changelog available, neither in the Obsidian theme store nor on GitHub. Being a non-developer, I can't understand what has been changed I can see the d/f's in the previous code & the present but that's it! I can only discern the alterations but not their significance. So I request you to add a changelog. it will take some additional time and effort on your part, but other users would genuinely appreciate your work. coz as of right now I don't see a compelling reason to update, aside from mere curiosity. Having access to a changelog would help us understand what specifically has been changed or what new got added which will make us understand the necessity of the updates.

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by ryan-p-randall** [comment]
+1 I'd also very much appreciate a changelog!

**Comment by chrisgrieser** [comment]
You can pretty much get a simple changelog by checking out this link: https://github.com/chrisgrieser/shimmering-focus/commits/main

The theme is mostly done, and mostly only includes maintenance updates (updates for new Obsidian features, like recently the Properties), so I do not think there will be big significant changes that justify a more elaborated changelog for now 😅 

So for now, the link above should suffice.

**Comment by chrisgrieser** [comment]
FYI, I added a simple [automated changelog, where changes will be logged from now on](https://github.com/chrisgrieser/shimmering-focus/blob/main/Changelog.md). 

For convenience, it is also directly linked in the Style Settings
![Pasted image 2024-03-12 at 11 50 52](https://github.com/chrisgrieser/shimmering-focus/assets/73286100/00180f1a-45fa-4f32-91f4-ba98dd1e13bb)

**Comment by ryan-p-randall** [comment]
Fantastic! Thank you for adding one and for letting us know!
