### ISSUE TITLE
Feature Request: Allow right-click in empty space of Files panel

### ISSUE THREAD

**Issue by jbhaywood** [chrisgrieser/shimmering-focus#283]
### Feature Requested

I just ran into this problem with creating a brand new vault with nothing in it yet. With the default style settings of the theme it's impossible to create new top level folders. Weirdly, there's no "Create new folder" option in the command pallet either. So the only way to get new parent folders is to install Style Settings and search around until you find the "Re-enable Navigation Buttons" settings and read the description.

I'll also say the the setting name itself isn't intuitive because there's nothing navigation-related about those buttons. They're more about managing the file list and creating things.

The request then is to make it so that you can right-click on the empty space of the panel and at least have the "New Note" and "New Folder" commands show up.

Version: 3.523

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
> Weirdly, there's no "Create new folder" option in the command pallet either. (...) The request then is to make it so that you can right-click on the empty space of the panel and at least have the "New Note" and "New Folder" commands show up.

Unfortunately, both of those aren't something a theme can change, you would need a dedicated plugin to get that behavior.


> I'll also say the the setting name itself isn't intuitive because there's nothing navigation-related about those buttons. They're more about managing the file list and creating things.

There is a search field at the top, where searching for "new folder" gives you exactly the result you needed:
![Pasted image 2024-03-14 at 18 00 50](https://github.com/chrisgrieser/shimmering-focus/assets/73286100/b50fb4cb-758e-4708-904c-756c7a2f25ca)

Nevertheless, you are right in that "Navigation buttons" is a bad description, I just improved the label.
