### ISSUE TITLE
Feature Request: Please let us disable Images: Size (Percent) altogether (including click and holding to zoom)

### ISSUE THREAD

**Issue by Eneswar** [chrisgrieser/shimmering-focus#286]
### Feature Requested

Like title says, please let us disable it.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/shimmering-focus/assets/22943781/b96ed25e-bd13-488b-a2b9-7b597d0338dd)

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
Wouldn't setting this to `100%` effectively disable it?

**Comment by Eneswar** [comment]
I tried it but it still messes with various banner snippets such as https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments.

**Comment by chrisgrieser** [comment]
Sorry for not getting back to this earlier.

Unfortunately, making this theme work with specific CSS snippets is out of scope for this project – in my view, it's rather the task of snippet creators to make their snippets compatible with themes, not the other way round. 

Accommodating individual snippets would create more maintenance work for this theme than I am able to handle. Sorry! Maybe someone in the Obsidian discord server could help you out, modifying the snippet to work with this theme?
