### ISSUE TITLE
Feature Request: Status bar can be adjusted to use Masonry css snippet

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#29]
I just found a css snippet that is useful to write academic writing in [Discord](https://discord.com/channels/686053708261228577/702656734631821413/895496623604510790) and wonder if this theme can be adjusted (maybe through the Style Setting plugin) so that the status bar does not cover the scroll bar (see the screenshot).

![Masonry Theme](https://user-images.githubusercontent.com/88898230/136465507-625c2dfb-94a5-4846-95a0-7721a73197ac.png)

Thank you!

**Comment by Liong1976** [comment]
This is what I expect (in the Minimal theme):
![image](https://user-images.githubusercontent.com/88898230/136966897-392c92d6-7ecd-4e19-85de-03d39e407098.png)

![image](https://user-images.githubusercontent.com/88898230/136966941-4df407fa-8f75-4549-b223-b1f4d04279bd.png)

**Comment by chrisgrieser** [comment]
This still relevant?

**Comment by Liong1976** [comment]
Yes, for I need to use the so-called mansory snippet even though I am not using the longform plugin anymore after the outline-drag-drop feature was out. But, I am ok if you have no time to do it. Thanks for asking!

**Comment by chrisgrieser** [comment]
Well, I only noticed in Discord that you use Sanctum now, so I wouldn't want to work on this when you do not even use the theme anymore :P

Okay, so I'm gonna close this then for now, if this becomes relevant to you, feel free to re-open it at a later point in time!

**Comment by Liong1976** [comment]
The reason I am using Sanctum is that this theme is compatible with the Mansory snippet 😃 and it has the feature that your theme has which is focusing/highlighting the block. But, again as I said, _I am totally fine_ if you don't make this adjustment. 

This is the screenshot of the masonry snippet with the Sanctum theme.
![image](https://user-images.githubusercontent.com/88898230/143771681-ee1c337e-ffad-48f9-ad11-18a30aacc438.png)

**Comment by chrisgrieser** [comment]
ah okay, no problem!

I just added a style setting option to switch back to the default status bar, which should solve the issue for you – Update to the latest theme and you this should be solved for you :)

Sorry for this taking so long to implement, I didn't have that much time the last couple of days.

**Comment by Liong1976** [comment]
Whoa, that's great!
Thanks a lot for your hard work!
I totally can understand that you were so busy doing something that was for sure way more important than this adjustment.

**Comment by Liong1976** [comment]
Is there a way to make the font size of the status bar smaller so I can fully see information on it? Now I only can see partial information on the status bar.

![image](https://user-images.githubusercontent.com/88898230/143776310-9fc3e232-3422-4281-9a45-041175a6c4f2.png)

**Comment by chrisgrieser** [comment]
Good point – I added a style setting option to adjust status bar font size.

**Comment by Liong1976** [comment]
Thanks, Chris!
