### ISSUE TITLE
[Bug]: Sidenote Settings Don't Work

### ISSUE THREAD

**Issue by LennyPhoenix** [chrisgrieser/shimmering-focus#290]
### Bug Description

Attempting to change the "Width of Sidenote Callouts" setting has seemingly no effect.

### Relevant Screenshot

(Screenshots were taken after reloading the window to be sure)

Setting on lowest setting:

![image](https://github.com/chrisgrieser/shimmering-focus/assets/57148878/adc20fde-13ee-4cef-92bd-a3d88dd64497)

![image](https://github.com/chrisgrieser/shimmering-focus/assets/57148878/2c5b6317-0807-42c7-ad89-b2bfd5be2e5a)

Setting on highest setting:

![image](https://github.com/chrisgrieser/shimmering-focus/assets/57148878/b60cb25e-f78a-4208-9763-c3c0873080cc)

![image](https://github.com/chrisgrieser/shimmering-focus/assets/57148878/f6553a71-86cf-48a8-92d1-76b052906432)

### To Reproduce

1. Add a sidenote callout:

```md
> [!Sidenote]
> Test...
```

2. Adjust setting
3. Observe lack of style change

### Sample Text

```md
---
aliases: []
tags: [further-maths/notes/d1/graphs-and-networks]
sr-due: 2024-07-19
sr-interval: 310
sr-ease: 250
---

# Directed Graphs

If the arcs in a [[Graph]] have directions, the graph is known as a **digraph**.

> [!sidenote]
> This is known as Euler's handshaking lemma.

In any undirected graph, the sum of the degrees of the vertices is equal to $2 \times$ the number of edges. Therefore, the number of odd vertices must be even.
```

### Obsidian Version

1.4.16

### Installer Version

1.4.16

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
Hi, sorry for the late response.

The sidenote-cssclass was a super-old solution, when plugins like [multi column markdown](https://obsidian.md/plugins?id=multi-column-markdown) haven't been around yet. Since plugin provide a much more flexible and customizable solution for this, it does not make sense anymore to have something like the sidenote css class in this theme. 

Thus, I will actually remove the sidenote callout soon, I'd recommend using one of the by now many plugins which provide a much better experience for this.
