### ISSUE TITLE
Can't list tag hints when typing "tag:" in search box

### ISSUE THREAD

**Issue by myserial** [chrisgrieser/shimmering-focus#294]
### Bug Description

when search files with a tag forgotten the name, with the default theme, once typing "tag:" in the box, all tags will list, it's is helpful. but It's regret that shimmering focus miss it. expect tag hint can be added to searching. thanks!

### Relevant Screenshot

![no tag hint appear](https://github.com/chrisgrieser/shimmering-focus/assets/10251268/72ddca40-6108-4f67-9d61-eee530e1deab)

### To Reproduce

type "tag:" in search box, no tag hint.

### Obsidian Version

1.5.3

### Installer Version

1.4.16

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
fixed

**Comment by myserial** [comment]
> fixed

Thanks!

**Comment by myserial** [comment]
> fixed

Thanks!
