### ISSUE TITLE
[Bug]: Arrow symbols rendering in code blocks

### ISSUE THREAD

**Issue by Vadenmark** [chrisgrieser/shimmering-focus#295]
### Bug Description

Hi! Arrow symbols (← / →) is being rendered in inline code and in code blocks. I initially thought that it was due to some plugin I had installed, but after troubleshooting and disabling (and reinstalling) the "Smart Typography" plugin, as well as the "Code Styler" plugin I've realized that this seems to be due to how Shimmering Focus renders code blocks. 

### Relevant Screenshot

In the **default Obsidian theme** -> is not styled as →.
![default theme](https://github.com/chrisgrieser/shimmering-focus/assets/9417415/95b7090f-257e-4e17-8918-7ddf11076c8f)
However in **Shimmering Focus** it is.
![SF](https://github.com/chrisgrieser/shimmering-focus/assets/9417415/5eaad59f-8711-4baa-b235-cf0b691e4e2c)

### To Reproduce

With Shimmering Focus enabled, toggle inline code or insert a code block and type in "<-" or "->" 

### Sample Text

`->`

```
->
```

### Obsidian Version

1.5.3

### Installer Version

1.4.13

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [X] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
Ah yes, that's due to the new monospace font I recently switched to having ligatures (https://www.tempertemper.net/blog/ligatures-in-coding-fonts).

I'll fix that soon, in the meantime you can set a different monospace font in the Obsidian appearance setting to fix that.

**Comment by chrisgrieser** [comment]
> Love the theme btw!

thanks 😊 

---

Switched to Ubuntu Mono as default monospace font in the latest release. The font does not have these issues anymore. 👍
