### ISSUE TITLE
Right sidebar hides the main note panel 

### ISSUE THREAD

**Issue by myserial** [chrisgrieser/shimmering-focus#297]
### Bug Description

when right sidebar is showed, it's over the main panel and hide the note content.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/shimmering-focus/assets/10251268/d5130a83-2648-4c84-a443-8d1cb35b059b)

### To Reproduce

For example, when right sidebar is called by clicking backlist.

### Obsidian Version

1.5.11

### Installer Version

1.4.16

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] If your installer version is much lower your app version, you should update it by re-downloading Obsidian from [the Obsidian website](https://obsidian.md/). The installer version can be seen in the Obsidian settings (About → App → Installer Version).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Legacy Editor are not supported by this theme anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by chrisgrieser** [comment]
That's the "overlaying right sidebar" style setting, which you have likely enabled by default. Disable the setting and you have normal sidebar behavior.

**Comment by myserial** [comment]
Thanks! I have adjusted.
