### ISSUE TITLE
Option to show the “status bar” of the Quick Switcher and the Command Palette

### ISSUE THREAD

**Issue by notDavid** [chrisgrieser/shimmering-focus#298]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

### Feature Requested

Hi there,

The Quick Switcher and Command Palette have something like a “status bar” underneath displaying info about what pressing “modifier keys” do.
It is no longer visible when using this theme.

I can imagine the reason you might have hidden it, is because it is not very important. Is that correct? Or is it a misconfiguration on my part…?

If so, would it be possible to show it somehow?
Thank you!

### Relevant Screenshot

![IMG_1678](https://github.com/chrisgrieser/shimmering-focus/assets/1530401/a48584e1-6e27-475d-be51-89e8d6ee8d76)

**Comment by chrisgrieser** [comment]
I added a style setting to re-enable those instructions.

(Text might change, since I think I'd prefer to shorten it a bit.)

<img width="914" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/73286100/1ed8db86-a128-4e2b-99fb-71b4ec3df4e5">
