### ISSUE TITLE
[Bug]:  Can't show floatting-toc plugin's style setting in the Style setting plugin.

### ISSUE THREAD

**Issue by neuromaancer** [chrisgrieser/shimmering-focus#299]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

### Bug Description

When I use the shimmering focus, I can't see the options in the Style setting for float-toc. However, I can see these options in the default theme. Please see the screenshots below. PKM-er/obsidian-floating-toc-plugin#42

### Relevant Screenshot

With Shimmering-Focus:
![image](https://github.com/chrisgrieser/shimmering-focus/assets/28112871/f823cfa7-1d5d-41d6-8bb9-6e8c9dbd291a)
With default theme: 
<img width="820" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/28112871/c18f6c5c-2c7b-4e76-838c-855e8ccd85e6">

### To Reproduce

1. install float-toc
2. install shimmering focus
3. install style setting
4. enable shimmering focus, float-toc, style setting
5. check if the options for float-toc are in the style setting.

### Obsidian Version

1.5.12

### Installer Version

1.5.11

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

**Comment by chrisgrieser** [comment]
fixed (though I had to this theme's styling for floating-toc, so the look of the plugin may change a bit)

**Comment by chrisgrieser** [comment]
it's out on my end, could be that github caching takes a minute?

**Comment by neuromaancer** [comment]
Yeah, I think so too, nevertheless thank you!
