### ISSUE TITLE
Feature Request: Headerbar visible on hover (CSS Magicians wanted)

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/shimmering-focus#3]
I would really love to implement this, but do not know how. If any CSS Magicians know how to do it, I'd love to hear from you! 🙏

**Comment by arumazu** [comment]
Best works with Sliding Panes and enabled Readable Line Length

You need to change code on line 136 to this code:

`
/* only show on hover */
.view-header,
.is-translucent .view-header {
  opacity: 0;
  transition: 200ms;
}
.view-header:hover {
  opacity: 1;
  transition: 200ms;
}
`

**Comment by chrisgrieser** [comment]
I already came up with that solution (I use a similar one for showing the status bar only on hover).

However, with the header bar, this leaves an ugly grey bar on top

<img width="869" alt="Screenshot 2021-09-01 15 42 21" src="https://user-images.githubusercontent.com/73286100/131682288-884ed7c4-a36b-4c02-b601-df7a8360ba39.png">

**Comment by arumazu** [comment]
Yeah, I don't know how to solve this, but it looks more clear if you use Sliding Panes with vertical tabs.

**Comment by chrisgrieser** [comment]
Hah, I found a way to do it: Instead of changing the *opcacity* on hover, I changed the *height* on hover :)

Implemented in [release 1.3](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.3)
