### ISSUE TITLE
[Bug]: Header text and buttons are misaligned on mobile

### ISSUE THREAD

**Issue by sundevista** [chrisgrieser/shimmering-focus#301]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

### Bug Description

Buttons and text in the header are misaligned on mobile.

### Relevant Screenshot

![IMG_0217](https://github.com/chrisgrieser/shimmering-focus/assets/56955307/d644e0a3-006f-4aae-b443-af35fa3d9407)

### To Reproduce

1. Open any note on mobile

### Obsidian Version

1.5.12

### Installer Version

1.5.12

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] iOS
- [ ] Android

**Comment by chrisgrieser** [comment]
see https://github.com/chrisgrieser/shimmering-focus/issues/303#issuecomment-2085272112
