### ISSUE TITLE
[Bug]: Checkmarks are out of circle in callout on mobile

### ISSUE THREAD

**Issue by sundevista** [chrisgrieser/shimmering-focus#302]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

### Bug Description

On mobile checkmarks are out of checkbox’s circle if checkbox is in callout

### Relevant Screenshot

![IMG_0219](https://github.com/chrisgrieser/shimmering-focus/assets/56955307/9af57fed-defe-4667-84e6-4010cb927081)

### To Reproduce

1. Open any note
2. Create callout
3. Add checkbox
4. Check checkbox

### Obsidian Version

1.5.12

### Installer Version

1.5.12

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] iOS
- [ ] Android

**Comment by chrisgrieser** [comment]
see https://github.com/chrisgrieser/shimmering-focus/issues/303#issuecomment-2085272112
