### ISSUE TITLE
[Bug]: Folding arrow near header is too close

### ISSUE THREAD

**Issue by sundevista** [chrisgrieser/shimmering-focus#303]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

### Bug Description

Folding arrow for header is to close to the text of the header.

### Relevant Screenshot

![IMG_0220](https://github.com/chrisgrieser/shimmering-focus/assets/56955307/99a0fa47-3091-42a2-ad23-f544ffa9d7f0)

### To Reproduce

1. Open any note
2. Add a header

### Obsidian Version

1.5.12

### Installer Version

1.5.12

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] iOS
- [ ] Android

**Comment by chrisgrieser** [comment]
Ah, sorry – I don't use Obsidian on mobile anymore for a while, and thus the theme also does not support mobile anymore for a while already. 

Due to time constraints, I cannot look after a mobile version of this theme without actually using it myself, sorry.
