### ISSUE TITLE
[Bug]: MacOS Traffic Lights Overlap with Title

### ISSUE THREAD

**Issue by zschreur** [chrisgrieser/shimmering-focus#305]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Bug Description

When I start fresh in Obsidian and install Shimmering Focus the traffic lights are appearing on top of the title.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/shimmering-focus/assets/51675520/ece13fc8-8859-47da-a49e-bc3e737b0a8c)

### To Reproduce

1. Create a new vault
2. Install shimmering focus

### Obsidian Version

1.5.12 

### Installer Version

1.5.12

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows

**Comment by chrisgrieser** [comment]
> Obsidian Version
1.5.12

Are you sure about that? The issue does not occur for me on 1.5.12. It does occur for me when on the insider-release (1.6.1) though.

Since themes in Obsidian do not support proper versioning (as opposed to plugins), I cannot fix issues for the insider release, which would break stuff for the latest public release.

I already fixed the problem on the insider-release-branch, you can download and use this `theme.css` for the time being, if you prefer to stay on the insider release and still want to use Shimmering Focus: https://raw.githubusercontent.com/chrisgrieser/shimmering-focus/insider-release/theme.css

**Comment by zschreur** [comment]
Weird, this definitely is 1.5.12 - and I don't think I am on the insider release 🤷‍♂️ 

![image](https://github.com/chrisgrieser/shimmering-focus/assets/51675520/01393ddb-70c7-41fc-b6f7-2f59bb47878e)

**Comment by chrisgrieser** [comment]
Weird. I cannot reproduce the problem on my end.

Worst case, the issue solves itself with the next public release, since the underlying code for that part changed, and everything works fine on the insider branch of the theme.

**Comment by zschreur** [comment]
I'm on intel mac if that makes a difference

**Comment by chrisgrieser** [comment]
Hmm. Just a sanity check: on which version of the theme are you? If you open the file
`{your-vault}/.obsidian/themes/Shimmering Focus/theme.css`, it should say at the very top of the file.

Also, what Zoom level are you? (Settings → Appearance → Advanced → Zoom Level)

**Comment by zschreur** [comment]
- Zoom is 100%
- Window frame style is `Hidden`

```
SHIMMERING FOCUS
by @pseudometa
Version 3.568
MIT License
https://github.com/chrisgrieser/shimmering-focus
```

**Comment by chrisgrieser** [comment]
yeah, same settings, same Obsidian version, same theme version. Cannot really think of what the issue might be here 🤔 
![Pasted image 2024-06-05 at 17 45 31@2x](https://github.com/chrisgrieser/shimmering-focus/assets/73286100/343979a8-2c82-4592-a357-0ffd9b9084fe)

**Comment by chrisgrieser** [comment]
okay, as a suspected, the Obsidian update 1.6.2 has been released.

Could you update Obsidian to it as well as update Shimmering Focus and take a look whether this issue still occurs? (theme version number should be Version 3.617 after updating.)

**Comment by zschreur** [comment]
Works after the update!

<img width="522" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/51675520/aeaaab07-ca58-4194-986b-c2e4d07325c4">
