### ISSUE TITLE
[Bug]: edit menu is over 3 dot menu

### ISSUE THREAD

**Issue by jankoweb** [chrisgrieser/shimmering-focus#308]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Bug Description

Windows 11, current Obsidian version, current theme version, resolution 1920x1200.
The edit menu overlap 3 dot menu, so it is not visible and can't be reached.

### Relevant Screenshot

<img width="197" alt="Snímek obrazovky 2024-08-07 150914" src="https://github.com/user-attachments/assets/3c9346fc-f97f-4bca-9ba3-b061f94d6d5f">
<img width="124" alt="2024-08-07 15_25_58-📆 Plán - !work_diary - Obsidian v1 6 7" src="https://github.com/user-attachments/assets/833535a3-819d-4dc8-9bb7-4adcb904bb11">

### To Reproduce

Allow edit menu (icon in right bottom / show and hide), the 3 dot menu is not visible.

### Obsidian Version

1.6.7.

### Installer Version

1.5.3.

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows

**Comment by chrisgrieser** [comment]
That menu is not part of Obsidian core. Which plugin are you using for that toolbar?

**Comment by chrisgrieser** [comment]
got it, fixed.
