### ISSUE TITLE
Pane Become Dark when Longform CSS Snippet is Active

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#31]
When the [Longform](https://github.com/kevboh/longfor) css snippet is on, the pane turns to dark like this:
![image](https://user-images.githubusercontent.com/88898230/136960542-b230b0e2-a540-4d6d-8b16-35caad2b3298.png)

This is the use of the Longform css snippet in the Minimal theme:
![image](https://user-images.githubusercontent.com/88898230/136960762-5135b03f-3274-45d2-86c8-28baa10d2cbc.png)

Thanks

**Comment by chrisgrieser** [comment]
Hmm, I cannot reproduce the issue. Could you re-install the theme and also restart Obsidian?

**Comment by chrisgrieser** [comment]
also, are you using a css snippet that changes the styling of longform notes? In the most recent version, I added background-coloring for longform notes, when you are using a css snippet for longform stuff, this can also occur via some conflicting css.
