### ISSUE TITLE
Feature Request: Trim file names: re-enable full file name while file is being renamed

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#313]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] The request is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Feature Requested

I generally have the option turned on to Trim file names because otherwise I wouldn't get to see as many files. 

Admittedly my file names are generally pretty long, and since I don't know anyone else's workflow, I'm not sure how applicable for others this might be, but I generally have a date or number, descriptor, version, e.g. `2024-09-18 Application to College XYZ V.15`

Since I have many files, this would get unwieldy if it weren't for Trim file names, which I love. With that turned on, I only see `2024-09-15 Appli...` or similar, which is fine since for this type of work, I have these files in a folder.

However, when I want to rename a file, by right clicking the file, I kind of have to guess at the name because the ellipses `...` remains there even while renaming.

Is there a way to change that, so that while the cursor is in the file name in the sidebar, the entire name is displayed?

Thanks :)

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/76264b82-fc96-4438-8d23-257a22eee18e)

![image](https://github.com/user-attachments/assets/edbae74b-6273-4c5a-9bef-f7160f2d96b9)

These screenshots are from the sandbox vault, to make sure it's not any other plugins or snippets messing with this.

**Comment by chrisgrieser** [comment]
Huh, that's actually an issue Obsidian itself has. Nonetheless, it's a good idea to disable trimming while a file is being renamed, so I just added that.

**Comment by ReaderGuy42** [comment]
Thanks for replying so quickly! It seems after updating, the option to trim file names is now gone completely, along with the trimming. Was that intentional?
