### ISSUE TITLE
Bug: When trying to enter Vim mode, the text field in the popup to enter the command to exit Vim is missing

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#314]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.
- [X] My Obsidian installer version 1.1.9 or later. If not, please update first. You can find the version in the *About* tab of the Obsidian settings.

### Bug Description

I want to learn to use Vim so I was trying to enter Vim mode, but with Shimmering Focus the popup warning about Vim is different, in this case missing the actual text field. First I thought Obsidian had changed the way they check if the user knows Vim because there's a little warning box saying `Enter the command to enable Vim mode` so I was initially looking for a command to do that, when I realized that with the default theme the popup looks differently. 

This is in a brand new vault I made to practice Vim in, so there are no snippets, and all I have installed is Style Settings (with no settings changed), and Vimrc Support (with no settings changed).

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/f4ac6571-2458-4e5e-b4a8-fbd5f7e16d75)

![image](https://github.com/user-attachments/assets/79ddd8ac-7466-4833-9214-b84113af2582)

![image](https://github.com/user-attachments/assets/87e37019-7ef8-4276-89c5-e5b65d0d338a)

### Plugins Involved

Vim

### Obsidian Version

1.6.7

### Installer Version

1.6.7

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source Mode
- [ ] Reading Mode
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows

**Comment by chrisgrieser** [comment]
fixed 👍
