### ISSUE TITLE
Bug: Note title is smaller in header bar than Folder name, if Font Size has been increased

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#316]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.
- [X] My Obsidian installer version 1.1.9 or later. If not, please update first. You can find the version in the *About* tab of the Obsidian settings.

### Bug Description

With one of the more recent updates of your theme, the note title in the header bar, enabled via `Style Settings > Workspace > Use normal header bar` has become smaller. Alone that would be fine, but it looks odd because the Folder name is larger than the note name now.

The Folder name in the Header Bar is increased in size if the Font size in the default Obsidian Appearance settings are increased. However, the Note title remains at the default. This also works in reverse so if you make the font smaller, the folder name shrinks, note title remains the same.

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/a00791ab-c140-4267-9362-f90d4f065e4f)

### To Reproduce

1. Blank vault
2. install Shimmering Focus
3. install Style Settings
4. enable Header Bar
5. Obsidian Settings > Appearance > Change Font size

### Plugins Involved

Style Settings

### Obsidian Version

1.7.4

### Installer Version

1.6.7

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source Mode
- [ ] Reading Mode
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows

**Comment by chrisgrieser** [comment]
thx, fixed.
