### ISSUE TITLE
Feature Request: Supports UI, all text, and code block font family settings.

### ISSUE THREAD

**Issue by zhouxinghong** [chrisgrieser/shimmering-focus#317]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] The request is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Feature Requested

Supports UI, all text, and code block font family settings.

**Comment by chrisgrieser** [comment]
Since Obsidian 1.0, those can be set via the Obsidian settings themselves under appearance.
