### ISSUE TITLE
Bug: After the last update the appearance looks like the default one

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#318]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.
- [X] My Obsidian installer version 1.1.9 or later. If not, please update first. You can find the version in the *About* tab of the Obsidian settings.

### Bug Description

After I installed the last update the appearance looks like the default theme.

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/9b1b8dd5-18f5-46f6-a877-46e46c09b2c4)

### To Reproduce

1. Install the last update

### Obsidian Version

1.7.7

### Installer Version

1.7.7

### In which mode(s) does the problem occur? (if applicable)

- [X] Source Mode
- [X] Reading Mode
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows

**Comment by chrisgrieser** [comment]
Ah, thanks for telling me. That was a rather obscure bug with how globbing works different on my local device and on the GitHub remote…

Should be fixed now. (Might take a few minutes before the Obsidian theme store picks up the update on GitHub.)
