### ISSUE TITLE
Bug: When using the theme, the callout icons disappear (tested in Sandbox; images attached)

### ISSUE THREAD

**Issue by 1AshenPage1** [chrisgrieser/shimmering-focus#320]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.
- [X] My Obsidian installer version 1.1.9 or later. If not, please update first. You can find the version in the *About* tab of the Obsidian settings.

### Bug Description

When I use the theme, the symbols of most the callouts disappear and are replaced by a blank symbol as seen in the screenshot. the screenshots come from Shimmering and Default Sandbox in order to demonstrate the issue in a clean default environment.

### Relevant Screenshot

![Image 06 12 2024 at 18 04](https://github.com/user-attachments/assets/9bcbf197-37b8-407e-a66a-db18fafed266)
![Image 06 12 2024 at 18 04](https://github.com/user-attachments/assets/221e5c54-6cb9-4230-842d-418a18319aa2)

### To Reproduce

Install the theme in the sandbox, go to the Callout note, and the symbol will be gone. 

### Plugins Involved

No plugins, done in sandbox environment

### Sample Text

> [!NOTE]
> For compatibility reasons, if you're also using the Admonitions plugin, you should update it to at least v8.0.0 to avoid problems with the new callout system.

(Reference the provided screenshots)

### Obsidian Version

1.7.7

### Installer Version

1.7.5

### In which mode(s) does the problem occur? (if applicable)

- [X] Source Mode
- [X] Reading Mode
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows

**Comment by chrisgrieser** [comment]
Technically not a bug, but a deliberate decision by me to override the default callout icon 😅 

But I can see that this can come off as confusing, so I just removed the callout override, so all callout icons simply stay the same.

**Comment by 1AshenPage1** [comment]
Oh, I see, I am sorry, my bad then. I was just very much stressing if I have broken my vault somehow or not. 

Thanks for explanation. 
Have a great day/night.

**Comment by chrisgrieser** [comment]
all good, I can see that it can appear to be a bug. It's fixed anyway, so the problem should not occur anymore!
