### ISSUE TITLE
Feature Request: Command for toggling "Readable line length" on notes with tables

### ISSUE THREAD

**Issue by Rensing1** [chrisgrieser/shimmering-focus#322]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] The request is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Feature Requested

Currently, there is an option in the Style settings to "Automatically disable 'readable line length' on notes with tables". I really like this option! But it's not useful for every table or every note that contains a table.

So it would be nice to have a command so I can easily toggle to disable/enable readable line length without going to the Style settings.

**Comment by chrisgrieser** [comment]
good idea, added in latest release.

![Pasted image 2024-12-21 at 16 32 48@2x](https://github.com/user-attachments/assets/712c7489-afe0-4c9a-b405-25a4aa06389b)
