### ISSUE TITLE
Unordered list relationship lines can extend too far in edit mode when there are indentation issues

### ISSUE THREAD

**Issue by nfd9001** [chrisgrieser/shimmering-focus#38]
Example doc:
![image](https://user-images.githubusercontent.com/5666174/139597924-87ee9ba7-771f-453a-b072-7977b44af878.png)
...which renders normally in view mode:
![image](https://user-images.githubusercontent.com/5666174/139597938-e09f98ba-0abb-4747-bf04-4b404c4fcccf.png)

Adding an extra space to the obvious line causes edit mode to look as expected:
![image](https://user-images.githubusercontent.com/5666174/139598024-122ccc66-a45e-417b-95b9-4e52e24a348f.png)

**Comment by chrisgrieser** [comment]
since this isn't a critical issue & since relationship lines are gonna need a do-over with the upcoming version 0.13 anyway (due to the transition to CodeMirror 6), I'll postpone this issue for now and look into it when the CM6 changes are stable, just so you know

**Comment by chrisgrieser** [comment]
So I tried to look into it in the new editor and I think you can't make relationship lines work with wrong indention. 

Unless you find some theme or plugin that has relationship lines despite indention issues, I don't think I am able to do anything about this, sorry.
