### ISSUE TITLE
Feature Request: Code Syntax Highlighting

### ISSUE THREAD

**Issue by firinael** [chrisgrieser/shimmering-focus#4]
Hi, since the theme is focused on academic use, it'd be pretty nice if it had inbuilt code highlighting like the Dracula Theme.

You could import CodeMirror's code highlighting or use Dracula or any other color scheme, maybe even add option to switch in Style Settings?

Thanks!

**Comment by chrisgrieser** [comment]
I am not sure I follow. Isn't code highlighting stuff done by plugins like Editor Syntax Highlighting Plugin? 

Also I looked through the css of the Dracula theme and could not find anything in the code sections that does syntax highlighting, at least not any I saw recognized as such. I am happy to implement it though, if you can provide the css code that does syntax highlighting.

**Comment by chrisgrieser** [comment]
closed due to lack of required information. If you are still interested in this, feel free re-open this issue. :)

**Comment by firinael** [comment]
I'm sorry, it seems it was just some interaction between Dracula theme and the Syntax Highlighting plugin.
