### ISSUE TITLE
[BUG] Style Settings variable not correct

### ISSUE THREAD

**Issue by b1uegh0st** [chrisgrieser/shimmering-focus#40]
Hi,

 Thanks for a great theme.

 I tried to change the `regular-font` in Style Settings to something else but couldn't get it to affect the result. I digged around your CSS a bit (with my little knowledge of it) and thinking that you only use variable `default-font` in most of the CSS body.

 Changed this line from `regular` to `default` and it works for now.  

![image](https://user-images.githubusercontent.com/6695697/140571259-5db37bc6-3c18-4855-8184-c56282822b75.png)

 Thanks,
 NA

**Comment by chrisgrieser** [comment]
Ah, I forgot that one when renaming variables. 🙈

Thanks a lot – your suggestion is exactly the fix that was needed. 👍 
Just updated it.
