### ISSUE TITLE
[Bug - conflict] The Outliner (plug-in) folded indicator not showing

### ISSUE THREAD

**Issue by b1uegh0st** [chrisgrieser/shimmering-focus#41]
Hi,

 Thanks for a great theme.

 Step to reproduce:
 - Use [Outliner](https://github.com/vslinko/obsidian-outliner) plugin. 
 - Fold a header or a bullet point.
 - (expected behavior: show `...` by the end of the parent line)
 - Show the line is folded with no indicator `...`

 I understand that you want to maximize the focus in this theme so you hide a lot of elements. And it seems like not needed (as the arrow indicator showing fold or unfold already). However the `...` is pretty visual hint for me. 

 Hope you can check for an option to re-enable it.

 I attached a picture showing the quick inspecting of the CSS class for that (in other themes).
 
![image](https://user-images.githubusercontent.com/6695697/140765127-b8b80f4f-a7d5-409d-880d-397e624ecb5e.png)

**Comment by b1uegh0st** [comment]
By the way, the current folding also carry the child code-block formatting if included.


Unfolded
![image](https://user-images.githubusercontent.com/6695697/140955490-5ce418c0-0208-4d76-a1b0-6a2b609fe460.png)

Folded
![image](https://user-images.githubusercontent.com/6695697/140955440-cb102693-8cce-456a-9a09-2e72b424e14c.png)

**Comment by chrisgrieser** [comment]
You can simply re-enable the folding buttons with the style settings plugins :)

<img width="1038" alt="Screenshot 2021-11-12 14 26 31" src="https://user-images.githubusercontent.com/73286100/141474578-23ab59f2-0a0f-4db3-8537-c1b1efd34cdd.png">

**Comment by b1uegh0st** [comment]
Oh sorry I missed that. Did dig a bit in the Style Settings. My bad. I guess I was looking for something mentioning "..." :D

Thanks for the great theme.
NA

**Comment by b1uegh0st** [comment]
On an updated note: I tried and don't think that the setting is working (did try updated the theme).

![image](https://user-images.githubusercontent.com/6695697/141513241-fcc9875c-c063-422b-b66f-dff8903d7176.png)

**Comment by chrisgrieser** [comment]
ah, you meant *the other* folder markers 😝 
Sorry, I forgot that Obsidian has two types of folder markers (the arrow & the `...`). I added a new style setting option to re-enable the `...` :)
