### ISSUE TITLE
Usability Problem: Cannot show side bar for options and opening a different vault 

### ISSUE THREAD

**Issue by MariosGkMeng** [chrisgrieser/shimmering-focus#42]
After I activated this theme, I could not see the left side-bar which contains the options. I had to change the theme in the Appearance.json script.

**Comment by chrisgrieser** [comment]
I am sorry to say that this is a feature not a bug. 😅 

You can simply access the settings via keyboard shortcuts, or you can re-enable the left ribbon ("the left side-bar") by using the Style settings plugin. [See right here at the very beginning of the readme.](<img width="1038" alt="Screenshot 2021-11-12 14 26 31" src="https://user-images.githubusercontent.com/73286100/141474995-4b732c1c-544e-4fa6-b6aa-f8a30b32e206.png">)
