### ISSUE TITLE
Readable line width not working with sidebar collapsed

### ISSUE THREAD

**Issue by BradyRosino** [chrisgrieser/shimmering-focus#44]
I have the Obsidian "Readable Line Length" option set to enabled in the Editor settings. With this (awesome) theme, this option is not observed when the sidebar is collapsed. It works fine if I have the sidebar enabled, but once I collapse it switches to 100% width.

Based on the comment below in the CSS, it looks like this is intentional? Unfortunately for me using a large monitor in full screen mode, this decision makes the editor unusable.

Could this default behavior be reconsidered? or could it be added as an option in your Style Switcher plugin?

For now I've deleted the offending code, but I hope it could be corrected so I can stay on your latest version 😀

Thanks!

```
/* ─────────────────────────────────────────────────── */
/* < Max View */
/* full length editor and full size images when left sidebar is collapsed */
/* (Note: You need to turn on "readable line length" in the editor settings as well for this to work.)*/
/* ─────────────────────────────────────────────────── */

/* < Line Length & Tables */
body:not(.max-view-off) .workspace-split.mod-left-split.is-collapsed ~ .mod-root .markdown-preview-section ,
body:not(.max-view-off) .workspace-split.mod-left-split.is-collapsed ~ .mod-root .CodeMirror-wrap{
	max-width: 100% !important;
}
```

**Comment by chrisgrieser** [comment]
That the "Max View" feature of the theme! You can already disable it in the Style Settings :)

<img width="1116" alt="Screenshot 2021-11-12 14 23 57" src="https://user-images.githubusercontent.com/73286100/141474077-4c4f3b76-a298-41b8-987d-48f540bddfa8.png">

**Comment by BradyRosino** [comment]
🤦‍♂️ Haha, well that solves that... Thank you!

I promise I did look through the plugin before opening this issue. I suppose the "Images & PDFs" heading it is nested under threw me off because I wasn't using images or PDFs. Straight text.

Much appreciated.

**Comment by chrisgrieser** [comment]
ah, good point! I'll think about how to make the option easier to find.
