### ISSUE TITLE
FR: Style Settings Font Setting for UI

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/shimmering-focus#47]
I would like to use a slightly different font for the UI, but I can't seem to figure out what the setting is—it's not sidebar, and changing the main text should be for the editor—I was hoping to use something like Open Sans for the UI features.

**Comment by chrisgrieser** [comment]
when you say "UI", what elements in particular do you mean? Do you have some examples / screenshots?

**Comment by brimwats** [comment]
Settings/Community Plugins/Community Themes

![image](https://user-images.githubusercontent.com/49103046/141694888-e1c43bfd-6155-4eb3-93e6-ca0490c23f7c.png)

**Comment by chrisgrieser** [comment]
Style setting options to modify the menu font have been added in the latest release :)
