### ISSUE TITLE
Feature Request: Style Setting Option to show/hide folder icons and collapse arrows in File Explorer

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/shimmering-focus#48]
Could you add an option in stylesettings for the hiding/showing of folder icons and for the hiding/showing of arrows? The reasoning for this is the conflict with folder icon plugin: 

![image](https://user-images.githubusercontent.com/49103046/142091192-774eccd7-229c-43a5-9a3e-489130d9b0e1.png)

**Comment by chrisgrieser** [comment]
Just to make sure I understood this right: You basically need an option that hides the folder icons & re-enables the collapse-arrows that they replaced?

**Comment by brimwats** [comment]
you've summed it up perfectly! thank you :)

**Comment by brimwats** [comment]
(if it is possible!)

**Comment by sheriferson** [comment]
Requesting this here as it seems like a style setting, but happy to create a separate issue for it:

would you consider adding an option to disable active line highlighting? I looked and couldn't find it anywhere so I assumed the option doesn't currently exist.

**Comment by chrisgrieser** [comment]
@sheriferson Since that one is super easy to implement I added a style setting option to to das in the last update :)

Turning off the folder icons is a bit more work (adjusting the positioning etc.), but I'll try to implement it soon, @brimwats

**Comment by chrisgrieser** [comment]
@brimwats 
added a style setting to turn off file explorer icons in the latest update! 🙂
