### ISSUE TITLE
No more "releases"?

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#49]
Just a quick question: I was wondering why there were no more releases in the Github section? That made it easier to know when there was an update to the theme.

Thanks :)

**Comment by chrisgrieser** [comment]
Thing is that 99% downloads literally come through the Community Browser, so I think it's simply not worth the effort :P

You can simply check the theme Browser every now and then :)

**Comment by ReaderGuy42** [comment]
Ok, thanks :)
