### ISSUE TITLE
Sidebar/panel shortcuts

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#5]
Would it be possible to get a hoverview of the sidebar/panel shortcuts that some plugins use, such as the export Pandoc function?
Also, same question for the buttons in the top right to close the program?

Thanks!

**Comment by chrisgrieser** [comment]
Hi, I am not sure that I follow. What hover view are you talking about? Could you post some screenshots of what you mean?

**Comment by ReaderGuy42** [comment]
When you're using another theme, if you hover over the left side of the screen, several icons pop up, that are shortcuts for several plugins, such as "Open Graphview" or "Export to PDF", etc.
While I get that this theme is meant to be minimalist, it would be handy to able to access these shortcuts as well. 

Plus I wasn't able to access the regular buttons that are in all windows that let you minimize, maximize or close the window.

Thanks!

**Comment by chrisgrieser** [comment]
again, could you post a screenshot? And also link the theme that has that feature? Without those two pieces of information, it is hard for me to do anything.

**Comment by ReaderGuy42** [comment]
I apologize, I missed that notification. Here are two screnshots, the first with the default theme, the second with your shimmer theme. 
What I mean are the small icons on the very left edge of the screen, and the buttons in the top right corner.

![normal](https://user-images.githubusercontent.com/71895400/132132596-4a651a99-14f6-43e0-b5a8-81a53c172676.png)

![shimmer](https://user-images.githubusercontent.com/71895400/132132599-6aedb68b-01d3-43dc-af0b-3688a63c7f75.png)

I know the theme is minimal, but those shortcuts are pretty useful :)
Thanks!

**Comment by chrisgrieser** [comment]
Ah, got it.

With [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4), I added support for the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/). Using that plugin, you can simply re-enable the ribbons (the thin vertical sidebars to the far left and right). Then, you are able to use all those buttons again. 🙂

**Comment by ReaderGuy42** [comment]
Thanks for that! However, it seems that when I have the option to show the ribbons on and then restart Obsidian, it disappears again, even though the setting is still set to on. Also the font selection option does not appear to be working. Any ideas on that?

I put in "Consolas" in the Mono field and nothing happened. Also it seems that if I open the settings twice within a few seconds of each other, Obsidian crashes. Not sure if that's related to your plug-in or not.
Thanks for the help!

**Comment by chrisgrieser** [comment]
ah, thanks for the info. A small typo seems to have prevented the style settings plugin from correctly saving settings. Has been fixed in [release 1.4.3](https://github.com/chrisgrieser/shimmering-focus/releases), which you can download here at Github or by updating in the Community Theme Browser from within Obsidian.

**Comment by ReaderGuy42** [comment]
Awesome, thanks! Any idea how I can change the font of the edit mode though? It seems that I can only change it for code areas and headers, not for the regular edit area though. Last question, I promise :)

**Comment by chrisgrieser** [comment]
Unfortunately, for the moment, you cannot. [Changing the main font is a bit more complicated since the iA Writer font consists of multiple font files](https://github.com/chrisgrieser/shimmering-focus/issues/2#issuecomment-914909085) and I will have to figure out how you replace multiple fonts at once (replacing only one would break a lot of things).

**Comment by ReaderGuy42** [comment]
Alright, thanks!
