### ISSUE TITLE
Feature Request: "Trim file names in sidebars" like in plugin Advanced Appearance

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#51]
**Feature Requested**
The plugin Advanced Appearance has the option to trim the file names in the sidebars, which makes things a little clearer if you have long file names. It cuts off the titles after x amount of characters and replaces it with "...". Aside from this your implementation of Style Settings makes Advanced Appearance pretty much redundant, so adding the "trim file names" would just make it possible to work without Advanced Appearance.

**Relevant Screenshots**
![Screenshot from 2021-11-22 12-53-56](https://user-images.githubusercontent.com/71895400/142857333-655357b1-3f6e-4afe-859b-d4fe8858161f.png)

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings)

Thanks!

**Comment by chrisgrieser** [comment]
added a style setting implementing that feature in the latest update! 🙂

**Comment by ReaderGuy42** [comment]
Awesome, thank you!

**Comment by ReaderGuy42** [comment]
> added a style setting implementing that feature in the latest update! slightly_smiling_face

Hi again, quick question about this: Not sure if I didn't notice this till now or if something changed, but are folder names _not_ trimmed? If so would it be difficult to add an option to trim those as well? Thanks :)

**Comment by ReaderGuy42** [comment]
I figured it out and added a snippet:
```
.trim-long-filenames :is(.nav-folder-title-content, .nav-file-title-content, .tree-item-inner, .search-result-file-title) {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
```
(I added the `.nav-folder-title-content,`
Thanks :)

**Comment by chrisgrieser** [comment]
huh, you should have opened a separate issue for this, I almost missed this. 😝 

The latest update changes the style setting to also affect folder names.
