### ISSUE TITLE
[BUG]  Text no longer displays as "readable line length"

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#52]
**Describe the Bug**
As of this morning, using Shimmering Focus results in text not being displayed with the readable line length, meaning text only breaks at manual new-lines. When switching to the Default theme this does not occur.

**To Reproduce**
Open vault, and have only one note open on the whole screen; this makes it most apparent.

**Relevant Screenshots**
In Shimmering Focus

![Screenshot from 2021-11-23 11-04-59](https://user-images.githubusercontent.com/71895400/143005031-26d5f63d-cce5-42d0-9760-ecb470e69d29.png)

In Default theme

![Screenshot from 2021-11-23 11-06-39](https://user-images.githubusercontent.com/71895400/143005255-e17d8e02-edfe-4209-b2a7-9e4e769aaa0d.png)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] I also checked that it wasn't a download issue again, so I deleted and reinstalled the theme.

**Comment by chrisgrieser** [comment]
well, I am sorry to say, that this is not a bug, it's [a feature to change line length when hiding the left sidebar](https://github.com/chrisgrieser/shimmering-focus#max-view) ;)

You can simply turn the feature off in the style setting:
<img width="1063" alt="Screenshot 2021-11-23 13 22 38" src="https://user-images.githubusercontent.com/73286100/143023813-30a6363c-6eb8-45c8-8a05-41ccdd4a2f8f.png">

**Comment by ReaderGuy42** [comment]
Apologies, I must have changed that at some point at not noticed it. Thanks for clearing it up :)

**Comment by chrisgrieser** [comment]
no problem! :)
