### ISSUE TITLE
Feature Request: Stylesettings to Turn off YAML Formatting?

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/shimmering-focus#53]
Just a small idea— a stylesettings to turn off YAML formatting temporarily or permanently? I find it hard to spot YAML problems with the text in all black. Feel free to close this if you're opposed! :)

**Comment by chrisgrieser** [comment]
no problem at all, request makes total sense to me. I implemented it as a style setting in the latest update :)

(sorry for not responding/implementing your other requests yet – got a lot of work to do, but I have them on the radar.)

**Comment by chrisgrieser** [comment]
just so you know: as far as I can tell, the new editor does not allow to color the individual yaml elements anymore, so you won't get any coloring with newer versions of Obsidian / this theme :/

**Comment by chrisgrieser** [comment]
never mind my last message – it seems that was some bug, after restarting Obsidian, the selectors are back, so I re-added the feature 🙈
