### ISSUE TITLE
Can't see "star current..." buttons

### ISSUE THREAD

**Issue by ShannaSeigel** [chrisgrieser/shimmering-focus#55]
Hey, I'm not sure if this should be a feature request or I'm just missing something in the style settings. I realized today that I couldn't figure out how to add a search to the starred list until I switched to a different theme. I tried looking in the style settings to bring these buttons back but I didn't see anything helpful.

If this can't be fixed in the style settings then my feature request would be:
Be able to see or toggle the "star/unstar current file" and "star/unstar current search" buttons under the "starred" tab.

Thanks! I'm enjoying this theme!

**Comment by chrisgrieser** [comment]
Oops, I have hidden those buttons, as I thought you could do both via context menu and command palette anyway. But indeed, there is only a command to star a file, but not to star a search. My bad, sorry! 🙈 

I just added a new Style Settings Plugin option to re-enable those two buttons.

**Comment by ShannaSeigel** [comment]
> Oops, I have hidden those buttons, as I thought you could do both via context menu and command palette anyway. But indeed, there is only a command to star a file, but not to star a search. My bad, sorry! 🙈
> 
> I just added a new Style Settings Plugin option to re-enable those two buttons.

I didn't want to reopen this but I didn't know how else to say thanks for the super fast response! You're awesome!
