### ISSUE TITLE
Small [BUG] /Clarification: Decorative Quotation Mark

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/shimmering-focus#56]
Just wanted to point out that it's not clear from this description if the setting affects Live Preview or just Preview mode:
![image](https://user-images.githubusercontent.com/49103046/143780876-a50979b3-fa32-4562-9a56-79b2994a1bbd.png)

I hoped it would show up in LP but looks like it's just preview! :)

**Comment by chrisgrieser** [comment]
tbh, I didn't have time yet to do any sort of live preview adjustments for my theme 😅 

But thanks for pointing this out, I'll clarify it :)
