### ISSUE TITLE
[BUG] Style Setting Plugin Error

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#57]
**Describe the Bug**
The Style Setting plugin is showing an error.

![image](https://user-images.githubusercontent.com/88898230/144151921-d9328461-9d43-4dd4-bf62-f809c78b47ad.png)

**Comment by Liong1976** [comment]
The issue has been resolved. Thanks Chris!

**Comment by chrisgrieser** [comment]
yeah, just noticed it and pushed a hotfix already :)
