### ISSUE TITLE
[BUG] "Next" in Search function disappears if panel is too narrow (with example video)

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#58]
**Describe the Bug**
If you "search" (Ctrl+F) and the active panel is too narrow it seems that the "Next" button disappears.

**To Reproduce**
1. Make active panel narrow, by having the whole window be narrow, or just that panel.
2. "search" - Ctrl+F
3. Resize panel to see that the button does appear again when the panel gets to a greater width.
4. Resize panel back down again to see that it disappears again when the width gets too narrow.

**Relevant Screenshots**
Sorry for the audio. The crackling occurs even when the mic is off, so you'd best just turn the audio off for the video.

https://user-images.githubusercontent.com/71895400/144273722-5a551c0e-74a6-4fe7-821a-1261af15d01d.mp4

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme

.

**Comment by chrisgrieser** [comment]
That's weird 🧐 
I'll look into it

**Comment by chrisgrieser** [comment]
found the issue, fixed :)
