### ISSUE TITLE
Feature Request: Way to enable the old Calendar look

### ISSUE THREAD

**Issue by b1uegh0st** [chrisgrieser/shimmering-focus#59]
**Feature Requested**
I prefer the old calendar's look , I think it fits how I feel about the theme (more flat, less line). Although it is rather on the personal preference side of things, I do think that there are more who feel the same as me.

If it's not too much work, can you please have a Style Setting check to come back to the older look?

Thanks a lot for a great theme and your keep updating it.

**Relevant Screenshots**
New:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/6695697/144484834-676f1715-a61a-4845-b278-5e653c89475d.png">

vs. old: (with my custom fonts, but it's not the point here, my eyes are mostly on the lines)
<img width="254" alt="image" src="https://user-images.githubusercontent.com/6695697/144484882-f1087fef-e435-48ac-965b-033417d11549.png">

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
If it's just the calendar lines, that's easy to add an option to remove them. I have just pushed an update that adds such an option for the Style Settings plugin. :)

Is that what you were looking for?

**Comment by b1uegh0st** [comment]
Hi there,

Thanks for the prompt response and action. I think it is what I am looking for. 

This can be closed by now.

Thanks again,
NA

<img width="172" alt="image" src="https://user-images.githubusercontent.com/6695697/144556606-2e66007f-36c4-4bb7-af2d-43440a9b454d.png">

**Comment by b1uegh0st** [comment]
Just a gentle notes that since the new update (CM6?) the style settings for this stop working. Not an urgent need so just leaving a notes here @chrisgrieser .

Thanks for the great theme.

**Comment by chrisgrieser** [comment]
luckily, that one is quite easy. fixed with latest update

**Comment by b1uegh0st** [comment]
Cool many thanks. (and for staying patient with this transition process to CM6).
