### ISSUE TITLE
Feature Request: Heading 6 functions as a Heading instead of Pseudo-Admonition

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#60]
**Feature Requested**
I was wondering if I can use Heading 6 as a heading instead of a Pseudo-Admonition.

**Checklist**
- [X] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
since I recently switched to SlVrb's checkboxes myself, I decided to drop the h6 pseudo-Admonitions all together, since the custom checkboxes are just a so much better solution anyway. 

As a side effect, h6 become available to you again :P

**Comment by Liong1976** [comment]
Great, thanks, Chris!
