### ISSUE TITLE
Collection: Live Preview Bugs

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/shimmering-focus#61]
The purpose of this issue is to collect all bugs regarding the upcoming live preview, so I can prioritize them better.

**Comment by Madnick21** [comment]
Hey there, thanks for the awesome theme, I am facing some weird problems with my live preview panels. They are not scrollable first and foremost and then some times they are out of the frame (really low in the bottom of the page).

I hope this is the right place to report this.

**Comment by chrisgrieser** [comment]
Thanks!

I decided to use separate issues instead of one collection issues thread for live preview things. Could you open a new issue and add some screenshots / screen recordings so can get a better grasp?

(Also just so you know, I will probably not tackle Live Preview issues until the public release, since things might change and potentially bugs fixed on Obsidians side. But when Live Preview goes public, I will make it a priority.)

**Comment by Madnick21** [comment]
Ah I am such a noob, I meant Page Preview not Live. Ignore the post please I managed to have it working as indented. Thanks again for your work amazing theme!
