### ISSUE TITLE
Feature Request: Blockquote in Left Alignment

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#63]
**Feature Requested**
I was wondering if you can make an option (in the Style Setting) to make the blockquote left-aligned instead of justified. Thank you

**Checklist**
- [X] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Sure thing. that one is very simple to implement, so I've just done so 👍

**Comment by Liong1976** [comment]
Thanks a lot, Chris!

**Comment by Liong1976** [comment]
I was wondering if you can make the blockquote left-aligned in the _Preview Mode_ as well? If that's challenging I am totally fine.

**Comment by chrisgrieser** [comment]
Oh sorry, of course it should have the same type of text alignment in both modes. Simply forgot to change it for preview mode, too 🙈 

Fixed in latest update

**Comment by Liong1976** [comment]
Thanks!
