### ISSUE TITLE
Feature Request: Reduce Transclusion Size

### ISSUE THREAD

**Issue by rushikb** [chrisgrieser/shimmering-focus#67]
**Feature Requested**
reduce the size of transclusion embeds/ offer the ability to change this,  Shimmering Focus currently defaults to a much larger size for transcluded embeds relative to other themes

**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/6484525/146851400-968f13ac-e114-4e5b-b48f-c0e017c87e52.png)
![image](https://user-images.githubusercontent.com/6484525/146851406-67589068-65fd-48a2-9988-354799413ba1.png)

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
that's actually not a feature request, but a bug report 😉 

Nevertheless, found the issue, fixed with latest update.
