### ISSUE TITLE
[BUG] Folders with a lot of notes are not being displayed entirely

### ISSUE THREAD

**Issue by cashew90** [chrisgrieser/shimmering-focus#68]
**Describe the Bug**
In the navigation bar, if a folder has a lot of notes it just stops displaying them. 

**To Reproduce**
1. Go to 'File Explorer'
2. Click on 'a folder with probably 100+ notes'
3. Scroll down until it stops displaying

**Is the Problem related to Obsidian 0.13+ / Live Preview Mode?**
No. It also appears with Legacy Mode turned on.

**Relevant Screenshots**
![CleanShot 2021-12-22 at 21 38 30@2x](https://user-images.githubusercontent.com/20352339/147152469-97a23e90-32bd-403f-8c83-38effbf4c67b.png)

**Checklist**
- [ x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [ x] I checked that the issue does not occur when using the default theme.
- [ x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by daxmonson** [comment]
Came here to say the same. Also, scrolling now gets wonky and skips to different areas. The latter is really apparent in ipados when Obsidian is in slide-over mode.

**Comment by chrisgrieser** [comment]
@cashew90 Did this bug only occur after an update of Shimmering Focus it was this problem there before?

@daxmonson Could you post a screen recording of your issue?

**Comment by cashew90** [comment]
Hard to tell... I only discovered it by chance because I don't often open folders to scroll through them. Most of the time I use Quick Switcher. So I really can't tell, sorry. For the moment, I switched to the Minimal theme where everything works as intended.

**Comment by chrisgrieser** [comment]
Hmm, I have a suspicion. Could you turn off the file explorer icons in the settings and then try again?

**Comment by daxmonson** [comment]
Sure, I tried with the file explorer setting icons off and it still won’t render files names after a certain point. Tried to count exactly how many down, but the file explorer kind of skips around and loses place after a while. Will get a loom or similar recording up, will probably have to be over the holiday when I get a minute.

**Comment by cashew90** [comment]
Same for me.

**Comment by chrisgrieser** [comment]
Okay, has been fixed thanks to @SlVrb ([reference](https://discord.com/channels/686053708261228577/702656734631821413/923689323428192336))
