### ISSUE TITLE
Settings button disappears after installing

### ISSUE THREAD

**Issue by AtticusBeachy** [chrisgrieser/shimmering-focus#69]
**Describe the Bug**
I was messing around with different themes but after I installed this one the Settings cog was gone. This meant I could not turn the theme off. An extension should **never** disable your ability to easily turn it off. I hope this was not the intended behavior. 

**To Reproduce**
Install the extension on Obsidian v0.13.14

**Comment by chrisgrieser** [comment]
This *is* the intended behavior. 

- The theme's promo screenshot explicitly has a warning that this is a very minimalistic theme as the very first item.
- After installing the theme, you find a link to the README which [mentions at the very top how to access the settings with the keyboard](https://github.com/chrisgrieser/shimmering-focus#hidingshowing-ui-elements).
- The infobox after installation, the Readme, as well as the checklist for a bug report all mention that you can re-enable hidden elements via the Style Settings Plugin. Amon other things, there is an option to re-enable the ribbons (the sidebar that contains the setting button).

I do not know how else to communicate this. 🙁

**Comment by chrisgrieser** [comment]
okay, I have added yet another extra info message directly which should become visible after installing the theme. Hope this is enough now.

<img width="388" alt="Screenshot 2021-12-25 16 08 38" src="https://user-images.githubusercontent.com/73286100/147387961-1519f447-67e6-4b31-83b9-2ab118e059bf.png">

**Comment by AtticusBeachy** [comment]
Thanks for the quick response! That's an improvement, but I think it could be made more clear. Something like

> ⚠️ Minimalistic theme. No settings button. 
> 
> ⚙️ To access settings:
> - "ctrl + ," (Win/Linux)
> - "cmd + ," (Mac)
> 
> 💡 For Theme Customization:
> Install Style Settings Plugin

The perfect solution would be a one-time pop-up with the message when the theme is first installed. I don't know whether this is feasible to implement though. 

Reason for the pop-up: the first thing I want to do after installing a new theme is see what it looks like. But to see what it looks like I have to close settings. So if people are like me, they might exit settings as soon as the installation completes without bothering to scroll up and see the warning message. At which point, the user would have to re-open settings in order to see the message about how to re-open settings. 

If you can't do a pop-up, maybe you can add the warning to the promo screenshot? That would probably make it look worse though.

**Comment by chrisgrieser** [comment]
thanks for the suggested text! I updated it.

Popups are unfortunately not possible, since themes cannot really add content, only style them. (adding that info message after installation is already a hacky workaround.)

Hopefully at some point, the theme store would have the same readmes presented to you like the plugins.
