### ISSUE TITLE
Pane Navigation not visible

### ISSUE THREAD

**Issue by cashew90** [chrisgrieser/shimmering-focus#7]
Hello,

thank you for this really nice theme, which I enjoy a lot! One small issue: I use the Pane Relief Plugin, which enables per pane history, so that you can go back and forth. With your theme enabled, the two arrows are not visible anymore. Can you fix this, please? The image shows how it should look like (in the image I use the minimal theme)

![CleanShot 2021-09-05 at 13 40 34@2x](https://user-images.githubusercontent.com/20352339/132125443-63c60ce8-e72b-454b-a5f6-63b80a760f98.png)

**Comment by chrisgrieser** [comment]
With [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4), I added support for the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/). Using that plugin, you can simply re-enable the titlebar to use the Pane-Relief arrows 🙂
