### ISSUE TITLE
[BUG] There are black shades in between paragraphs/lines

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#71]
**Describe the Bug**
I am not sure if this is a bug or not, but, the shades between paragraphs/lines do not look good to me (see the screenshot below).

**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/88898230/147398228-628b7b5c-e694-4fb9-b260-525ff8b69ada.png)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
ah, thanks for the report! After looking into it, it's a bug that only in the legacy editor but not the new editor. fixed it with the latest update.

(background: some styling for the new editor had the side effect of *also* being applied to  things in the legacy editor. keeping the theme compatible with both the new and old editor is becoming a bit complicated 😅 )

**Comment by Liong1976** [comment]
Thanks, Chris!
