### ISSUE TITLE
FR: Support Tasks Plugin

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#72]
**Describe the Bug**
When I create a task with the [tasks plugin](https://github.com/schemar/obsidian-tasks), it looks fine but when i switch the reading view the bug occurs.
Also, the query doesn't render correctly in live preview or in reading view.

**Relevant Screenshots**

https://user-images.githubusercontent.com/38974541/147487437-5a797f43-14a3-43d8-a01a-2ea19a1df74e.mov

**To Reproduce**
1. Create a task with tasks plugin
2. make a query

**In which mode / editor does the bug occur?**
- [ ] Legacy Editor (or Obsidian 0.12 or below)
- [ ] New Editor
- [x] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
The tasks plugin simply is not supported yet. I'll add it to the do to list (ironically) to add support for the plugin.

**Comment by imeed166** [comment]
Okay, hope it gets supported soon.

**Comment by chrisgrieser** [comment]
just checked, most likely this is an issue on the side of the task plugin, since [in their readme, they state](https://github.com/schemar/obsidian-tasks):

> ⚠️ Tasks does not yet support Obsidian's "Live Preview". Once "Live Preview" supports the whole feature set, we will make sure Tasks is compatible.

I think even though they talk about "live preview", they mean the new editor as a whole. If the tasks plugin fully supports Obsidian 0.13+ and the issue still occurs, please re-open the issue 🙂

**Comment by imeed166** [comment]
The plugin works just fine, the problem occurred only when I used the emoji toolbar plugin and enabled this feature :

![image](https://user-images.githubusercontent.com/38974541/147511315-f5cd7055-ef89-4216-9ee3-b81f0eec1f48.png)

So no need to reopen this issue.

**Comment by chrisgrieser** [comment]
great! :)
