### ISSUE TITLE
Feature Request: color checkbox when hovering in live preview

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#73]
**Feature Requested**
When I hover over a completed checkbox, it doesn't color itself in live preview as opposed to the reading view.

**Relevant Screenshots**

https://user-images.githubusercontent.com/38974541/147489982-47a62fc1-8dd3-4133-b74d-ad765868866b.mov

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
nice catch! that one is actually a bug though, since everything is supposed to get green when hovered :P

nevertheless, fixed in the latest release

**Comment by imeed166** [comment]
Always get the label wrong 😆
