### ISSUE TITLE
Feature Request: add another shape

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#74]
**Feature Requested**
Additional to the square and circle shapes, is it possible to add another shape in between (square with rounded corners) ?

**Relevant Screenshots**

![image](https://user-images.githubusercontent.com/38974541/147500258-864cd13f-346a-438e-9190-183ca3adb110.png)

**Checklist**
- [ ] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
now this is the proper label ;)

yeah, that's possible. I'll do it when I finished the current to do list (change of accent, hover, and text colors, etc.) 😊

**Comment by chrisgrieser** [comment]
added in the latest update :)

**Comment by imeed166** [comment]
Thank you! been waiting for this. Could you also make the checkboxes the same shape, please ?

**Comment by chrisgrieser** [comment]
sure, fixed it just now.

The shape settings affects hundreds of shapes throughout the theme, so I am pretty sure that I have still overlooked some :P
