### ISSUE TITLE
Changing the colors of the highlight types

### ISSUE THREAD

**Issue by yigitozgumus** [chrisgrieser/shimmering-focus#75]
**Feature Requested**
The main highlight and 2 alternative color options are really nice additions. It would be nice to adjust their colors from the style settings so that they could be used in more contexts. 

**Relevant Screenshots**
- There is no UI change, only settings options to update the highlight colors

**Checklist**
- [x] The feature would be useful to more users than just me. 
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
done in the latest release
<img width="1040" alt="Screenshot 2022-04-04 18 46 51" src="https://user-images.githubusercontent.com/73286100/161592903-66b3694c-af68-4bae-a1d0-08346cdaadd5.png">

**Comment by ReaderGuy42** [comment]
As a tiny nitpick, would it be possible to add a color scale beneath the thing that you move around? That way you don't have to "blindly" move it (not that it's a huge spectrum, just as a thought) :)

**Comment by chrisgrieser** [comment]
uff, yeah it would be possible but it's would be quite tricky to implement, so I think I'll invest the time rather somewhere else :P

**Comment by ReaderGuy42** [comment]
Absolutely fine! That was just a thought, and not important. Thanks anyway :)

**Comment by chrisgrieser** [comment]
Nevermind, I was procrastinating and figured it out actually 😆 
<img width="1027" alt="Screenshot 2022-04-05 13 39 14" src="https://user-images.githubusercontent.com/73286100/161745924-1b51ddbf-1f4a-4df3-8d3f-3b7973831364.png">

**Comment by ReaderGuy42** [comment]
Oh wow, that looks awesome, thank you!! This isn't showing up for me yet, though?

**Comment by chrisgrieser** [comment]
try again? maybe it takes a few minutes for GitHub to update the file? 🤔

**Comment by ReaderGuy42** [comment]
Yup, there it is, thanks!! Tangentially related, I have a question on a snippet I had that no longer seems to be working.
```
.theme-dark
{ --selection-color: #90482a;

}

.theme-light
{ --selection-color: #F07847;

}

.theme-light .cm-strong,
.theme-light .markdown-preview-view strong {
	color: var(--bold-in-lightmode);
}

.vertical-tab-nav-item:last-child {
	color: var(--bold-in-lightmode);
}
```
It's supposed to cause the selection color to be different, i.e. brighter to make it easier to see (orange-ish). I'm not sure exactly when this "broke" but it no longer does that. First I thought it had to do with your theme, but it also no longer works in the default theme either. Any ideas why that might be? Not that important either, just something I noticed.

**Comment by chrisgrieser** [comment]
ah yes, that's cause I have changed a lot how colors work in preparation for a bigger color customization update. You can use this snippet to change the colors anyway:


```css
.theme-dark {
	--text-selection: #90482a;
}

.theme-light {
	--text-selection: #F07847;
}
```

---

Alternatively, you can use this CSS snippet to "unlock" some accent color style settings I am still working on. Changing the Primary Accent to Orange or blue already works. 

```css
/* "unlock" under-development-color options in the style settings
(note that some unlocked settings do not do anything yet, since it
is still work-in-progress.) */
body .style-settings-container .setting-item[data-id*="-accent-"] {
	display: flex;
}
```

**Comment by chrisgrieser** [comment]
oh never mind the snippet. I had the better idea to simply make it a style setting toggle under Misc :P

<img width="1021" alt="Screenshot 2022-04-05 14 51 05" src="https://user-images.githubusercontent.com/73286100/161757620-4edd0add-f988-45a7-b10f-05d92b5c9107.png">

**Comment by ReaderGuy42** [comment]
Thanks :)
