### ISSUE TITLE
[BUG] button overlap

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#76]
**Describe the Bug**
The "drag to rearrange" button overlaps with the macOS full screen button.

**Relevant Screenshots**

![image](https://user-images.githubusercontent.com/38974541/147871330-9436c8b7-0681-4dec-ab19-8d63c4f000ba.png)

**To Reproduce**
1. Disable the title bar ;
2. Disable ribbons ;
3. Show the header bar.

**In which mode / editor does the bug occur?**
- [x] Legacy Editor (or Obsidian 0.12 or below)
- [x] New Editor
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Huh, that's weird, it looks for me. Could be ac result of different screen resolution though, could you tell me the resolution of your display?

**Comment by chrisgrieser** [comment]
Okay, *if* the screen resolution is the cause of this, I should have fixed it with the most recent update. Could you update and check whether it's working for you now?

**Comment by imeed166** [comment]
Still the same, I use a mac (2560x1600) and an external monitor (1360x768)

**Comment by chrisgrieser** [comment]
Weird, I changed my mac's display resolution to yours and the buttons still don't overlap.

I added even more padding between the buttons. Could you update and check whether that works for you now?

If it doesn't I suspect it might be another issue caused by something else that adds CSS to the header. Could you check whether deactivating your css snippets and plugins helps?

**Comment by imeed166** [comment]
It works now 
![image](https://user-images.githubusercontent.com/38974541/147884009-edac491b-23a1-4b12-af2b-86ea0653c4d4.png)

**Comment by imeed166** [comment]
Updated the themes after disabling all the plugins (except style settings) and snippets, so don't know what was causing this

**Comment by chrisgrieser** [comment]
weird. Whatever the cause, guess as long it works, this issue is resolved! 🙂
