### ISSUE TITLE
Feature Request: line weight adjustments

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#77]
**Feature Requested**
The last update made the lines thinner than they were in previous versions. I personally like how it looked previously better.
I don't know if "line weight" is the right term for this, but it's very noticeable in the checkboxes.

**Relevant Screenshots**
I don't know how to go back to previous versions, so I can't provide any screenshots.

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
> **Relevant Screenshots**
I don't know how to go back to previous versions, so I can't provide any screenshots.

The theme has literally hundreds of borders and lines, so I still need a screenshot to know which lines you are referring to 😛

**Comment by imeed166** [comment]
For now, just the border of the checkbox, it used to be thicker (easier to recognize)
![image](https://user-images.githubusercontent.com/38974541/147883509-1a8fc189-3998-46ac-b70f-65100ca7b3f7.png)

**Comment by chrisgrieser** [comment]
That's weird, I haven't changed the line thickness of checkboxes at all. Have you maybe added a plugin or css snippet that somehow alters checkboxes? 🤔 

Anyway, I don't wanna clutter up the style settings with too specific settings, but you can make the lines thicker by adding the following css snippet. (The current weight is `2px`.)

```css
body input[type="checkbox"] {
	border-width: 3px;
}
```

**Comment by imeed166** [comment]
> That's weird, I haven't changed the line thickness of checkboxes at all. Have you maybe added a plugin or css snippet that somehow alters checkboxes? 🤔

Yeah that seems to be the case, I used another theme and the checkboxer appear thinner in it too.

> Anyway, I don't wanna clutter up the style settings with too specific settings, but you can make the lines thicker by adding the following css snippet. (The current weight is `2px`.)

Thank you, if I can't find what i causing this, I'll use this snippet.
