### ISSUE TITLE
Feature Request: Disable animations

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#78]
**Feature Requested**
A toggle to disable animations like : checkboxes filling up in settings and fading in buttons...

**Relevant Screenshots**

https://user-images.githubusercontent.com/38974541/147962848-ec20aae4-3127-4bed-b1d9-3031dfda0f0d.mov

https://user-images.githubusercontent.com/38974541/147962861-701a6964-cb86-48a4-941e-05880eded00f.mov

**Checklist**
- [ ] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
what exactly do you mean by "disabling" the animations? Just making making the changes occur instantly would be easy, removing the color change however would be a lot of work, however

**Comment by imeed166** [comment]
Yes, "making the changes occur instantly" is what I meant.

**Comment by chrisgrieser** [comment]
sure that is easy. Latest release has an option to turn off animations.
