### ISSUE TITLE
Headbar has fuzzy lines when not hovered and panes being vertically splitted

### ISSUE THREAD

**Issue by aaccqb** [chrisgrieser/shimmering-focus#8]
Hi,

Thanks a lot for the beautiful theme! I noticed a small issue on the headbars that are only displayed on hover when I split panes vertically. It is not a bit issue but makes part of the top pane sometimes hard to read. Many thanks! 

![image](https://user-images.githubusercontent.com/61416148/132167133-596982fc-02b1-4753-9276-64490b1333bf.png)

**Comment by chrisgrieser** [comment]
Hmm, unfortunately, I am not able to reproduce this issue. With [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4), I fixed some stuff with the header bar – with some luck, that update also resolves your issue?

If not, could you do a screen recording how that weird line appears?

**Comment by aaccqb** [comment]
Many thanks Chris! Yes the release 1.4 fixed issue when enable the title bar.

I attach the screen recording for the weird line when the title bar is disabled, just for your information. Really love this theme! 

https://user-images.githubusercontent.com/61416148/132464292-6a75635b-20d6-4f15-8f16-73b8a892a2fb.mov
