### ISSUE TITLE
Question: Does the special font for the Longform plugin only work in Preview mode?

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#80]
Hi Chris,

I got a question for you. In my case (I am using Legacy Editor), the specific font for the Longform plugin (Crimson Pro S) only shows in the Preview Mode?

Here is in the Editor mode:
![image](https://user-images.githubusercontent.com/88898230/147969272-ab09b93a-ae74-4e60-a061-04e85878c954.png)

Here is in the Preview mode:
![image](https://user-images.githubusercontent.com/88898230/147969395-6559c055-16b3-44fd-a9b3-88d7b82d8c99.png)

I was wondering if that is intentional?

**Comment by chrisgrieser** [comment]
no, it's not intentional. That's due to the fact how annoyingly complicated it is to make everything work in 5 views at once. :(

I looked into it and fixed it. with the latest release.

**Comment by Liong1976** [comment]
Thanks, Chris!
