### ISSUE TITLE
Feature Request: line width modification

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#81]
**Feature Requested**
It would be nice if we could change with a slider (like in sanctum theme show below) the line width in reading view mode and in live preview mode.

**Relevant Screenshots**

![image](https://user-images.githubusercontent.com/38974541/148086819-bd40d5a2-0e04-47ea-87c7-daa10688a529.png)

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
The last release includes a new Style Setting Option to adjust Readable Line length. (Works only in the new Editor.) 🙂

**Comment by imeed166** [comment]
Amazing, thank you.
