### ISSUE TITLE
[BUG] hard to read text in red button in light mode

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#82]
**Describe the Bug**
In light mode, the dark text in the red button (in the settings) is hard to view.

**Relevant Screenshots**

![image](https://user-images.githubusercontent.com/38974541/148089565-f359e821-b07a-4849-8dd7-97b13eeef744.png)

**To Reproduce**
1. Enable light mode
2. File recovery setting or any other setting with red button

**In which mode / editor does the bug occur?**
- [x] Legacy Editor
- [x] New Editor
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Version**
- [ ] I am on the latest __Insider__ release
- [x] I am on the latest __public__ release

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
For me, the button text occurs in the right color. Could you please check whether you maybe have a snippet or plugin that changes button text colors?
<img width="1432" alt="Screenshot 2022-01-04 17 23 23" src="https://user-images.githubusercontent.com/73286100/148090851-75cc05f2-5bf0-4476-a1fd-6fe329e0c87c.png">

**Comment by imeed166** [comment]
You're right, a plugin is changing the color. I'll tell you which one causes this change if I find it.

**Comment by imeed166** [comment]
Okay, so I disable each plugin one by one, and it's the style setting plugin.
It's also causing these weird gray rectangles in the middle 

![image](https://user-images.githubusercontent.com/38974541/148094137-ec800f44-fa3b-4532-a2bb-900bcb01ded4.png)

I'll file an issue there.

**Comment by chrisgrieser** [comment]
huh? how can that be, I, of course, use the style settings plugin myself and it does neither change the button text nor adds such rectangles for me? 🤔

**Comment by chrisgrieser** [comment]
the style setting splugin also does not add any css to other things, my guess is that you have some plugin or snippet that adds css and which is disabled/enabled via style settings. Maybe ask in Discord for some advice?
