### ISSUE TITLE
Feature Request: Remove transparency

### ISSUE THREAD

**Issue by Mixpap** [chrisgrieser/shimmering-focus#84]
### Feature Requested

Hi! If the theme is used with the Sliding Pane plugin uses a distracting (and resource hungry) transparency between panes. I couldn't find any option to stop it in the styling options. 

Thanks for this awesome theme by the way :) 

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Could you add a screenshot what kind of transparency you mean? The "relevant screenshot" field is there for a reason, I can't tell for your description alone what you mean ;)

**Comment by Mixpap** [comment]
Oh yes I am sorry,  

![image](https://user-images.githubusercontent.com/10127931/148462340-1184ec40-4dd2-4655-99eb-0b42890ea65a.png)

**Comment by chrisgrieser** [comment]
ah, I see! 

Thanks for the info! It's actually a side effect of a feature that I implemented a couple of weeks ago. Since I don't use Sliding Panes, I didn't know that this has this sort of side effect... :P

Fixed with the latest release!

**Comment by chrisgrieser** [comment]
btw, I finally found some time to make the rotated headers work properly with my theme. If you update, the rotated headers correctly now :)
