### ISSUE TITLE
[Bug]: default theme checkbox icons in live preview editing mode

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#88]
### Bug Description

In the last update, the checkbox icons reverted to the default look.

### Relevant Screenshot

editing view 
![image](https://user-images.githubusercontent.com/38974541/149330762-7382b86b-ef41-48cf-877e-f8cef640f062.png)
reading view
![image](https://user-images.githubusercontent.com/38974541/149330795-30119c33-c2b7-4baa-8b52-9114b5aff6c9.png)

### To Reproduce

Add task in editing live preview mode

### Obsidian Version

0.13.19

### Installer Version

0.13.14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugin](https://github.com/chrisgrieser/shimmering-focus#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
ah thank you, since I rarely use Live Preview, I haven't noticed. Fixed with the latest update
