### ISSUE TITLE
[Bug]: The Style Settings Plugin Does not Work Well

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#89]
### Bug Description

When I opened the style setting plugin it showed this:

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/88898230/149591579-557f269a-3286-4d82-8c5c-9c92f95140e7.png)

### Obsidian Version

0.13.9

### Installer Version

0.13.9

### Which editor are you using?

- [ ] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugin](https://github.com/chrisgrieser/shimmering-focus#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
ah thanks, forgot quotation marks. fixed.

**Comment by Liong1976** [comment]
Thanks, Chris!
