### ISSUE TITLE
[Bug]: Popup warning for special characters in filename is unreadable in light mode

### ISSUE THREAD

**Issue by lguenth** [chrisgrieser/shimmering-focus#91]
### Bug Description

Hey,
I've been using the theme for a few days and noticed a small bug by chance.

When creating a new file and trying to rename it by putting in some special characters which are not allowed, there is usually this popup:
![220116_153631_screenshot](https://user-images.githubusercontent.com/69049131/149664573-228e819e-33bc-4e8d-8dab-982105100105.png)

However, with Shimmering Focus (default settings, no custom CSS snippets, plugins disabled) it looks like this in light mode:
![220116_154555_screenshot](https://user-images.githubusercontent.com/69049131/149664891-d1276256-e339-4f80-8a0f-97fbc5a73b42.png)

Dark mode is fine:
![220116_154539_screenshot](https://user-images.githubusercontent.com/69049131/149664897-35a8955e-2b06-45de-a2ee-0df3548ca595.png)

I tweaked the light version a bit with Style Settings... And now it just looks like an empty box at first glance because the contrast ist so low. :upside_down_face: 
![220116_153210_screenshot](https://user-images.githubusercontent.com/69049131/149664984-f66226bf-fe21-45ad-a1c9-1ec092b747aa.png)

Thanks for creating & maintaining this theme

### To Reproduce

1. Create new note
2. Rename file
3. Type in special character which is not allowed like : /\

### Obsidian Version

0.13.19

### Installer Version

0.13.14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [x] I took note of the [specific instructions regarding those plugin](https://github.com/chrisgrieser/shimmering-focus#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
never encountered that one, since I only use legal characters in file names 😝 

fixed with latest release
