### ISSUE TITLE
Feature Request: Display vault name

### ISSUE THREAD

**Issue by pdworkman** [chrisgrieser/shimmering-focus#92]
### Feature Requested

I would like to be able to enable the vault name on the title bar. I have title bar enabled, but no title. I have multiple vaults open, and not being able to see which one I am in when cycling through vaults is irritating. 

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
The latest update includes a style setting to show the vault name in the titlebar 👍
