### ISSUE TITLE
Feature Request: Focus mode on iPad

### ISSUE THREAD

**Issue by albfaggion** [chrisgrieser/shimmering-focus#93]
### Feature Requested

My request is an option to hide the note title on iPad while editing/viewing a note. I believe Minimal Theme hides the title by default. Thank you!

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
implemented in latest release :)

**Comment by albfaggion** [comment]
Thank you very much! It was very kind of you to implement it so fast 👍
