### ISSUE TITLE
[Bug]: The first letter of file titles is occluded when using Sliding-Panes (Andy's Mode)

### ISSUE THREAD

**Issue by AlexRimor** [chrisgrieser/shimmering-focus#94]
### Bug Description

The first letter of file titles is occluded when using Sliding-Panes (Andy's Mode).
I have noted the settings for Sliding-Panes in the current documentation.
Can you add an option for the style settings plugin to get around this issue?
Thanks for an amazing theme!

### Relevant Screenshot

![Sliding-Panes settings](https://user-images.githubusercontent.com/81555748/150477180-07fb19b6-054b-4386-8233-05c0afe2ae2a.png)
![Example 1](https://user-images.githubusercontent.com/81555748/150477188-b99a6f42-b5a3-4529-8002-ac45400b87ee.png)

### Obsidian Version

0.13.19

### Installer Version

0.12.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://github.com/chrisgrieser/shimmering-focus#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
thanks, haven't noticed, is fixed.

**Comment by AlexRimor** [comment]
That was fast. Thank you!

**Comment by chrisgrieser** [comment]
well, it was literally one line of code that needed to be added, such small stuff is easy to do during coffee break 🙂
