### ISSUE TITLE
[Bug]: Multiple Notes open at once: vertical split results in a bug

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#99]
### Bug Description

I have four panes open and want to add another one, by vertically splitting one on the top. This results in a bug where that pane (and the newly created one) are not visible. See screen recording below for example.

I have tested this in the default theme, and this does NOT happen there. I have turned off all plugins and snippets and it still happens.

This also doesn't appear to happen in the bottom panes, only the top two. I have also tried closing and reopening Obsidian, but the bug persists.

I've been mostly using Legacy mode, but I just tested it, it also happens in the new Preview mode.

### Relevant Screenshot

https://user-images.githubusercontent.com/71895400/151190848-85c30c0e-8dd1-4b68-b8b9-0c16653bb586.mp4

### To Reproduce

1. open multiple panes/notes
2. try to vertically split the top row
3. see bug

### Obsidian Version

0.13.19

### Installer Version

0.12.15

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by s-kyy** [comment]
+1 also occurs on windows 10

**Comment by chrisgrieser** [comment]
I found the cause; it's actually gigantic resize handles that under specific circumstances get enlarged to maximum height 😅 

That's a weird bug, anyway it's fixed. (Along the way improved header mechanics for horizontal splits & fixed another bug occurring there, too.)

**Comment by ReaderGuy42** [comment]
Thank you :smile:
